var CHALLENGE_75_ID='winter-arc-75-me-v1';
var LEGACY_CHALLENGE_75_ID='intentional-75-2026';

function getChallenge75(){var stored=STATE.challenges&&STATE.challenges[CHALLENGE_75_ID]||null,p=typeof winterArcPlan==='function'?winterArcPlan():null;if(!stored||!p)return stored;return Object.assign({},stored,{startDate:p.startDate,endDate:p.endDate,ruleIds:p.challenge.rules.map(function(rule){return rule.id})})}
function challenge75Phase(dateKey){var c=getChallenge75();if(!c)return 'none';var key=dateKey||localDateKey(new Date());return key<c.startDate?'before':key>c.endDate?'after':'active'}
function challenge75DayNumber(dateKey){var c=getChallenge75();if(!c)return 0;var key=dateKey||localDateKey(new Date());if(key<c.startDate)return 0;if(key>c.endDate)return 75;return Math.max(1,Math.min(75,habitDayDiff(c.startDate,key)+1))}
function challenge75Habit(key){var c=getChallenge75(),id=c&&c.habitIds&&c.habitIds[key];return id?(STATE.habits||[]).find(function(h){return h&&h.id===id}):null}
function challenge75CareerHabit(){var c=STATE.challenges&&STATE.challenges[LEGACY_CHALLENGE_75_ID],id=c&&c.habitIds&&c.habitIds.career;return id?(STATE.habits||[]).find(function(h){return h&&h.id===id}):null}
function challenge75OwnsHabit(id){var c=getChallenge75();if(!c||challenge75Phase(localDateKey(new Date()))!=='active')return false;return Object.keys(c.habitIds||{}).some(function(key){return c.habitIds[key]===id})}
function challenge75WaterStatus(dateKey){var status=typeof winterArcDailyStatus==='function'?winterArcDailyStatus(dateKey):{rows:[]};var row=status.rows.find(function(item){return item.id==='water'});return row||{done:false,ml:0,targetMl:2000,glasses:0}}
function challenge75DailyStatus(dateKey){var status=typeof winterArcDailyStatus==='function'?winterArcDailyStatus(dateKey):{rows:[],done:0,total:0,complete:false};return {rows:status.rows.map(function(row){return Object.assign({key:row.id},row)}),done:status.done,total:status.total,complete:status.complete,water:status.rows.find(function(row){return row.id==='water'})||null}}
function challenge75CareerStatus(dateKey){var habit=challenge75CareerHabit();if(!habit)return {habit:null,count:0,target:3,met:false,todayDone:false,state:'inactive'};var progress=getHabitProgress(habit,dateKey,dateKey);return {habit:habit,count:progress.count,target:progress.target||3,met:progress.met,todayDone:!!(habit.logs&&habit.logs[dateKey]),state:getHabitDayState(habit,dateKey,dateKey)}}
function challenge75PerfectDays(asOfKey){var c=getChallenge75();if(!c)return 0;var cutoff=asOfKey<c.endDate?asOfKey:c.endDate;if(cutoff<c.startDate)return 0;var count=0;for(var day=habitDate(c.startDate);localDateKey(day)<=cutoff;day=habitAddDays(day,1)){var s=challenge75DailyStatus(localDateKey(day));if(s.complete)count++}return count}
function challenge75CompactSummary(dateKey){var c=getChallenge75();if(!c)return null;var key=dateKey||localDateKey(new Date()),phase=challenge75Phase(key);if(phase==='before')return {phase:phase,text:'Winter Arc · starts '+fmtDate(c.startDate)};if(phase==='after')return {phase:phase,text:'Winter Arc · closed '+fmtDate(c.startDate)+'–'+fmtDate(c.endDate)};var daily=challenge75DailyStatus(key),career=challenge75CareerStatus(key);return {phase:phase,text:'Day '+challenge75DayNumber(key)+' of 75 · '+daily.done+'/8 today · Career '+career.count+'/'+career.target}}

function challenge75ToggleHabit(habitId){
  if(!habitId||challenge75Phase(localDateKey(new Date()))!=='active')return false;var habit=(STATE.habits||[]).find(function(item){return item&&item.id===habitId});if(!habit)return false;
  var today=localDateKey(new Date()),state=getHabitDayState(habit,today,today),manual=habitManualCompleted(habit,today);if(!manual&&state!=='todo'&&state!=='optional')return false;
  var selector='[data-challenge-habit="'+habitId+'"]',restoreFocus=!!(document.activeElement&&document.activeElement.matches&&document.activeElement.matches(selector));
  var snapshot=typeof _clone==='function'?_clone(STATE):JSON.parse(JSON.stringify(STATE));ensureHabitProvenance(habit);ensureHabitLifecycle(habit);setManualHabitCompletion(habit,today,!manual);if(!saveStateOrRollback(snapshot))return false;
  emitLifeHubChange({action:'challenge-habit-toggle',entityId:habitId,dateKeys:[today],domains:['habits'],source:'challenge'});if(restoreFocus)setTimeout(function(){var replacement=document.querySelector(selector);if(replacement)replacement.focus()},0);return true;
}
function challenge75LogWater(){var today=localDateKey(new Date()),glasses=Number((STATE.water||{})[today]||0),restore=!!(document.activeElement&&document.activeElement.matches&&document.activeElement.matches('[data-challenge-water]'));if(typeof logWaterGlass==='function')logWaterGlass(glasses+1);if(restore)setTimeout(function(){var replacement=document.querySelector('[data-challenge-water]');if(replacement)replacement.focus()},0)}
function challenge75ReadingAction(){if(STATE.reading&&STATE.reading.activeSessionId)finishReadingTimer();else startReadingTimer(localDateKey(new Date()));if(typeof refreshPlannerCards==='function')refreshPlannerCards(['challenge'])}
function challenge75RuleAction(row,key){if(row.id==='water')return 'challenge75LogWater()';if(row.id==='duolingo'||row.id==='manna')return row.habitId?'challenge75ToggleHabit(\''+row.habitId+'\')':'';if(row.id==='reading')return 'challenge75ReadingAction()';if(row.id==='workout')return 'openWinterArcWorkout(\''+key+'\')';return 'openWinterArcCheckIn(\''+key+'\')'}
function challenge75RuleMeta(row){if(row.meta)return row.meta;if(row.id==='workout')return 'Plan session';if(row.id==='eating')return '120g+ protein · 1,700–2,100 kcal';if(row.id==='alcohol')return 'Record today’s result';return ''}

function renderChallenge75Card(todayKey){
  var c=getChallenge75();if(!c)return '';var key=todayKey||localDateKey(new Date()),phase=challenge75Phase(key),html='<div class="card planner-card challenge75-card" id="planner-challenge-card"><div class="challenge75-head"><div><div class="challenge75-kicker">WINTER ARC · 75 ME</div><div class="challenge75-title">My eight for today</div></div>';
  if(phase==='active')html+='<div class="challenge75-day">Day '+challenge75DayNumber(key)+'<span>/75</span></div>';html+='</div>';
  if(phase==='before')html+='<div class="challenge75-before">Starts Monday 5 October · your dated plan is ready.</div><div class="challenge75-rule-note">10k steps · 45-minute plan workout · 2L water · Duolingo · 15 minutes reading · Manna · alcohol rule · eating well. A day counts at 8/8.</div>';
  else if(phase==='after')html+='<div class="challenge75-before">5 October–18 December · '+challenge75PerfectDays(c.endDate)+' fully checked days recorded.</div><div class="challenge75-rule-note">The block is closed and every historical record stays available.</div>';
  else{
    var daily=challenge75DailyStatus(key);html+='<div class="challenge75-progress"><span style="width:'+(challenge75DayNumber(key)/75*100)+'%"></span></div><div class="challenge75-summary">Today · '+daily.done+' of 8'+(daily.complete?' · full day ✓':'')+'</div><div class="challenge75-grid">';
    html+=daily.rows.map(function(row){var action=challenge75RuleAction(row,key),activeReading=row.id==='reading'&&STATE.reading&&STATE.reading.activeSessionId,focusAttr=row.habitId?' data-challenge-habit="'+escapeHtml(row.habitId)+'"':row.id==='water'?' data-challenge-water="true"':'';return '<button type="button"'+focusAttr+' class="challenge75-row'+(row.done?' done':'')+'"'+(action?' onclick="'+action+'"':' disabled')+' aria-pressed="'+(row.done?'true':'false')+'"><span class="challenge75-check">'+(row.done?'✓':row.icon)+'</span><span class="challenge75-label">'+escapeHtml(row.label)+'</span><span class="challenge75-meta">'+escapeHtml(activeReading?'Timer running · tap to finish':challenge75RuleMeta(row))+'</span></button>'}).join('');
    html+='</div><div class="challenge75-card-actions"><button type="button" class="btn btn-sm btn-ghost" onclick="openWinterArcCheckIn(\''+key+'\')">Daily check-in</button></div><div class="challenge75-rule-note">Never miss twice. A missed day stays missed; nothing resets. Clinical guidance always wins.</div>';
  }
  return html+'</div>';
}

function challenge75DateKeys(){var c=getChallenge75();if(!c)return [];var keys=[];for(var day=habitDate(c.startDate);localDateKey(day)<=c.endDate;day=habitAddDays(day,1))keys.push(localDateKey(day));return keys}
function challenge75JourneyModel(asOfKey){
  var c=getChallenge75();if(!c)return null;var today=asOfKey||localDateKey(new Date()),cutoff=today<c.startDate?null:(today>c.endDate?c.endDate:today),dateKeys=challenge75DateKeys(),doneChecks=0,elapsedDays=0,perfectDays=0,weeks={};
  var days=dateKeys.map(function(key,index){var daily=challenge75DailyStatus(key),elapsed=!!cutoff&&key<=cutoff,state='future';if(elapsed){elapsedDays++;doneChecks+=daily.done;if(daily.complete){state='complete';perfectDays++}else if(daily.done>0)state='partial';else state='open'}if(key===today&&challenge75Phase(today)==='active')state='current '+state;var wk=weekKey(habitDate(key));if(!weeks[wk])weeks[wk]={key:wk,dates:[],elapsedDates:[],doneChecks:0,totalChecks:0,perfectDays:0};weeks[wk].dates.push(key);if(elapsed){weeks[wk].elapsedDates.push(key);weeks[wk].doneChecks+=daily.done;weeks[wk].totalChecks+=daily.total;if(daily.complete)weeks[wk].perfectDays++}return {key:key,number:index+1,state:state,done:daily.done,total:daily.total}});
  var careerHabit=challenge75CareerHabit(),weekRows=Object.keys(weeks).sort().map(function(key,index){var week=weeks[key],last=week.elapsedDates.length?week.elapsedDates[week.elapsedDates.length-1]:null,career={count:0,target:3,met:false};if(careerHabit&&last){var progress=getHabitProgress(careerHabit,key,last);career={count:progress.count,target:progress.target||3,met:progress.met}}return {number:index+1,key:key,dates:week.dates,elapsed:week.elapsedDates.length,doneChecks:week.doneChecks,totalChecks:week.totalChecks,perfectDays:week.perfectDays,career:career}});
  return {challenge:c,today:today,phase:challenge75Phase(today),dayNumber:challenge75DayNumber(today),days:days,weeks:weekRows,elapsedDays:elapsedDays,remainingDays:75-elapsedDays,doneChecks:doneChecks,totalChecks:elapsedDays*8,perfectDays:perfectDays};
}
function renderChallenge75Journey(){
  var el=document.getElementById('planner-journey');if(!el)return;var model=challenge75JourneyModel(localDateKey(new Date()));if(!model){el.innerHTML='<div class="card planner-card">Winter Arc is not configured yet.</div>';return}var phaseLabel=model.phase==='before'?'Starts 5 October':model.phase==='after'?'Journey complete':'Day '+model.dayNumber+' of 75';
  var html='<section class="challenge-journey-hero card"><div><div class="challenge75-kicker">WINTER ARC · 75 ME</div><h2>Your journey</h2><p>5 October–18 December · 8/8 makes a full day. Imperfect days never reset the calendar.</p></div><div class="challenge-journey-phase">'+escapeHtml(phaseLabel)+'</div></section><div class="challenge-journey-stats"><div class="card"><strong>'+model.elapsedDays+'</strong><span>days elapsed</span></div><div class="card"><strong>'+model.perfectDays+'</strong><span>8/8 days</span></div><div class="card"><strong>'+model.doneChecks+(model.totalChecks?' / '+model.totalChecks:'')+'</strong><span>daily checks</span></div><div class="card"><strong>'+model.remainingDays+'</strong><span>days remaining</span></div></div>';
  html+='<section class="card planner-card challenge-calendar-card"><div class="planner-card-head"><span class="planner-card-title">The 75 days</span><span class="planner-card-hint">read-only progress</span></div><div class="challenge-calendar" role="list" aria-label="75 Me calendar">'+model.days.map(function(day){var label=habitDate(day.key).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});return '<div role="listitem" class="challenge-calendar-day '+day.state+'" title="'+escapeHtml(label+' · '+day.done+'/'+day.total)+'" aria-label="Day '+day.number+', '+escapeHtml(label)+', '+day.done+' of '+day.total+' checks"><span>'+day.number+'</span><small>'+day.done+'/'+day.total+'</small></div>'}).join('')+'</div><div class="challenge-calendar-legend"><span><i class="complete"></i>8/8</span><span><i class="partial"></i>in progress</span><span><i class="open"></i>no checks</span><span><i class="future"></i>future</span></div></section>';
  html+='<section class="card planner-card challenge-weeks-card"><div class="planner-card-head"><span class="planner-card-title">Week by week</span></div><div class="challenge-week-list">'+model.weeks.map(function(week){return '<div class="challenge-week-row"><span class="challenge-week-num">W'+week.number+'</span><span class="challenge-week-dates">'+escapeHtml(fmtDate(week.dates[0])+'–'+fmtDate(week.dates[week.dates.length-1]))+'</span><span>'+(week.elapsed?week.doneChecks+'/'+week.totalChecks:'Not started')+'</span><span>'+(week.elapsed?'Career '+week.career.count+'/'+week.career.target:'Career —')+'</span><span>'+week.perfectDays+' full day'+(week.perfectDays===1?'':'s')+'</span></div>'}).join('')+'</div></section>';
  html+='<section class="card planner-card challenge-rules-card"><div class="planner-card-head"><span class="planner-card-title">Rules & guardrails</span></div><div class="challenge-rules-grid"><div><strong>Keep going</strong><span>Never miss twice. A miss stays on that day; do not reset.</span></div><div><strong>Train safely</strong><span>Pain changes the plan. Chest symptoms mean full rest. Your clinician wins.</span></div><div><strong>Eat well</strong><span>120g+ protein and 1,700–2,100 kcal, or confirm the balanced portion guide.</span></div><div><strong>Career stays separate</strong><span>Three intentional career blocks each week, outside the daily eight.</span></div></div></section>';el.innerHTML=html;
}
function renderChallenge75CareerCard(todayKey){var key=todayKey||localDateKey(new Date()),phase=challenge75Phase(key),c=getChallenge75(),career=challenge75CareerStatus(phase==='after'&&c?c.endDate:key),html='<section class="card planner-card challenge-career-page-card"><div class="planner-card-head"><span class="planner-card-title">Career Focus</span><span class="planner-card-count">'+career.count+' / '+career.target+'</span></div><div class="challenge-career-progress"><span style="width:'+Math.min(100,career.count/Math.max(1,career.target)*100)+'%"></span></div><p>Three intentional blocks each week. This rhythm remains separate from the eight daily Winter Arc rules.</p>';if(phase==='before')html+='<div class="challenge75-rule-note">Tracking starts Monday 5 October.</div>';else if(phase==='after')html+='<div class="challenge75-rule-note">Final challenge week · '+career.count+'/'+career.target+' blocks recorded.</div>';else if(career.habit)html+=career.met&&!career.todayDone?'<span class="challenge-career-met">✓ Weekly target met</span>':'<button type="button" class="btn '+(career.todayDone?'btn-ghost':'btn-accent')+'" onclick="challenge75ToggleHabit(\''+career.habit.id+'\')">'+(career.todayDone?'Undo today’s block':'Log a Career Focus block')+'</button>';return html+'</section>'}
