// DASHBOARD
// ============================================================
function renderDashboard(){
  var now=new Date();var todayKey=localDateKey(now);
  var hr=now.getHours();var greeting=hr<12?'Good morning':hr<18?'Good afternoon':'Good evening';
  var gEl=document.getElementById('dash-greeting');if(gEl)gEl.textContent=greeting+', Kai \u2728';
  var dEl=document.getElementById('dash-date-sub');if(dEl)dEl.textContent=now.toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  var qEl=document.getElementById('dash-quote');if(qEl)qEl.textContent='You did not wake up to be mediocre.';
  loadDailyHighlight();
  var goalsDone=STATE.goals.filter(function(g){return g.done}).length;
  var habitsToday=STATE.habits.filter(function(h){return h.logs[todayKey]}).length;
  var rmProgress=function(){var td=0,ti=0;RM_MONTHS.forEach(function(m){var p=rmGetProgress(m);td+=p.done;ti+=p.total});return ti===0?0:Math.round(td/ti*100)}();
  var sEl=document.getElementById('dash-stats');
  if(sEl)sEl.innerHTML='<div class="card" style="border-top:3px solid var(--accent)"><div class="card-label">Goals completed</div><div class="stat-big">'+goalsDone+'/'+STATE.goals.length+'</div><div class="stat-sub">annual goals</div></div><div class="card" style="border-top:3px solid var(--gold)"><div class="card-label">Habits today</div><div class="stat-big">'+habitsToday+'/'+STATE.habits.length+'</div><div class="stat-sub">logged today</div></div><div class="card" style="border-top:3px solid var(--teal)"><div class="card-label">Roadmap progress</div><div class="stat-big">'+rmProgress+'%</div><div class="stat-sub">overall plan</div></div>';
  var gpEl=document.getElementById('dash-goals-preview');
  if(gpEl){var catColors={Finance:'#7a8fa6',Fitness:'#9b7b8a',Career:'#d4845a',Personal:'#6b9e7a'};gpEl.innerHTML=STATE.goals.slice(0,5).map(function(go){var isDone=go.done;var col=catColors[go.cat]||'var(--accent)';return '<div style="display:flex;align-items:center;gap:10px;padding:7px 0;border-bottom:1px solid var(--border);'+(isDone?'opacity:0.55':'')+'"><div onclick="toggleGoalDone(\''+go.id+'\');renderDashboard()" style="width:22px;height:22px;border-radius:50%;border:2px solid '+(isDone?'var(--mint)':col)+';cursor:pointer;display:flex;align-items:center;justify-content:center;flex-shrink:0;background:'+(isDone?'var(--mint)':'transparent')+'">'+(isDone?'<span style="color:#fff;font-size:11px;font-weight:700">✓</span>':'')+'</div><span style="flex:1;font-size:12px;font-weight:500;'+(isDone?'text-decoration:line-through;color:var(--text3)':'')+'">'+go.name+'</span><span class="badge badge-'+go.badge+'" style="font-size:9px;padding:2px 7px">'+go.cat+'</span></div>'}).join('')+'<button class="btn btn-ghost btn-sm" onclick="nav(\'goals\')" style="margin-top:8px;width:100%;justify-content:center">Manage all \u2192</button>'};
  var days7=weekDays(weekKey(now));var dl=['S','M','T','W','T','F','S'];
  var hpEl=document.getElementById('dash-habits-preview');
  if(hpEl)hpEl.innerHTML=STATE.habits.slice(0,5).map(function(h){return '<div style="display:flex;align-items:center;gap:6px;padding:7px 0;border-bottom:1px solid var(--border)"><span style="flex:1;font-size:12px">'+h.name+'</span><div style="display:flex;gap:3px">'+days7.map(function(d,i){var done=h.logs[d];var isT=d===todayKey;return '<div style="width:20px;height:20px;border-radius:4px;border:1px solid '+(done?'var(--accent)':isT?'rgba(160,82,45,.3)':'var(--border2)')+';background:'+(done?'var(--accent)':'transparent')+';font-size:9px;display:flex;align-items:center;justify-content:center;color:'+(done?'#fff':'var(--text3)')+';cursor:pointer" onclick="quickToggleHabit(\''+h.id+'\',\''+d+'\')">'+dl[i]+'</div>'}).join('')+'</div></div>'}).join('')+'<button class="btn btn-ghost btn-sm" onclick="nav(\'habits\')" style="margin-top:8px;width:100%;justify-content:center">View all \u2192</button>';
  renderDashMoodCheckin();
  var gEl2=document.getElementById('dash-gratitude-preview');
  if(gEl2){var todayJ=(STATE.journal||{})[todayKey]||{};var grat=todayJ.gratitude||'';if(grat){var lines=grat.split('\n').filter(function(l){return l.trim()}).slice(0,3);gEl2.innerHTML=lines.map(function(l){return '<div style="display:flex;align-items:flex-start;gap:8px;padding:7px 0;border-bottom:1px solid var(--border)"><span style="color:var(--gold)">\ud83d\ude4f</span><span style="font-size:12px">'+l.replace(/^\d+.\s*/,'')+'</span></div>'}).join('')+'<button class="btn btn-ghost btn-sm" onclick="nav(\'gratitude\')" style="margin-top:6px;width:100%;justify-content:center">View all \u2192</button>'}else{gEl2.innerHTML='<div style="font-size:12px;color:var(--text3);text-align:center;padding:12px 0">Nothing logged today</div><button class="btn btn-accent btn-sm" onclick="openModal(\'addGratitude\')" style="width:100%;justify-content:center">+ Log gratitude</button>'}}
  var recent=(STATE.workouts||[]).slice(-3).reverse();
  var wpEl=document.getElementById('dash-workouts-preview');
  if(wpEl)wpEl.innerHTML=recent.length?recent.map(function(w){return '<div style="display:flex;align-items:center;gap:9px;padding:8px 0;border-bottom:1px solid var(--border)"><div style="flex:1"><div style="font-size:12px;font-weight:500">'+w.name+'</div><div style="font-size:11px;color:var(--text2)">'+((w.muscleGroups||[]).join(', '))+' \u00b7 '+fmtDate(w.date)+'</div></div></div>'}).join('')+'<button class="btn btn-ghost btn-sm" onclick="nav(\'workout\')" style="margin-top:8px;width:100%;justify-content:center">View all \u2192</button>':'<div class="empty" style="padding:12px 0"><div style="font-size:28px;margin-bottom:6px">\ud83c\udfcb\ufe0f</div>No sessions yet</div><button class="btn btn-accent btn-sm" onclick="openModal(\'startSession\')" style="width:100%;justify-content:center">+ Start session</button>';
  renderDashboardRelationships();
  var tExp=(STATE.expenses||[]).reduce(function(s,e){return s+Number(e.amount)},0);var tInc=(STATE.income||[]).reduce(function(s,i){return s+Number(i.amount)},0);var tDebt=(STATE.debts||[]).reduce(function(s,d){return s+Number(d.balance)},0);var tSav=(STATE.accounts||[]).reduce(function(s,a){return s+Number(a.balance)},0);var left=tInc-tExp;
  var fpEl=document.getElementById('dash-finance-preview');
  if(fpEl)fpEl.innerHTML='<div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:10px"><div class="card-sm"><div style="font-size:11px;color:var(--text3)">Savings</div><div style="font-size:18px;font-family:var(--serif);font-weight:600;color:var(--accent)">'+fmtMoney(tSav)+'</div></div><div class="card-sm"><div style="font-size:11px;color:var(--text3)">Total debt</div><div style="font-size:18px;font-family:var(--serif);font-weight:600;color:var(--red)">'+fmtMoney(tDebt)+'</div></div></div><div style="font-size:11px;color:var(--text2)">'+fmtMoney(tInc)+' in \u00b7 '+fmtMoney(tExp)+' out \u00b7 <span style="color:'+(left>=0?'var(--mint)':'var(--red)')+'">'+fmtMoney(Math.abs(left))+' '+(left>=0?'left over':'over')+'</span></div><button class="btn btn-ghost btn-sm" onclick="nav(\'finance\')" style="margin-top:8px;width:100%;justify-content:center">View finance \u2192</button>';
  var rpEl=document.getElementById('dash-roadmap-preview');
  if(rpEl){var curRM=RM_MONTHS.find(function(m){return m.year===now.getFullYear().toString()&&m.name===now.toLocaleDateString('en-GB',{month:'long'})});if(!curRM)curRM=RM_MONTHS[0];var rp=rmGetProgress(curRM);var nextItems=[];curRM.sections.forEach(function(sec,si){sec.items.forEach(function(item,ii){if(!rmIsDone(curRM.id,si,ii))nextItems.push({text:item.text})})});rpEl.innerHTML='<div style="margin-bottom:10px"><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:4px"><span style="font-weight:600">'+curRM.name+' '+curRM.year+'</span><span style="color:'+rmPctColor(rp.pct)+'">'+rp.pct+'%</span></div><div class="pbar-wrap"><div class="pbar" style="width:'+rp.pct+'%;background:'+rmPctColor(rp.pct)+'"></div></div><div style="font-size:11px;color:var(--text3)">'+rp.done+'/'+rp.total+' tasks done</div></div>'+(nextItems.length?nextItems.slice(0,3).map(function(i){return '<div style="font-size:11px;color:var(--text2);padding:5px 0;border-bottom:1px solid var(--border);display:flex;gap:6px"><span style="color:var(--text3)">\u2192</span>'+i.text+'</div>'}).join(''):'<div style="font-size:11px;color:var(--mint);padding:8px 0">\u2713 All tasks complete this month!</div>')+'<button class="btn btn-ghost btn-sm" onclick="nav(\'roadmap\')" style="margin-top:8px;width:100%;justify-content:center">Open Roadmap \u2192</button>'}
}

function quickToggleHabit(hid,day){var h=STATE.habits.find(function(x){return x.id===hid});if(!h)return;var wasDone=h.logs[day];h.logs[day]=!h.logs[day];saveState();renderDashboard();if(!wasDone&&h.logs[day]){var s=habitStreak(h);if(s===7||s===14||s===21||s===30){fireConfetti();showCelebrationToast(h.name+' — '+s+' day streak!','🔥')}}}

// GOALS (simplified)
function renderGoals(){var catColors={Finance:'#7a8fa6',Fitness:'#9b7b8a',Career:'#d4845a',Personal:'#6b9e7a'};var all=STATE.goals||[];var doneCount=all.filter(function(g){return g.done}).length;var total=all.length;var pct=total>0?Math.round(doneCount/total*100):0;var sumEl=document.getElementById('goals-summary');if(sumEl&&total>0){var sh='<div style="display:flex;gap:12px;flex-wrap:wrap">';
/* Overall progress card */
sh+='<div class="card" style="flex:1;min-width:200px;padding:14px 20px;display:flex;align-items:center;gap:16px;flex-wrap:wrap"><div style="font-size:13px;font-weight:500;color:var(--text2)">'+doneCount+' of '+total+' goals completed</div><div style="flex:1;min-width:120px;height:6px;background:var(--bg4);border-radius:3px;overflow:hidden"><div style="height:100%;width:'+pct+'%;background:var(--mint);border-radius:3px;transition:width .4s"></div></div><span style="font-size:13px;font-weight:600;color:var(--mint)">'+pct+'%</span></div>';
/* Category breakdown */
var cats=['Finance','Fitness','Career','Personal'];
sh+='<div class="card" style="min-width:200px;padding:14px 20px;display:flex;gap:12px;align-items:center;flex-wrap:wrap">';
cats.forEach(function(c){var catAll=all.filter(function(g){return g.cat===c});var catDone=catAll.filter(function(g){return g.done}).length;if(catAll.length>0)sh+='<div style="text-align:center"><div style="font-size:16px;font-family:var(--serif);font-weight:600;color:'+(catColors[c]||'var(--accent)')+'">'+catDone+'/'+catAll.length+'</div><div style="font-size:9px;color:var(--text3);text-transform:uppercase;letter-spacing:.05em">'+c+'</div></div>'});
sh+='</div></div>';
/* Up next — most urgent undone goal */
var upcoming=all.filter(function(g){return !g.done&&g.deadline}).sort(function(a,b){return a.deadline.localeCompare(b.deadline)});
if(upcoming.length){var ug=upcoming[0];var udl=daysLeft(ug.deadline);var overdue=udl<0;sh+='<div style="background:linear-gradient(135deg,#fdf6e8,#f2e8d8);border:1.5px solid '+(overdue?'var(--red)':'var(--gold)')+';border-radius:var(--radius);padding:12px 18px;margin-top:12px;display:flex;align-items:center;gap:12px"><div style="font-size:22px">'+(overdue?'⚠️':'🎯')+'</div><div style="flex:1"><div style="font-size:10px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:'+(overdue?'var(--red)':'var(--gold)')+'">Up next</div><div style="font-size:14px;font-weight:600;margin-top:2px">'+ug.name+'</div></div><div style="text-align:right"><div style="font-size:13px;font-weight:600;color:'+(overdue?'var(--red)':'var(--text)')+'">'+( overdue?Math.abs(udl)+' days overdue':udl+' days left')+'</div><div style="font-size:10px;color:var(--text3)">'+fmtDate(ug.deadline)+'</div></div></div>'}
sumEl.innerHTML=sh}else if(sumEl){sumEl.innerHTML=''}
var filtered=all;if(goalFilter==='Done')filtered=all.filter(function(g){return g.done});else if(goalFilter==='Active')filtered=all.filter(function(g){return !g.done});else if(goalFilter!=='all')filtered=all.filter(function(g){return g.cat===goalFilter});
var el=document.getElementById('goals-container');if(!el)return;if(!filtered.length){el.innerHTML='<div class="empty"><div class="empty-icon">\ud83c\udfaf</div>'+(total>0?'No goals match this filter':'No goals yet. Add one!')+'</div>';return}
el.innerHTML=filtered.map(function(go){var isDone=go.done;var dl=daysLeft(go.deadline);var col=catColors[go.cat]||'var(--accent)';var overdue=!isDone&&dl<0;
var h='<div class="card goal-item" style="margin-bottom:12px;border-left:4px solid '+col+';'+(isDone?'opacity:0.65;':'')+'"><div style="display:flex;align-items:flex-start;gap:14px">';
/* Tickbox */
h+='<div onclick="toggleGoalDone(\''+go.id+'\')" style="width:28px;height:28px;border-radius:50%;border:2px solid '+(isDone?'var(--mint)':col)+';cursor:pointer;display:flex;align-items:center;justify-content:center;flex-shrink:0;margin-top:2px;transition:all .15s;background:'+(isDone?'var(--mint)':'transparent')+'">'+(isDone?'<span style="color:#fff;font-size:14px;font-weight:700">✓</span>':'')+'</div>';
/* Content */
h+='<div style="flex:1;min-width:0"><div style="display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin-bottom:4px"><span class="badge badge-'+go.badge+'">'+go.cat+'</span>';
if(isDone)h+='<span class="badge badge-done">Done</span>';
else if(overdue)h+='<span class="badge badge-risk">Overdue</span>';
h+='</div>';
h+='<div style="font-size:15px;font-weight:600;'+(isDone?'text-decoration:line-through;color:var(--text3)':'')+'">'+go.name+'</div>';
if(go.desc)h+='<div style="font-size:12px;color:var(--text2);margin-top:3px;'+(isDone?'text-decoration:line-through':'')+'">'+go.desc+'</div>';
/* Deadline */
if(go.deadline){h+='<div style="font-size:11px;margin-top:6px;color:'+(overdue?'var(--red)':'var(--text3)')+'">📅 '+(isDone?'Completed':'Due '+fmtDate(go.deadline)+(dl>0?' · '+dl+' days left':''))+'</div>'}
h+='<button class="goal-roadmap-link" onclick="nav(\'roadmap\')">\ud83d\uddd3\ufe0f Monthly steps in Roadmap</button>';
h+='</div>';
/* Actions */
h+='<div class="goal-actions"><button class="btn btn-sm btn-ghost" onclick="openModal(\'editGoal\',\''+go.id+'\')">Edit</button><button class="btn btn-sm btn-danger" onclick="deleteGoal(\''+go.id+'\')">×</button></div>';
h+='</div></div>';return h}).join('')}
function filterGoals(cat,btn){goalFilter=cat;document.querySelectorAll('#goal-filters .filter-btn').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');renderGoals()}
function toggleGoalDone(id){var goal=STATE.goals.find(function(x){return x.id===id});if(!goal)return;var wasDone=goal.done;goal.done=!goal.done;if(goal.done)goal.progress=goal.target;saveState();renderGoals();if(!wasDone&&goal.done){fireConfetti({count:150,duration:3000});showCelebrationToast('Goal complete: '+goal.name,'🎯')}}
function saveGoal(){var name=((document.getElementById('m-gname')||{}).value||'').trim();if(!name)return;var cat=(document.getElementById('m-gcat')||{}).value||'Personal';var badges={Finance:'fin',Fitness:'fit',Career:'car',Personal:'per'};STATE.goals.push({id:g(),name:name,cat:cat,badge:badges[cat]||'per',desc:(document.getElementById('m-gdesc')||{}).value||'',target:100,unit:'%',direction:'up',deadline:(document.getElementById('m-gdeadline')||{}).value||'2026-12-31',progress:0,done:false,subGoals:[]});saveState();closeModal();renderGoals()}
function updateGoalProgress(id){var goal=STATE.goals.find(function(x){return x.id===id});if(!goal)return;var wasDone=goalPct(goal)>=100;goal.progress=Number((document.getElementById('m-gprogress')||{}).value)||0;saveState();closeModal();renderGoals();if(!wasDone&&goalPct(goal)>=100){fireConfetti({count:150,duration:3000});showCelebrationToast('Goal complete: '+goal.name,'🎯')}}
function editGoalSave(id){var goal=STATE.goals.find(function(x){return x.id===id});if(!goal)return;goal.name=(document.getElementById('m-gname')||{}).value||goal.name;goal.deadline=(document.getElementById('m-gdeadline')||{}).value||goal.deadline;goal.desc=(document.getElementById('m-gdesc')||{}).value||'';var cat=(document.getElementById('m-gcat')||{}).value;if(cat){goal.cat=cat;var badges={Finance:'fin',Fitness:'fit',Career:'car',Personal:'per'};goal.badge=badges[cat]||goal.badge}saveState();closeModal();renderGoals()}
function deleteGoal(id){confirmDelete('Delete this goal?',function(){STATE.goals=STATE.goals.filter(function(g){return g.id!==id});saveState();renderGoals()})}
function saveMetric(type){if(!STATE.metrics)STATE.metrics={};var date=(document.getElementById('m-mdate')||{}).value||localDateKey(new Date());var note=(document.getElementById('m-mnote')||{}).value||'';var entry={id:g(),date:date};if(type==='project'){var name=((document.getElementById('m-mname')||{}).value||'').trim();if(!name)return;entry.name=name}else if(type==='run'){var val=(document.getElementById('m-mval')||{}).value;if(!val)return;entry.distance=Number(val);entry.time=(document.getElementById('m-mtime')||{}).value||'';entry.note=note}else if(type==='moneySaved'){var val=(document.getElementById('m-mval')||{}).value;if(!val)return;entry.amount=Number(val);entry.note=note}else{var val=(document.getElementById('m-mval')||{}).value;if(!val)return;entry.value=Number(val);entry.note=note}if(!STATE.metrics[type])STATE.metrics[type]=[];STATE.metrics[type].push(entry);saveState();closeModal();renderMetrics();if(type==='weight')renderMyPlanStats();if(type==='run'){var rrEl=document.getElementById('recent-runs-workout');if(rrEl)renderWorkout()}}


