// FINANCE
// ============================================================
var finCharts={};
function destroyFC(id){if(finCharts[id]){finCharts[id].destroy();delete finCharts[id]}}
function renderFinance(tab){if(tab==='overview')renderFinanceOverview();if(tab==='budget')renderBudget();if(tab==='accounts')renderAccounts();if(tab==='debts')renderDebts();if(tab==='savings')renderSavingsGoals()}
function renderFinanceOverview(){var accounts=STATE.accounts||[];var totalDebt=(STATE.debts||[]).reduce(function(s,d){return s+Number(d.balance)},0);var totalInc=(STATE.income||[]).reduce(function(s,i){return s+Number(i.amount)},0);var totalExp=(STATE.expenses||[]).reduce(function(s,e){return s+Number(e.amount)},0);var left=totalInc-totalExp;var fsEl=document.getElementById('fin-stats');if(fsEl)fsEl.innerHTML='<div class="card" style="border-top:3px solid var(--mint)"><div class="card-label">&#128154; Monthly income</div><div class="stat-big" style="color:var(--mint)">'+fmtMoney(totalInc)+'</div></div><div class="card" style="border-top:3px solid var(--red)"><div class="card-label">&#128308; Monthly expenses</div><div class="stat-big" style="color:var(--red)">'+fmtMoney(totalExp)+'</div></div><div class="card" style="border-top:3px solid '+(left>=0?'var(--accent)':'var(--red)')+'"><div class="card-label">&#10024; Left over</div><div class="stat-big" style="color:'+(left>=0?'var(--accent)':'var(--red)')+'">'+fmtMoney(left)+'</div></div><div class="card" style="border-top:3px solid var(--mauve)"><div class="card-label">&#128179; Total debt</div><div class="stat-big" style="color:var(--mauve)">'+fmtMoney(totalDebt)+'</div></div>';destroyFC('spend');var cats={};var catColors={};(STATE.expenses||[]).forEach(function(e){cats[e.name]=(cats[e.name]||0)+Number(e.amount);catColors[e.name]=e.color||'#f9a8d4'});var spCtx=document.getElementById('spendChart');if(spCtx)finCharts['spend']=new Chart(spCtx,{type:'doughnut',data:{labels:Object.keys(cats),datasets:[{data:Object.values(cats),backgroundColor:Object.keys(cats).map(function(k){return (catColors[k]||'#f9a8d4')+'cc'}),borderColor:Object.keys(cats).map(function(k){return catColors[k]||'#f9a8d4'}),borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'right',labels:{color:'#8a6545',font:{size:11},boxWidth:12,padding:8}}}}});destroyFC('networth');var nwL=[],nwD=[],nwC=[];accounts.forEach(function(a){nwL.push(a.name);nwD.push(Number(a.balance));nwC.push(a.color||'#a0522d')});var nwCtx=document.getElementById('networthChart');if(nwCtx)finCharts['networth']=new Chart(nwCtx,{type:'doughnut',data:{labels:nwL,datasets:[{data:nwD,backgroundColor:nwC.map(function(c){return c+'cc'}),borderColor:nwC,borderWidth:2}]},options:{responsive:true,maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'right',labels:{color:'#8a6545',font:{size:11},boxWidth:12,padding:8}}}}})}
function renderBudget(){var income=STATE.income||[];var totalInc=income.reduce(function(s,i){return s+Number(i.amount)},0);var iEl=document.getElementById('income-list');if(iEl)iEl.innerHTML=income.length?income.map(function(i){return '<div style="display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid var(--border)"><span style="font-size:16px">'+(i.icon||'&#128176;')+'</span><span style="flex:1;font-size:13px;font-weight:500">'+i.name+'</span><span style="font-size:14px;font-weight:600;color:var(--mint)">'+fmtMoney(i.amount)+'</span><button class="btn btn-sm btn-ghost" onclick="openModal(\'editIncome\',\''+i.id+'\')">&#9998;</button><button class="btn btn-sm btn-danger" onclick="deleteIncome(\''+i.id+'\')">&#215;</button></div>'}).join(''):'<div style="text-align:center;padding:20px;color:var(--text3);font-size:13px">No income added yet</div>';var iTotalEl=document.getElementById('income-total');if(iTotalEl)iTotalEl.innerHTML='SUM <strong>'+fmtMoney(totalInc)+'</strong>/month';var expenses=STATE.expenses||[];var totalExp=expenses.reduce(function(s,e){return s+Number(e.amount)},0);var eEl=document.getElementById('expenses-list');if(eEl)eEl.innerHTML=expenses.length?expenses.map(function(e){return '<div style="display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid var(--border)"><span style="font-size:16px">'+(e.icon||'&#128184;')+'</span><div style="flex:1;min-width:0"><div style="font-size:13px;font-weight:500">'+e.name+'</div>'+(e.note?'<div style="font-size:11px;color:var(--text3)">'+e.note+'</div>':'')+'</div><span style="font-size:14px;font-weight:600;color:var(--red)">'+fmtMoney(e.amount)+'</span><button class="btn btn-sm btn-ghost" onclick="openModal(\'editExpense\',\''+e.id+'\')">&#9998;</button><button class="btn btn-sm btn-danger" onclick="deleteExpense(\''+e.id+'\')">&#215;</button></div>'}).join(''):'<div style="text-align:center;padding:20px;color:var(--text3);font-size:13px">No expenses yet</div>';var eTotalEl=document.getElementById('expenses-total');if(eTotalEl)eTotalEl.innerHTML='SUM <strong>'+fmtMoney(totalExp)+'</strong>/month';var left=totalInc-totalExp;var p=totalInc>0?Math.round((totalExp/totalInc)*100):0;var blEl=document.getElementById('budget-leftover');if(blEl)blEl.innerHTML='<div class="card" style="border:2px solid '+(left>=0?'#a7f3d0':'#fecdd3')+';background:'+(left>=0?'#f0fdf4':'#fff1f2')+'"><div style="display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px"><div><div style="font-size:12px;color:var(--text2);margin-bottom:4px">'+(left>=0?'&#10024; Monthly leftover':'&#9888;&#65039; Overspending by')+'</div><div style="font-family:var(--serif);font-size:30px;font-weight:600;color:'+(left>=0?'#059669':'#e11d48')+'">'+fmtMoney(Math.abs(left))+'</div></div></div></div>'}
function renderAccounts(){var accounts=STATE.accounts||[];var savings=accounts.filter(function(a){return a.type==='savings'});var investments=accounts.filter(function(a){return a.type==='investment'});var mkCard=function(a){return '<div class="card" style="margin-bottom:10px;border-left:4px solid '+(a.color||'#a0522d')+'"><div style="display:flex;align-items:center;gap:12px"><span style="font-size:26px">'+(a.icon||'&#127968;')+'</span><div style="flex:1"><div style="font-size:14px;font-weight:600">'+a.name+'</div><div style="font-size:11px;color:var(--text3)">'+(a.institution||'')+(a.note?' &#183; '+a.note:'')+'</div></div><div style="text-align:right"><div style="font-size:20px;font-family:var(--serif);font-weight:600;color:var(--accent)">'+fmtMoney(a.balance)+'</div>'+(a.target?'<div style="font-size:11px;color:var(--text3)">'+Math.min(100,Math.round(a.balance/a.target*100))+'% of goal</div>':'')+'</div><div style="display:flex;flex-direction:column;gap:4px"><button class="btn btn-sm btn-ghost" onclick="openModal(\'editAccount\',\''+a.id+'\')">&#9998;</button><button class="btn btn-sm btn-danger" onclick="deleteAccount(\''+a.id+'\')">&#215;</button></div></div>'+(a.target?'<div class="pbar-wrap" style="margin-top:8px"><div class="pbar" style="width:'+Math.min(100,Math.round(a.balance/a.target*100))+'%;background:'+(a.color||'var(--accent)')+'"></div></div>':'')+'</div>'};var bEl=document.getElementById('bank-accounts-list');if(bEl)bEl.innerHTML=savings.length?savings.map(mkCard).join(''):'<div style="font-size:13px;color:var(--text3);padding:12px 0">No savings accounts yet</div>';var iEl=document.getElementById('investments-list');if(iEl)iEl.innerHTML=investments.length?investments.map(mkCard).join(''):'<div style="font-size:13px;color:var(--text3);padding:12px 0">No investments yet</div>'}
function renderDebts(){var debts=STATE.debts||[];var payments=(STATE.debtPayments||[]).slice().sort(function(a,b){return b.date.localeCompare(a.date)});var totalDebt=debts.reduce(function(s,d){return s+Number(d.balance)},0);var totalPaid=payments.reduce(function(s,p){return s+Number(p.amount)},0);var totalTarget=debts.reduce(function(s,d){return s+Number(d.monthlyTarget||0)},0);var surplus=(STATE.income||[]).reduce(function(s,i){return s+Number(i.amount)},0)-(STATE.expenses||[]).reduce(function(s,e){return s+Number(e.amount)},0);var monthlyPay=totalTarget>0?totalTarget:Math.max(0,surplus);var months=monthlyPay>0?Math.ceil(totalDebt/monthlyPay):0;var freeDate=new Date();freeDate.setMonth(freeDate.getMonth()+months);var freeDateStr=months>0?freeDate.toLocaleDateString('en-GB',{month:'short',year:'numeric'}):'—';var grandTotal=debts.reduce(function(s,d){return s+Number(d.startingBalance||Number(d.balance)+payments.filter(function(p){return p.debtId===d.id}).reduce(function(ss,p){return ss+Number(p.amount)},0))},0);var paidPct=totalDebt<=0&&grandTotal>0?100:(grandTotal>0?Math.round((grandTotal-totalDebt)/grandTotal*100):0);var thisMonth=new Date().toISOString().slice(0,7);var paidThisMonth=payments.filter(function(p){return p.date.startsWith(thisMonth)}).reduce(function(s,p){return s+Number(p.amount)},0);
/* Summary stats */
var ssEl=document.getElementById('debt-summary-stats');if(ssEl){if(debts.length){ssEl.innerHTML='<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(140px,1fr));gap:10px"><div class="card-sm" style="text-align:center;border-top:3px solid var(--red)"><div style="font-size:20px;font-family:var(--serif);font-weight:600;color:var(--red)">'+fmtMoney(totalDebt)+'</div><div style="font-size:10px;color:var(--text3)">total remaining</div></div><div class="card-sm" style="text-align:center;border-top:3px solid var(--mint)"><div style="font-size:20px;font-family:var(--serif);font-weight:600;color:var(--mint)">'+fmtMoney(totalPaid)+'</div><div style="font-size:10px;color:var(--text3)">total paid off ('+paidPct+'%)</div></div><div class="card-sm" style="text-align:center;border-top:3px solid var(--gold)"><div style="font-size:20px;font-family:var(--serif);font-weight:600;color:var(--gold)">'+fmtMoney(paidThisMonth)+'</div><div style="font-size:10px;color:var(--text3)">paid this month</div></div><div class="card-sm" style="text-align:center;border-top:3px solid var(--teal)"><div style="font-size:20px;font-family:var(--serif);font-weight:600;color:var(--teal)">'+freeDateStr+'</div><div style="font-size:10px;color:var(--text3)">debt-free by (~'+months+'mo)</div></div></div><div style="height:8px;background:var(--bg4);border-radius:4px;overflow:hidden;margin-top:12px"><div style="height:100%;width:'+paidPct+'%;background:var(--mint);border-radius:4px;transition:width .4s"></div></div>'}else{ssEl.innerHTML=''}}
/* Debt cards — each card is self-contained with target, progress, recent payments */
var el=document.getElementById('debts-list');if(!el)return;
if(!debts.length){el.innerHTML='<div class="empty"><div class="empty-icon">🎉</div>No debts! Crushing it!</div>';return}
var PC={High:'#fde8ea',Medium:'#fef3c7',Low:'#f0fdf4'};var PT={High:'#e11d48',Medium:'#d97706',Low:'#16a34a'};
el.innerHTML=debts.map(function(d){var dPayments=payments.filter(function(p){return p.debtId===d.id});var dPaid=dPayments.reduce(function(s,p){return s+Number(p.amount)},0);var orig=Number(d.startingBalance)||Number(d.balance)+dPaid;var pct=Number(d.balance)<=0?100:(orig>0?Math.round((orig-Number(d.balance))/orig*100):0);var target=Number(d.monthlyTarget||0);var dPaidMonth=dPayments.filter(function(p){return p.date.startsWith(thisMonth)}).reduce(function(s,p){return s+Number(p.amount)},0);var monthPct=target>0?Math.min(100,Math.round(dPaidMonth/target*100)):0;var mLeft=target>0?Math.ceil(Number(d.balance)/target):0;
var h='<div class="card" style="margin-bottom:12px;border-left:4px solid '+(d.color||'#fb7185')+'">';
/* Header row */
h+='<div style="display:flex;align-items:start;gap:12px;margin-bottom:10px"><div style="flex:1"><div style="display:flex;align-items:center;gap:8px"><div style="font-size:15px;font-weight:600">'+d.name+'</div><span style="padding:2px 8px;border-radius:12px;font-size:10px;font-weight:600;background:'+(PC[d.priority]||'#f0f0f0')+';color:'+(PT[d.priority]||'#666')+'">'+d.priority+'</span></div>'+(d.note?'<div style="font-size:11px;color:var(--text3);margin-top:2px">'+d.note+'</div>':'')+'</div><div style="text-align:right"><div style="font-size:22px;font-family:var(--serif);font-weight:600;color:#e11d48">'+fmtMoney(d.balance)+'</div><div style="font-size:10px;color:var(--text3)">remaining</div></div><div style="display:flex;gap:4px"><button class="btn btn-sm btn-ghost" onclick="openModal(\'editDebt\',\''+d.id+'\')">✏️</button><button class="btn btn-sm btn-danger" onclick="deleteDebt(\''+d.id+'\')">×</button></div></div>';
/* Overall progress */
h+='<div style="display:flex;align-items:center;gap:8px;margin-bottom:10px"><div style="flex:1;height:8px;background:var(--bg4);border-radius:4px;overflow:hidden"><div style="height:100%;width:'+pct+'%;background:var(--mint);border-radius:4px;transition:width .4s"></div></div><span style="font-size:11px;font-weight:600;color:var(--mint);white-space:nowrap">'+pct+'% cleared</span></div>';
/* Monthly target + this month row */
h+='<div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:10px 12px;background:var(--bg3);border-radius:var(--radius-sm)">';
h+='<div style="display:flex;align-items:center;gap:6px"><span style="font-size:11px;color:var(--text2)">Monthly target:</span><input type="number" value="'+(target||'')+'" placeholder="£" onchange="setDebtMonthlyTarget(\''+d.id+'\',this.value)" style="width:70px;padding:4px 8px;background:var(--bg2);border:1.5px solid var(--border2);border-radius:6px;color:var(--text);font-family:var(--sans);font-size:12px;outline:none"></div>';
if(target>0){h+='<div style="flex:1;min-width:120px"><div style="display:flex;justify-content:space-between;font-size:10px;color:var(--text3);margin-bottom:3px"><span>This month</span><span>'+fmtMoney(dPaidMonth)+' / '+fmtMoney(target)+'</span></div><div style="height:5px;background:var(--bg4);border-radius:3px;overflow:hidden"><div style="height:100%;width:'+monthPct+'%;background:'+(monthPct>=100?'var(--mint)':'var(--gold)')+';border-radius:3px"></div></div></div>';
h+='<span style="font-size:10px;color:var(--text3);white-space:nowrap">~'+mLeft+' months left</span>'}
h+='</div>';
/* Recent payments for this debt */
if(dPayments.length){h+='<div style="margin-top:10px"><div style="font-size:10px;color:var(--text3);text-transform:uppercase;letter-spacing:.05em;margin-bottom:4px">Recent payments</div>';
h+=dPayments.slice(0,3).map(function(p){return '<div style="display:flex;align-items:center;gap:8px;padding:4px 0;font-size:11px"><span style="color:var(--text3)">'+fmtDate(p.date)+'</span><span style="flex:1;color:var(--text2)">'+(p.note||'')+'</span><span style="font-weight:600;color:var(--mint)">-'+fmtMoney(p.amount)+'</span><button style="background:none;border:none;color:var(--red);cursor:pointer;font-size:12px;padding:0 2px" onclick="deleteDebtPayment(\''+p.id+'\')">×</button></div>'}).join('');
if(dPayments.length>3)h+='<div style="font-size:10px;color:var(--text3);padding-top:2px">+ '+(dPayments.length-3)+' more</div>';
h+='</div>'}
h+='</div>';return h}).join('');
renderDebtPlan()}
function renderDebtPlan(){
  var el=document.getElementById('debt-plan-panel');if(!el)return;
  var debts=(STATE.debts||[]).filter(function(d){return Number(d.balance)>0});
  if(!debts.length){el.innerHTML='';return}
  var thisMonth=new Date().toISOString().slice(0,7);
  var planned=(STATE.plannedPayments||[]).filter(function(p){return p.month===thisMonth});
  var plannedTotal=planned.reduce(function(s,p){return s+Number(p.amount)},0);
  var paidTotal=planned.filter(function(p){return p.paid}).reduce(function(s,p){return s+Number(p.amount)},0);
  var h='<div class="card">';
  h+='<div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:14px">';
  h+='<div><div style="font-size:15px;font-weight:600">📋 '+new Date().toLocaleDateString('en-GB',{month:'long',year:'numeric'})+'</div>';
  h+='<div style="font-size:11px;color:var(--text2)">Payment plan</div></div>';
  h+='<button class="btn btn-sm btn-accent" onclick="openModal(\'addPlannedPayment\')">+ Add</button></div>';
  if(planned.length){
    h+='<div style="display:flex;gap:12px;margin-bottom:12px">';
    h+='<div style="flex:1;text-align:center"><div style="font-family:var(--serif);font-size:20px;font-weight:600;color:var(--accent)">'+fmtMoney(plannedTotal)+'</div><div style="font-size:10px;color:var(--text3)">planned</div></div>';
    h+='<div style="flex:1;text-align:center"><div style="font-family:var(--serif);font-size:20px;font-weight:600;color:var(--mint)">'+fmtMoney(paidTotal)+'</div><div style="font-size:10px;color:var(--text3)">paid</div></div>';
    h+='<div style="flex:1;text-align:center"><div style="font-family:var(--serif);font-size:20px;font-weight:600;color:'+(plannedTotal-paidTotal>0?'var(--red)':'var(--mint)')+'">'+fmtMoney(Math.max(0,plannedTotal-paidTotal))+'</div><div style="font-size:10px;color:var(--text3)">left</div></div></div>';
    var pct=Math.round(paidTotal/plannedTotal*100);
    h+='<div style="height:6px;background:var(--bg4);border-radius:3px;overflow:hidden;margin-bottom:14px"><div style="height:100%;width:'+pct+'%;background:'+(pct>=100?'var(--mint)':'var(--accent)')+';border-radius:3px;transition:width .4s"></div></div>';
    planned.sort(function(a,b){return (a.paid?1:0)-(b.paid?1:0)||(a.date||'').localeCompare(b.date||'')});
    planned.forEach(function(pp){
      var debt=debts.find(function(d){return d.id===pp.debtId})||{name:'?',color:'#999'};
      h+='<div style="display:flex;align-items:center;gap:8px;padding:9px 0;border-bottom:1px solid var(--border)'+(pp.paid?';opacity:0.5':'')+'">';
      h+='<div onclick="togglePlannedPayment(\''+pp.id+'\')" style="width:20px;height:20px;border-radius:5px;border:2px solid '+(pp.paid?'var(--mint)':'var(--border2)')+';background:'+(pp.paid?'var(--mint)':'var(--bg2)')+';cursor:pointer;display:flex;align-items:center;justify-content:center;flex-shrink:0">'+(pp.paid?'<span style="color:#fff;font-size:11px;font-weight:700">✓</span>':'')+'</div>';
      h+='<div style="width:6px;height:20px;border-radius:3px;background:'+(debt.color||'#fb7185')+';flex-shrink:0"></div>';
      h+='<div style="flex:1;min-width:0"><div style="font-size:13px;font-weight:500'+(pp.paid?';text-decoration:line-through;color:var(--text3)':'')+'">'+fmtMoney(pp.amount)+' → '+debt.name+'</div>';
      if(pp.date||pp.note)h+='<div style="font-size:11px;color:var(--text3);overflow:hidden;text-overflow:ellipsis;white-space:nowrap">'+(pp.date?fmtDate(pp.date):'')+(pp.date&&pp.note?' · ':'')+(pp.note||'')+'</div>';
      h+='</div>';
      h+='<button style="background:none;border:none;color:var(--red);cursor:pointer;font-size:14px;padding:0 4px" onclick="deletePlannedPayment(\''+pp.id+'\')">×</button>';
      h+='</div>';
    });
  } else {
    h+='<div style="text-align:center;padding:24px 0;color:var(--text3)"><div style="font-size:28px;margin-bottom:8px">📝</div><div style="font-size:13px">Plan your payments for this month</div></div>';
  }
  h+='</div>';
  el.innerHTML=h;
}
function renderDebtPayoffPlanner(){renderDebtPlan()}
function renderDebtPaymentHistory(){}
function togglePlannedPayment(id){var pp=(STATE.plannedPayments||[]).find(function(p){return p.id===id});if(!pp)return;pp.paid=!pp.paid;if(pp.paid&&!pp.wasPaid){pp.wasPaid=true;var debt=(STATE.debts||[]).find(function(d){return d.id===pp.debtId});if(debt){debt.balance=Math.max(0,Number(debt.balance)-Number(pp.amount));if(!STATE.debtPayments)STATE.debtPayments=[];STATE.debtPayments.push({id:g(),debtId:pp.debtId,amount:Number(pp.amount),date:localDateKey(new Date()),note:'Planned: '+(pp.note||'')})}}else if(!pp.paid&&pp.wasPaid){pp.wasPaid=false;var debt2=(STATE.debts||[]).find(function(d){return d.id===pp.debtId});if(debt2)debt2.balance=Number(debt2.balance)+Number(pp.amount);STATE.debtPayments=(STATE.debtPayments||[]).filter(function(p){return !(p.debtId===pp.debtId&&p.note&&p.note.startsWith('Planned:')&&Number(p.amount)===Number(pp.amount))})}saveState();renderDebts();refreshRoadmapLiveCards()}
function deletePlannedPayment(id){confirmDelete('Remove this planned payment?',function(){STATE.plannedPayments=(STATE.plannedPayments||[]).filter(function(p){return p.id!==id});saveState();renderDebts()})}
function savePlannedPayment(){var debtId=(document.getElementById('m-ppdebt')||{}).value;var amount=Number((document.getElementById('m-ppamount')||{}).value)||0;if(!debtId||!amount)return;var date=(document.getElementById('m-ppdate')||{}).value||'';var note=(document.getElementById('m-ppnote')||{}).value||'';var month=new Date().toISOString().slice(0,7);if(date)month=date.slice(0,7);if(!STATE.plannedPayments)STATE.plannedPayments=[];STATE.plannedPayments.push({id:g(),debtId:debtId,amount:amount,date:date,note:note,month:month,paid:false});saveState();closeModal();renderDebts()}
function renderSavingsGoals(){var goals=STATE.savingsGoals||[];var PC={High:'#fde8ea',Medium:'#fef3c7',Low:'#f0fdf4'};var PT={High:'#e11d48',Medium:'#d97706',Low:'#16a34a'};var el=document.getElementById('savings-goals-list');if(el)el.innerHTML=goals.length?'<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:16px">'+goals.map(function(sg){var p=sg.target>0?Math.min(100,Math.round(Number(sg.current||0)/Number(sg.target)*100)):0;var col=sg.color||'var(--accent)';var remaining=Math.max(0,sg.target-(sg.current||0));return '<div class="card" style="text-align:center;padding:24px 20px"><div style="display:flex;justify-content:flex-end;gap:4px;margin-bottom:8px"><button class="btn btn-sm btn-ghost" onclick="openModal(\'editSavingsGoal\',\''+sg.id+'\')">&#9998;</button><button class="btn btn-sm btn-danger" onclick="deleteSavingsGoal(\''+sg.id+'\')">&#215;</button></div><div class="thermo"><div class="thermo-tube"><div class="thermo-fill" style="height:'+p+'%;background:linear-gradient(to top,'+col+','+col+'cc)"></div></div><div class="thermo-bulb" style="background:'+col+';border-color:'+col+'"><span style="color:#fff">'+(sg.icon||'&#127919;')+'</span></div><div class="thermo-marks"><span class="thermo-mark">'+fmtMoney(sg.target)+'</span><span class="thermo-mark">'+fmtMoney(Math.round(sg.target*0.75))+'</span><span class="thermo-mark">'+fmtMoney(Math.round(sg.target*0.5))+'</span><span class="thermo-mark">'+fmtMoney(Math.round(sg.target*0.25))+'</span><span class="thermo-mark">£0</span></div></div><div class="thermo-pct" style="color:'+col+'">'+p+'%</div><div style="font-family:var(--serif);font-size:16px;font-weight:600;margin-top:8px">'+sg.name+'</div><div style="font-size:13px;color:var(--accent);font-weight:600;margin-top:4px">'+fmtMoney(sg.current||0)+' <span style="font-weight:400;color:var(--text3)">of '+fmtMoney(sg.target)+'</span></div>'+(sg.note?'<div style="font-size:11px;color:var(--text2);margin-top:4px">'+sg.note+'</div>':'')+(sg.deadline?'<div style="font-size:11px;color:var(--text3);margin-top:3px">&#128467; By '+fmtDate(sg.deadline)+'</div>':'')+'<div style="margin-top:6px"><span style="padding:3px 10px;border-radius:20px;font-size:10px;font-weight:600;background:'+(PC[sg.priority]||'#f0f0f0')+';color:'+(PT[sg.priority]||'#666')+'">'+sg.priority+'</span></div><div style="font-size:11px;color:var(--text3);margin-top:6px">'+fmtMoney(remaining)+' to go</div></div>'}).join('')+'</div>':'<div class="empty"><div class="empty-icon">&#127800;</div>No savings goals yet. Add one!</div>'}
function deleteAccount(id){confirmDelete('Remove?',function(){STATE.accounts=(STATE.accounts||[]).filter(function(a){return a.id!==id});saveState();renderAccounts()})}
function deleteDebt(id){confirmDelete('Remove?',function(){STATE.debts=(STATE.debts||[]).filter(function(d){return d.id!==id});saveState();renderDebts();refreshRoadmapLiveCards()})}
function deleteSavingsGoal(id){confirmDelete('Remove?',function(){STATE.savingsGoals=(STATE.savingsGoals||[]).filter(function(g){return g.id!==id});saveState();renderSavingsGoals()})}
function deleteIncome(id){STATE.income=(STATE.income||[]).filter(function(i){return i.id!==id});saveState();renderBudget()}
function deleteExpense(id){STATE.expenses=(STATE.expenses||[]).filter(function(e){return e.id!==id});saveState();renderBudget()}
function saveIncome(){var name=((document.getElementById('m-iname')||{}).value||'').trim();if(!name)return;if(!STATE.income)STATE.income=[];STATE.income.push({id:g(),name:name,amount:Number((document.getElementById('m-iamount')||{}).value)||0,icon:(document.getElementById('m-iicon')||{}).value||'&#128188;',note:(document.getElementById('m-inote')||{}).value||''});saveState();closeModal();renderBudget();refreshRoadmapLiveCards()}
function updateIncome(id){var i=(STATE.income||[]).find(function(x){return x.id===id});if(!i)return;i.name=(document.getElementById('m-iname')||{}).value||i.name;i.amount=Number((document.getElementById('m-iamount')||{}).value)||i.amount;i.icon=(document.getElementById('m-iicon')||{}).value||i.icon;i.note=(document.getElementById('m-inote')||{}).value||'';saveState();closeModal();renderBudget();refreshRoadmapLiveCards()}
function saveAccount(){var name=((document.getElementById('m-aname')||{}).value||'').trim();if(!name)return;var type=(document.getElementById('m-atype')||{}).value||'savings';if(!STATE.accounts)STATE.accounts=[];var acc={id:g(),name:name,type:type,balance:Number((document.getElementById('m-abalance')||{}).value)||0,color:type==='savings'?'#a0522d':'#c9973a',icon:(document.getElementById('m-aicon')||{}).value||(type==='savings'?'&#128176;':'&#128200;'),institution:(document.getElementById('m-ainst')||{}).value||''};var rate=(document.getElementById('m-arate')||{}).value;if(rate)acc.rate=Number(rate);var target=(document.getElementById('m-atarget')||{}).value;if(target)acc.target=Number(target);STATE.accounts.push(acc);saveState();closeModal();renderAccounts();refreshRoadmapLiveCards()}
function updateAccount(id){var a=(STATE.accounts||[]).find(function(x){return x.id===id});if(!a)return;a.name=(document.getElementById('m-aname')||{}).value||a.name;a.balance=Number((document.getElementById('m-abalance')||{}).value)||a.balance;a.icon=(document.getElementById('m-aicon')||{}).value||a.icon;a.institution=(document.getElementById('m-ainst')||{}).value||a.institution||'';var rate=document.getElementById('m-arate');if(rate&&rate.value)a.rate=Number(rate.value);var target=document.getElementById('m-atarget');if(target&&target.value)a.target=Number(target.value);saveState();closeModal();renderAccounts();refreshRoadmapLiveCards()}
function saveExpense(){var name=((document.getElementById('m-ename')||{}).value||'').trim();if(!name)return;var palette=['#f9a8d4','#c084fc','#fb923c','#818cf8','#34d399','#f59e0b','#a0522d','#2dd4bf','#fb7185'];STATE.expenses=STATE.expenses||[];STATE.expenses.push({id:g(),name:name,amount:Number((document.getElementById('m-eamount')||{}).value)||0,icon:(document.getElementById('m-eicon')||{}).value||'&#128184;',note:(document.getElementById('m-enote')||{}).value||'',color:palette[STATE.expenses.length%palette.length]});saveState();closeModal();renderBudget()}
function updateExpense(id){var e=(STATE.expenses||[]).find(function(x){return x.id===id});if(!e)return;e.name=(document.getElementById('m-ename')||{}).value||e.name;e.amount=Number((document.getElementById('m-eamount')||{}).value)||0;e.icon=(document.getElementById('m-eicon')||{}).value||e.icon;e.note=(document.getElementById('m-enote')||{}).value||'';saveState();closeModal();renderBudget()}
function saveDebt(){var name=((document.getElementById('m-dname')||{}).value||'').trim();if(!name)return;var priority=(document.getElementById('m-dpriority')||{}).value||'Medium';var pColors={High:'#f43f5e',Medium:'#fb7185',Low:'#fda4af'};var bal=Number((document.getElementById('m-dbalance')||{}).value)||0;if(!STATE.debts)STATE.debts=[];STATE.debts.push({id:g(),name:name,balance:bal,startingBalance:bal,priority:priority,color:pColors[priority],due:(document.getElementById('m-ddue')||{}).value||'',note:(document.getElementById('m-dnote')||{}).value||''});saveState();closeModal();renderDebts();refreshRoadmapLiveCards()}
function updateDebt(id){var d=(STATE.debts||[]).find(function(x){return x.id===id});if(!d)return;d.name=(document.getElementById('m-dname')||{}).value||d.name;d.balance=Number((document.getElementById('m-dbalance')||{}).value)||0;d.priority=(document.getElementById('m-dpriority')||{}).value||d.priority;d.note=(document.getElementById('m-dnote')||{}).value||'';d.due=(document.getElementById('m-ddue')||{}).value||'';var pColors={High:'#f43f5e',Medium:'#fb7185',Low:'#fda4af'};d.color=pColors[d.priority]||d.color;saveState();closeModal();renderDebts();refreshRoadmapLiveCards()}
function saveSavingsGoal(){var name=((document.getElementById('m-sgname')||{}).value||'').trim();if(!name)return;var colors=['#a0522d','#c9973a','#34d399','#f59e0b','#818cf8','#fb923c'];if(!STATE.savingsGoals)STATE.savingsGoals=[];STATE.savingsGoals.push({id:g(),name:name,target:Number((document.getElementById('m-sgtarget')||{}).value)||0,current:Number((document.getElementById('m-sgcurrent')||{}).value)||0,priority:(document.getElementById('m-sgpriority')||{}).value||'Medium',icon:(document.getElementById('m-sgicon')||{}).value||'&#127919;',deadline:(document.getElementById('m-sgdeadline')||{}).value||'',note:(document.getElementById('m-sgnote')||{}).value||'',color:colors[STATE.savingsGoals.length%colors.length]});saveState();closeModal();renderSavingsGoals();refreshRoadmapLiveCards()}
function updateSavingsGoal(id){var sg=(STATE.savingsGoals||[]).find(function(x){return x.id===id});if(!sg)return;sg.name=(document.getElementById('m-sgname')||{}).value||sg.name;sg.target=Number((document.getElementById('m-sgtarget')||{}).value)||sg.target;sg.current=Number((document.getElementById('m-sgcurrent')||{}).value)||0;sg.priority=(document.getElementById('m-sgpriority')||{}).value||sg.priority;sg.icon=(document.getElementById('m-sgicon')||{}).value||sg.icon;sg.deadline=(document.getElementById('m-sgdeadline')||{}).value||'';sg.note=(document.getElementById('m-sgnote')||{}).value||'';saveState();closeModal();renderSavingsGoals();refreshRoadmapLiveCards()}

