// GRATITUDE
// ============================================================
function renderGratitude(){var entries=(STATE.gratitude||[]).slice().sort(function(a,b){return b.date.localeCompare(a.date)});var thisWeekStart=weekKey(new Date());var thisWeek=entries.filter(function(e){return e.date>=thisWeekStart});var streak=0;var checkDate=new Date();for(var i=0;i<365;i++){var k=localDateKey(checkDate);if(entries.some(function(e){return e.date===k}))streak++;else if(i>0)break;checkDate.setDate(checkDate.getDate()-1)}var gwEl=document.getElementById('gratitude-wins');if(gwEl)gwEl.innerHTML=thisWeek.length?thisWeek.map(function(e){return '<div style="padding:9px 0;border-bottom:1px solid var(--border)"><div style="font-size:11px;color:var(--text3);margin-bottom:3px">'+fmtDate(e.date)+'</div>'+(e.wins?'<div style="font-size:13px;font-weight:500;margin-bottom:3px;color:var(--accent)">&#127942; '+e.wins+'</div>':'')+(e.gratitude?'<div style="font-size:12px;color:var(--text2)">'+e.gratitude.split('\n').filter(function(l){return l.trim()}).map(function(l){return '&#128591; '+l.replace(/^\d+.\s*/,'')}).join(' &#183; ')+'</div>':'')+'</div>'}).join(''):'<div style="font-size:13px;color:var(--text3);padding:12px 0;text-align:center">No entries this week yet</div>';var gsEl=document.getElementById('gratitude-stats');if(gsEl)gsEl.innerHTML='<div style="text-align:center;padding:16px 0"><div style="font-size:44px;font-family:var(--serif);font-weight:600;color:var(--gold)">'+streak+'</div><div style="font-size:13px;color:var(--text2);margin-top:3px">day gratitude streak</div><div style="font-size:12px;color:var(--text3);margin-top:6px">'+entries.length+' total entries</div></div>';var gaEl=document.getElementById('gratitude-all');if(gaEl)gaEl.innerHTML=entries.length?entries.slice(0,20).map(function(e){return '<div style="padding:11px 0;border-bottom:1px solid var(--border)"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:5px"><span style="font-size:12px;font-weight:600">'+fmtDate(e.date)+'</span><button class="btn btn-sm btn-danger" onclick="confirmDelete(\'Delete?\',function(){deleteGratitudeEntry(\''+e.id+'\')})">&#215;</button></div>'+(e.wins?'<div style="font-size:12px;font-weight:500;margin-bottom:3px;color:var(--accent)">&#127942; '+e.wins+'</div>':'')+(e.gratitude?'<div style="font-size:12px;color:var(--text2)">'+e.gratitude.split('\n').filter(function(l){return l.trim()}).map(function(l){return '&#128591; '+l.replace(/^\d+.\s*/,'')}).join('<br>')+'</div>':'')+'</div>'}).join(''):'<div class="empty"><div class="empty-icon">&#128591;</div>No entries yet.</div>'}
function deleteGratitudeEntry(id){STATE.gratitude=(STATE.gratitude||[]).filter(function(e){return e.id!==id});saveState();renderGratitude()}
function saveGratitudeEntry(){var date=(document.getElementById('m-gdate')||{}).value||localDateKey(new Date());var wins=(document.getElementById('m-gwins')||{}).value||'';var gratitude=(document.getElementById('m-ggratitude')||{}).value||'';if(!wins&&!gratitude)return;if(!STATE.gratitude)STATE.gratitude=[];STATE.gratitude.push({id:g(),date:date,wins:wins,gratitude:gratitude});saveState();closeModal();renderGratitude();if(document.getElementById('page-dashboard').classList.contains('active'))renderDashboard()}

// ============================================================
// DAILY HIGHLIGHT & CLOCK
// ============================================================
function saveDailyHighlight(){var today=localDateKey(new Date());var val=(document.getElementById('daily-highlight')||{}).value||'';if(!STATE.dailyHighlights)STATE.dailyHighlights={};STATE.dailyHighlights[today]=val;saveState();var btn=event.target;var orig=btn.textContent;btn.textContent='Saved!';setTimeout(function(){btn.textContent=orig},1500)}
function loadDailyHighlight(){var today=localDateKey(new Date());var el=document.getElementById('daily-highlight');if(el)el.value=(STATE.dailyHighlights||{})[today]||''}
function startClock(){function tick(){var now=new Date();var timeStr=now.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});var dateStr=now.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});var sdEl=document.getElementById('sidebar-date');if(sdEl)sdEl.textContent=timeStr+' · '+dateStr;var mdEl=document.getElementById('mobile-date');if(mdEl)mdEl.textContent=timeStr}tick();setInterval(tick,1000)}

// ============================================================
// MOOD
// ============================================================
function renderDashMoodCheckin(){var el=document.getElementById('dash-mood-checkin');if(!el)return;var today=localDateKey(new Date());var m=(STATE.mood||{})[today]||{};var moodEm=['','&#128542;','&#128528;','&#128578;','&#128522;','&#129321;'];var energyEm=['','&#129803;','&#128564;','&#9889;','&#128293;','&#128640;'];var moodLabels=['','Low','Meh','Okay','Good','Amazing'];var energyLabels=['','Drained','Tired','Okay','Energised','Buzzing'];if(m.mood){el.innerHTML='<div style="display:flex;align-items:center;gap:14px;flex-wrap:wrap"><div style="text-align:center"><div style="font-size:32px">'+( moodEm[m.mood]||'&#8212;')+'</div><div style="font-size:11px;color:var(--text2);margin-top:1px">'+(moodLabels[m.mood]||'')+'</div><div style="font-size:10px;color:var(--text3)">Mood</div></div><div style="text-align:center"><div style="font-size:32px">'+(energyEm[m.energy]||'&#8212;')+'</div><div style="font-size:11px;color:var(--text2);margin-top:1px">'+(energyLabels[m.energy]||'')+'</div><div style="font-size:10px;color:var(--text3)">Energy</div></div>'+(m.sleep?'<div style="text-align:center"><div style="font-size:22px;font-family:var(--serif);font-weight:600;color:var(--accent)">'+m.sleep+'h</div><div style="font-size:10px;color:var(--text3)">Sleep</div></div>':'')+'<div style="flex:1;text-align:right"><button class="btn btn-sm btn-ghost" onclick="openModal(\'logMood\',\''+today+'\')">Edit</button></div></div>'}else{el.innerHTML='<div style="font-size:13px;color:var(--text2);margin-bottom:10px">How are you feeling today?</div><div style="display:flex;gap:7px;align-items:center;flex-wrap:wrap"><div style="display:flex;gap:5px">'+['&#128542;','&#128528;','&#128578;','&#128522;','&#129321;'].map(function(e,i){return '<button onclick="quickLogMood('+(i+1)+',\''+today+'\')" style="font-size:22px;background:var(--bg3);border:1.5px solid var(--border2);border-radius:10px;padding:5px 7px;cursor:pointer">'+e+'</button>'}).join('')+'</div><button class="btn btn-sm" onclick="openModal(\'logMood\',\''+today+'\')" style="margin-left:auto">Full check-in</button></div>'}}
function quickLogMood(moodVal,date){if(!STATE.mood)STATE.mood={};if(!STATE.mood[date])STATE.mood[date]={};STATE.mood[date].mood=moodVal;saveState();renderDashMoodCheckin()}

function renderDashWater(){var el=document.getElementById('dash-water-tracker');if(!el)return;var today=localDateKey(new Date());if(!STATE.water)STATE.water={};var glasses=STATE.water[today]||0;var target=8;var pct=Math.min(100,Math.round(glasses/target*100));var col=pct>=100?'var(--mint)':pct>=50?'var(--teal)':'var(--text3)';el.innerHTML='<div style="text-align:center;padding:8px 0"><div style="display:flex;justify-content:center;gap:4px;margin-bottom:10px;flex-wrap:wrap">'+Array.from({length:target},function(_,i){var filled=i<glasses;return '<div onclick="logWaterGlass('+(i+1)+')" style="width:28px;height:36px;border-radius:4px 4px 6px 6px;border:1.5px solid '+(filled?'var(--teal)':'var(--border2)')+';background:'+(filled?'rgba(95,158,160,0.25)':'var(--bg3)')+';cursor:pointer;display:flex;align-items:flex-end;justify-content:center;transition:all .15s"><div style="width:100%;height:'+(filled?'100':'0')+'%;background:var(--teal);border-radius:0 0 4px 4px;transition:height .2s"></div></div>'}).join('')+'</div><div style="font-family:var(--serif);font-size:28px;font-weight:600;color:'+col+'">'+glasses+'<span style="font-size:14px;color:var(--text3);font-family:var(--sans)"> / '+target+'</span></div><div style="font-size:11px;color:var(--text3);margin-top:2px">glasses (~250ml each)</div><div style="height:6px;background:var(--bg4);border-radius:3px;margin-top:10px;overflow:hidden"><div style="height:100%;width:'+pct+'%;background:'+col+';border-radius:3px;transition:width .3s"></div></div>'+(glasses>0?'<button class="btn btn-ghost btn-sm" onclick="logWaterGlass('+(glasses-1)+')" style="margin-top:8px;font-size:10px">Undo last</button>':'')+'</div>'}
function logWaterGlass(count){var today=localDateKey(new Date());if(!STATE.water)STATE.water={};STATE.water[today]=Math.max(0,count);saveState();renderDashWater()}

