// HABITS
// ============================================================
function renderHabits(){var days=weekDays(activeWeek);var todayKey=localDateKey(new Date());var dl=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];var dhEl=document.getElementById('day-headers');if(dhEl)dhEl.innerHTML=days.map(function(d,i){return '<div style="width:28px;text-align:center"><div style="font-size:10px;color:var(--text3)">'+dl[i]+'</div><div style="font-size:11px;color:'+(d===todayKey?'var(--accent)':'var(--text3)')+'">'+new Date(d).getDate()+'</div></div>'}).join('');var wkStart=new Date(activeWeek);var wkEnd=new Date(activeWeek);wkEnd.setDate(wkEnd.getDate()+6);var wlEl=document.getElementById('habit-week-label');if(wlEl)wlEl.textContent=fmtDate(wkStart.toISOString())+' \u2013 '+fmtDate(wkEnd.toISOString());var hgEl=document.getElementById('habits-grid');if(hgEl)hgEl.innerHTML=STATE.habits.map(function(h){return '<div class="habit-row"><div style="width:170px;flex-shrink:0;display:flex;align-items:center;gap:4px"><div style="flex:1;min-width:0"><div class="habit-name">'+h.name+'</div><div class="habit-freq">'+h.freq+'</div></div><button style="border:none;background:none;padding:2px;font-size:11px;color:var(--text3);cursor:pointer;flex-shrink:0" onclick="openModal(\'editHabit\',\''+h.id+'\')" title="Edit">\u270F\uFE0F</button></div><div class="habit-dots" style="flex:1">'+days.map(function(d){var done=h.logs[d];var isT=d===todayKey;return '<div class="dot '+(done?'done':'')+(isT&&!done?' today':'')+'" onclick="toggleHabit(\''+h.id+'\',\''+d+'\')">'+( done?'&#10003;':'')+'</div>'}).join('')+'</div><div class="streak-badge">'+(habitStreak(h)>0?'&#128293;'+habitStreak(h):'')+'</div></div>'}).join('');var soEl=document.getElementById('streak-overview');if(soEl)soEl.innerHTML=STATE.habits.map(function(h){var s=habitStreak(h);var wp=habitWeekPct(h,weekKey(new Date()));return '<div style="display:flex;align-items:center;gap:12px;padding:9px 0;border-bottom:1px solid var(--border)"><span style="flex:1;font-size:13px">'+h.name+'</span><span class="badge badge-'+h.badge+'">'+h.freq+'</span><span style="font-size:13px;color:'+(s>=7?'var(--accent)':s>=3?'var(--amber)':'var(--text2)')+'">'+( s>0?'&#128293; '+s+' day streak':'No streak')+'</span><div class="pbar-wrap" style="width:60px;margin:0"><div class="pbar" style="width:'+wp+'%;background:'+pbarColor(wp)+'"></div></div><span style="font-size:12px;color:var(--text2);min-width:36px;text-align:right">'+wp+'%</span><button class="btn btn-sm btn-danger" onclick="deleteHabit(\''+h.id+'\')">&#215;</button></div>'}).join('')}
function toggleHabit(hid,day){var h=STATE.habits.find(function(x){return x.id===hid});if(!h)return;var wasDone=h.logs[day];h.logs[day]=!h.logs[day];saveState();renderHabits();if(!wasDone&&h.logs[day]){var s=habitStreak(h);if(s===7){fireConfetti();showCelebrationToast(h.name+' — 7 day streak!','🔥')}else if(s===14){fireConfetti({count:120});showCelebrationToast(h.name+' — 2 week streak!','⚡')}else if(s===21){fireConfetti({count:140});showCelebrationToast(h.name+' — 21 days! Habit formed!','💪')}else if(s===30){fireConfetti({count:180,duration:3500});showCelebrationToast(h.name+' — 30 day streak! Unstoppable!','🏆')}}}
function changeWeek(dir){var parts=activeWeek.split('-');var d=new Date(+parts[0],+parts[1]-1,+parts[2]);d.setDate(d.getDate()+dir*7);activeWeek=localDateKey(d);renderHabits()}
function deleteHabit(id){confirmDelete('Delete this habit?',function(){STATE.habits=STATE.habits.filter(function(h){return h.id!==id});saveState();renderHabits()})}
function saveHabit(){var name=((document.getElementById('m-hname')||{}).value||'').trim();if(!name)return;STATE.habits.push({id:g(),name:name,freq:(document.getElementById('m-hfreq')||{}).value||'daily',badge:(document.getElementById('m-hbadge')||{}).value||'per',logs:{}});saveState();closeModal();renderHabits()}
function updateHabit(id){var h=STATE.habits.find(function(x){return x.id===id});if(!h)return;h.name=((document.getElementById('m-hname')||{}).value||'').trim()||h.name;h.freq=(document.getElementById('m-hfreq')||{}).value||h.freq;h.badge=(document.getElementById('m-hbadge')||{}).value||h.badge;saveState();closeModal();renderHabits()}

