// MODALS
// ============================================================
var journalMoodVals={mood:0,energy:0};
function openModal(type){var args=Array.prototype.slice.call(arguments,1);var mc=document.getElementById('modal-content');var modals={
  addGoal:function(){return '<h2>&#127919; Add goal</h2><div class="modal-sub">High-level annual goal &#8212; monthly steps go in the Roadmap tab</div><div class="field"><label>Goal name</label><input id="m-gname" placeholder="e.g. Land &#163;50k+ data role"></div><div class="field-row"><div class="field"><label>Category</label><select id="m-gcat"><option>Finance</option><option>Fitness</option><option>Career</option><option>Personal</option></select></div><div class="field"><label>Deadline</label><input id="m-gdeadline" type="date"></div></div><div class="field"><label>Description</label><textarea id="m-gdesc" placeholder="Why this matters..."></textarea></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveGoal()">Add goal &#10003;</button></div>'},
  editGoal:function(id){var goal=STATE.goals.find(function(g){return g.id===id});if(!goal)return '';return '<h2>&#9998;&#65039; Edit goal</h2><div class="field"><label>Name</label><input id="m-gname" value="'+goal.name.replace(/"/g,'&quot;')+'"></div><div class="field-row"><div class="field"><label>Category</label><select id="m-gcat"><option'+(goal.cat==='Finance'?' selected':'')+'>Finance</option><option'+(goal.cat==='Fitness'?' selected':'')+'>Fitness</option><option'+(goal.cat==='Career'?' selected':'')+'>Career</option><option'+(goal.cat==='Personal'?' selected':'')+'>Personal</option></select></div><div class="field"><label>Deadline</label><input id="m-gdeadline" type="date" value="'+(goal.deadline||'')+'"></div></div><div class="field"><label>Description</label><textarea id="m-gdesc">'+(goal.desc||'')+'</textarea></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="editGoalSave(\''+id+'\')">Save &#10003;</button></div>'},
  addHabit:function(){return '<h2>&#10003;&#65039; Add habit</h2><div class="field"><label>Habit name</label><input id="m-hname" placeholder="e.g. 8k steps, drink water"></div><div class="field-row"><div class="field"><label>Frequency</label><select id="m-hfreq"><option>daily</option><option>3x/week</option><option>weekly</option><option>bi-monthly</option><option>monthly</option></select></div><div class="field"><label>Category</label><select id="m-hbadge"><option value="fit">Fitness</option><option value="fin">Finance</option><option value="car">Career</option><option value="per">Personal</option></select></div></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveHabit()">Add &#10003;</button></div>'},
  editHabit:function(id){var h=(STATE.habits||[]).find(function(x){return x.id===id});if(!h)return '';return '<h2>&#9998;&#65039; Edit habit</h2><div class="field"><label>Habit name</label><input id="m-hname" value="'+h.name.replace(/"/g,'&quot;')+'"></div><div class="field-row"><div class="field"><label>Frequency</label><select id="m-hfreq"><option'+(h.freq==='daily'?' selected':'')+'>daily</option><option'+(h.freq==='3x/week'?' selected':'')+'>3x/week</option><option'+(h.freq==='weekly'?' selected':'')+'>weekly</option><option'+(h.freq==='bi-monthly'?' selected':'')+'>bi-monthly</option><option'+(h.freq==='monthly'?' selected':'')+'>monthly</option></select></div><div class="field"><label>Category</label><select id="m-hbadge"><option value="fit"'+(h.badge==='fit'?' selected':'')+'>Fitness</option><option value="fin"'+(h.badge==='fin'?' selected':'')+'>Finance</option><option value="car"'+(h.badge==='car'?' selected':'')+'>Career</option><option value="per"'+(h.badge==='per'?' selected':'')+'>Personal</option></select></div></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-danger" onclick="deleteHabit(\''+id+'\')">Delete</button><button class="btn btn-accent" onclick="updateHabit(\''+id+'\')">Save &#10003;</button></div>'},
  addIncome:function(){return '<h2>&#128154; Add income</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-iname" placeholder="e.g. Amazon Salary"></div><div class="field"><label>Icon</label><input id="m-iicon" placeholder="&#128188;" maxlength="2"></div></div><div class="field"><label>Amount (&#163;/month)</label><input id="m-iamount" type="number" step="0.01" placeholder="2400"></div><div class="field"><label>Note</label><input id="m-inote" placeholder="e.g. After tax"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveIncome()">Add &#10003;</button></div>'},
  editIncome:function(id){var i=(STATE.income||[]).find(function(x){return x.id===id});if(!i)return '';return '<h2>Edit income</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-iname" value="'+i.name+'"></div><div class="field"><label>Icon</label><input id="m-iicon" value="'+(i.icon||'&#128188;')+'" maxlength="2"></div></div><div class="field"><label>Amount (&#163;/month)</label><input id="m-iamount" type="number" value="'+i.amount+'" step="0.01"></div><div class="field"><label>Note</label><input id="m-inote" value="'+(i.note||'')+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="updateIncome(\''+id+'\')">Save &#10003;</button></div>'},
  addExpense:function(){return '<h2>&#128308; Add expense</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-ename" placeholder="e.g. Rent"></div><div class="field"><label>Icon</label><input id="m-eicon" placeholder="&#127968;" maxlength="2"></div></div><div class="field"><label>Amount (&#163;/month)</label><input id="m-eamount" type="number" step="0.01" placeholder="0"></div><div class="field"><label>Note</label><input id="m-enote" placeholder="optional"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveExpense()">Add &#10003;</button></div>'},
  editExpense:function(id){var e=(STATE.expenses||[]).find(function(x){return x.id===id});if(!e)return '';return '<h2>Edit expense</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-ename" value="'+e.name+'"></div><div class="field"><label>Icon</label><input id="m-eicon" value="'+(e.icon||'&#128184;')+'" maxlength="2"></div></div><div class="field"><label>Amount</label><input id="m-eamount" type="number" value="'+e.amount+'" step="0.01"></div><div class="field"><label>Note</label><input id="m-enote" value="'+(e.note||'')+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="updateExpense(\''+id+'\')">Save &#10003;</button></div>'},
  addAccount:function(){return '<h2>&#127968; Add account</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-aname" placeholder="e.g. Marcus Savings"></div><div class="field"><label>Type</label><select id="m-atype"><option value="savings">Savings</option><option value="investment">Investment</option></select></div></div><div class="field-row"><div class="field"><label>Balance (&#163;)</label><input id="m-abalance" type="number" step="0.01" placeholder="0"></div><div class="field"><label>Icon</label><input id="m-aicon" placeholder="&#128176;" maxlength="2"></div></div><div class="field-row"><div class="field"><label>Institution</label><input id="m-ainst" placeholder="Monzo"></div><div class="field"><label>AER %</label><input id="m-arate" type="number" step="0.01" placeholder="4.75"></div></div><div class="field"><label>Savings target (&#163;)</label><input id="m-atarget" type="number" placeholder="5000"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveAccount()">Add &#10003;</button></div>'},
  editAccount:function(id){var a=(STATE.accounts||[]).find(function(x){return x.id===id});if(!a)return '';return '<h2>Edit account</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-aname" value="'+a.name+'"></div><div class="field"><label>Icon</label><input id="m-aicon" value="'+(a.icon||'&#127968;')+'" maxlength="2"></div></div><div class="field"><label>Balance (&#163;)</label><input id="m-abalance" type="number" value="'+a.balance+'" step="0.01"></div><div class="field-row"><div class="field"><label>Institution</label><input id="m-ainst" value="'+(a.institution||'')+'"></div><div class="field"><label>AER %</label><input id="m-arate" type="number" value="'+(a.rate||'')+'" step="0.01"></div></div><div class="field"><label>Target (&#163;)</label><input id="m-atarget" type="number" value="'+(a.target||'')+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="updateAccount(\''+id+'\')">Save &#10003;</button></div>'},
  addDebt:function(){return '<h2>&#128179; Add debt</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-dname" placeholder="e.g. Amex, Klarna"></div><div class="field"><label>Priority</label><select id="m-dpriority"><option>High</option><option>Medium</option><option>Low</option></select></div></div><div class="field-row"><div class="field"><label>Balance (&#163;)</label><input id="m-dbalance" type="number" step="0.01" placeholder="0"></div><div class="field"><label>Due date</label><input id="m-ddue" type="date"></div></div><div class="field"><label>Note</label><input id="m-dnote" placeholder="e.g. Auto payments"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveDebt()">Add &#10003;</button></div>'},
  editDebt:function(id){var d=(STATE.debts||[]).find(function(x){return x.id===id});if(!d)return '';return '<h2>Edit debt</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-dname" value="'+d.name+'"></div><div class="field"><label>Priority</label><select id="m-dpriority"><option'+(d.priority==='High'?' selected':'')+'>High</option><option'+(d.priority==='Medium'?' selected':'')+'>Medium</option><option'+(d.priority==='Low'?' selected':'')+'>Low</option></select></div></div><div class="field-row"><div class="field"><label>Balance (&#163;)</label><input id="m-dbalance" type="number" value="'+d.balance+'" step="0.01"></div><div class="field"><label>Note</label><input id="m-dnote" value="'+(d.note||'')+'"></div></div><div class="field"><label>Due date</label><input id="m-ddue" type="date" value="'+(d.due||'')+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="updateDebt(\''+id+'\')">Save &#10003;</button></div>'},
  addSavingsGoal:function(){return '<h2>&#127919; Add savings goal</h2><div class="field-row"><div class="field"><label>Goal name</label><input id="m-sgname" placeholder="e.g. House Deposit"></div><div class="field"><label>Icon</label><input id="m-sgicon" placeholder="&#127968;" maxlength="2"></div></div><div class="field-row"><div class="field"><label>Target (&#163;)</label><input id="m-sgtarget" type="number" step="0.01" placeholder="15000"></div><div class="field"><label>Current (&#163;)</label><input id="m-sgcurrent" type="number" step="0.01" placeholder="0"></div></div><div class="field-row"><div class="field"><label>Priority</label><select id="m-sgpriority"><option>High</option><option>Medium</option><option>Low</option></select></div><div class="field"><label>Target date</label><input id="m-sgdeadline" type="date"></div></div><div class="field"><label>Note</label><input id="m-sgnote" placeholder="e.g. 5% on &#163;300k property"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveSavingsGoal()">Add &#10003;</button></div>'},
  editSavingsGoal:function(id){var sg=(STATE.savingsGoals||[]).find(function(x){return x.id===id});if(!sg)return '';return '<h2>Edit savings goal</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-sgname" value="'+sg.name+'"></div><div class="field"><label>Icon</label><input id="m-sgicon" value="'+(sg.icon||'&#127919;')+'" maxlength="2"></div></div><div class="field-row"><div class="field"><label>Target (&#163;)</label><input id="m-sgtarget" type="number" value="'+sg.target+'" step="0.01"></div><div class="field"><label>Current (&#163;)</label><input id="m-sgcurrent" type="number" value="'+(sg.current||0)+'" step="0.01"></div></div><div class="field-row"><div class="field"><label>Priority</label><select id="m-sgpriority"><option'+(sg.priority==='High'?' selected':'')+'>High</option><option'+(sg.priority==='Medium'?' selected':'')+'>Medium</option><option'+(sg.priority==='Low'?' selected':'')+'>Low</option></select></div><div class="field"><label>Target date</label><input id="m-sgdeadline" type="date" value="'+(sg.deadline||'')+'"></div></div><div class="field"><label>Note</label><input id="m-sgnote" value="'+(sg.note||'')+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="updateSavingsGoal(\''+id+'\')">Save &#10003;</button></div>'},
  logMetric:function(type){var today=localDateKey(new Date());if(!type){return '<h2>Log entry</h2><div class="modal-sub">What do you want to track?</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:16px">'+[['&#9878;&#65039;','Weight','weight'],['&#127939;','Run','run'],['&#128683;','Steps','steps'],['&#128176;','Money saved','moneySaved'],['&#10003;&#65039;','Achievement','project']].map(function(b){return '<button onclick="openModal(\'logMetric\',\''+b[2]+'\')" style="cursor:pointer;border:1.5px solid var(--border2);background:var(--bg2);padding:14px;border-radius:var(--radius-sm);display:flex;flex-direction:column;align-items:center;gap:5px"><span style="font-size:22px">'+b[0]+'</span><span style="font-size:13px;font-weight:500">'+b[1]+'</span></button>'}).join('')+'</div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button></div>'}
    if(type==='weight')return '<h2>&#9878;&#65039; Log weight</h2><div class="field-row"><div class="field"><label>Weight (kg)</label><input id="m-mval" type="number" step="0.1" placeholder="e.g. 86.5"></div><div class="field"><label>Date</label><input id="m-mdate" type="date" value="'+today+'"></div></div><div class="field"><label>Note</label><input id="m-mnote" placeholder="e.g. morning weigh-in"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveMetric(&quot;weight&quot;)">Log &#10003;</button></div>';
    if(type==='run')return '<h2>&#127939; Log a run</h2><div class="field-row"><div class="field"><label>Distance (km)</label><input id="m-mval" type="number" step="0.1" placeholder="e.g. 5.2"></div><div class="field"><label>Time (mm:ss)</label><input id="m-mtime" placeholder="e.g. 28:30"></div></div><div class="field-row"><div class="field"><label>Date</label><input id="m-mdate" type="date" value="'+today+'"></div><div class="field"><label>Note</label><input id="m-mnote" placeholder="e.g. parkrun"></div></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveMetric(&quot;run&quot;)">Log &#10003;</button></div>';
    if(type==='steps')return '<h2>&#128683; Log weekly steps</h2><div class="field-row"><div class="field"><label>Avg daily steps</label><input id="m-mval" type="number" placeholder="e.g. 8500"></div><div class="field"><label>Week starting</label><input id="m-mdate" type="date" value="'+weekKey(new Date())+'"></div></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveMetric(&quot;steps&quot;)">Log &#10003;</button></div>';
    if(type==='moneySaved')return '<h2>&#128176; Log money saved</h2><div class="field-row"><div class="field"><label>Amount (&#163;)</label><input id="m-mval" type="number" step="0.01" placeholder="e.g. 200"></div><div class="field"><label>Date</label><input id="m-mdate" type="date" value="'+today+'"></div></div><div class="field"><label>Note</label><input id="m-mnote" placeholder="e.g. ISA deposit"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveMetric(&quot;moneySaved&quot;)">Log &#10003;</button></div>';
    return '<h2>&#10003;&#65039; Log achievement</h2><div class="field"><label>Achievement</label><input id="m-mname" placeholder="e.g. Finished SQL course"></div><div class="field"><label>Date</label><input id="m-mdate" type="date" value="'+today+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveMetric(&quot;project&quot;)">Log &#10003;</button></div>'},
  addProject:function(){return '<h2>Add project</h2><div class="field"><label>Name</label><input id="m-pname" placeholder="e.g. Build portfolio site"></div><div class="field-row"><div class="field"><label>Category</label><select id="m-pcat"><option>Career</option><option>Personal</option><option>Finance</option><option>Fitness</option></select></div><div class="field"><label>Status</label><select id="m-pstatus"><option value="active">Active</option><option value="paused">Paused</option><option value="done">Done</option></select></div></div><div class="field"><label>Deadline</label><input id="m-pdeadline" type="date"></div><div class="field"><label>Description</label><textarea id="m-pdesc" placeholder="What is this project about?"></textarea></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveProject()">Add</button></div>'},
  editProject:function(id){var proj=(STATE.projects||[]).find(function(p){return p.id===id});if(!proj)return '';return '<h2>Edit project</h2><div class="field"><label>Name</label><input id="m-pname" value="'+proj.name.replace(/"/g,'&quot;')+'"></div><div class="field"><label>Status</label><select id="m-pstatus"><option value="active"'+(proj.status==='active'?' selected':'')+'>Active</option><option value="paused"'+(proj.status==='paused'?' selected':'')+'>Paused</option><option value="done"'+(proj.status==='done'?' selected':'')+'>Done</option></select></div><div class="field"><label>Description</label><textarea id="m-pdesc">'+(proj.desc||'')+'</textarea></div><div class="field"><label>Deadline</label><input id="m-pdeadline" type="date" value="'+(proj.deadline||'')+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="updateProject(\''+id+'\')">Save</button></div>'},
  addProjectTask:function(id){return '<h2>Add task</h2><div class="field"><label>Task</label><input id="m-ptask" placeholder="e.g. Write section 2"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveProjectTask(\''+id+'\')">Add</button></div>'},
  addRelationship:function(){return '<h2>Add person</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-rname" placeholder="e.g. Sarah"></div><div class="field"><label>Category</label><select id="m-rcat"><option>Partner</option><option>Family</option><option>Friend</option></select></div></div><div class="field-row"><div class="field"><label>Check-in every (days)</label><input id="m-rfreq" type="number" value="14"></div><div class="field"><label>Icon</label><input id="m-ricon" placeholder="&#128100;" maxlength="2"></div></div><div class="field"><label>Note</label><input id="m-rnote" placeholder="e.g. Call weekly"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveRelationship()">Add</button></div>'},
  editRelationship:function(id){var r=(STATE.relationships||[]).find(function(x){return x.id===id});if(!r)return '';return '<h2>Edit</h2><div class="field-row"><div class="field"><label>Name</label><input id="m-rname" value="'+r.name.replace(/"/g,'&quot;')+'"></div><div class="field"><label>Icon</label><input id="m-ricon" value="'+(r.icon||'&#128100;')+'" maxlength="2"></div></div><div class="field-row"><div class="field"><label>Check-in every (days)</label><input id="m-rfreq" type="number" value="'+r.freq+'"></div><div class="field"><label>Note</label><input id="m-rnote" value="'+(r.note||'').replace(/"/g,'&quot;')+'"></div></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="updateRelationship(\''+id+'\')">Save</button></div>'},
  addGratitude:function(){var today=localDateKey(new Date());return '<h2>Add entry</h2><div class="field"><label>Date</label><input id="m-gdate" type="date" value="'+today+'"></div><div class="field"><label>Win of the day</label><input id="m-gwins" placeholder="Something you achieved or are proud of"></div><div class="field"><label>3 things I am grateful for</label><textarea id="m-ggratitude" placeholder="1. &#10;2. &#10;3. " style="min-height:80px"></textarea></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveGratitudeEntry()">Save</button></div>'},
  addWatchItem:function(){return '<h2>Add to watch list</h2><div class="field-row"><div class="field"><label>Title</label><input id="m-wname" placeholder="e.g. Interstellar"></div><div class="field"><label>Type</label><select id="m-wtype"><option>Movie</option><option>Series</option><option>YouTube</option><option>Documentary</option></select></div></div><div class="field"><label>Status</label><select id="m-wstatus"><option value="want">Want to watch</option><option value="watching">Watching</option><option value="done">Done</option></select></div><div class="field"><label>Note</label><input id="m-wnote" placeholder="optional"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveWatchItem()">Add</button></div>'},
  addWishItem:function(){return '<h2>Add to wishlist</h2><div class="modal-sub">It will sit here for 30 days before you can buy it.</div><div class="field"><label>Item name</label><input id="m-wname" placeholder="e.g. Nike trainers"></div><div class="field-row"><div class="field"><label>Price (&#163;)</label><input id="m-wprice" type="number" step="0.01" placeholder="0.00"></div><div class="field"><label>Category</label><input id="m-wcat" placeholder="e.g. Clothes, Tech"></div></div><div class="field"><label>Note</label><input id="m-wnote" placeholder="Why do you want this?"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveWishItem()">Add to waitlist</button></div>'},
  startSession:function(){var templates=STATE.gymTemplates||[];return '<h2>Start session</h2><div class="modal-sub">Choose a template or create a custom session</div><div style="margin-bottom:14px"><div class="card-label" style="margin-bottom:8px">From template</div>'+templates.map(function(t){return '<div class="card-sm" style="margin-bottom:8px;cursor:pointer;border:1px solid var(--border)" onclick="startFromTemplate(\''+t.id+'\')"><div style="font-size:13px;font-weight:500">'+t.name+'</div><div style="font-size:12px;color:var(--text2);margin-top:2px">'+(t.muscleGroups||[]).join(', ')+' &#183; '+t.exercises.length+' exercises</div></div>'}).join('')+'</div><div class="divider"></div><div class="card-label" style="margin-bottom:8px">Custom session</div><div class="field"><label>Session name</label><input id="m-sname" placeholder="e.g. Upper Body A"></div><div class="field"><label>Muscle groups</label><input id="m-muscles" placeholder="e.g. Chest, Triceps"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="createCustomSession()">Create</button></div>'},
  logRun:function(){var today=localDateKey(new Date());return '<h2>&#127939; Log a run</h2><div class="field-row"><div class="field"><label>Distance (km)</label><input id="m-rundist" type="number" step="0.1" placeholder="e.g. 5.2"></div><div class="field"><label>Time (mm:ss)</label><input id="m-runtime" placeholder="e.g. 28:30"></div></div><div class="field-row"><div class="field"><label>Date</label><input id="m-rundate" type="date" value="'+today+'"></div><div class="field"><label>Note</label><input id="m-runnote" placeholder="e.g. parkrun, easy jog"></div></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveRunFromWorkout()">Log &#10003;</button></div>'},
  viewSession:function(id){var sess=(STATE.workouts||[]).find(function(w){return w.id===id});if(!sess)return '<h2>Not found</h2>';var isActive=activeSessionId===id;return '<h2>'+sess.name+'</h2><div class="modal-sub">'+fmtDate(sess.date)+' &#183; '+((sess.muscleGroups||[]).join(', '))+'</div><div id="session-exercises">'+(sess.exercises||[]).map(function(e,ei){var prev=getBestPrevSet(id,e.name);return '<div style="margin-bottom:14px;border-bottom:1px solid var(--border);padding-bottom:14px"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><div><div style="font-size:14px;font-weight:500">'+e.name+'</div>'+(prev?'<div style="font-size:11px;color:var(--text3)">Prev best: '+prev.weight+'kg&#215;'+prev.reps+'</div>':'')+'</div>'+(isActive?'<button class="btn btn-sm" onclick="addSet(\''+id+'\','+ei+')">+ Set</button>':'')+'</div>'+(e.sets||[]).map(function(s,si){return '<div style="display:grid;grid-template-columns:auto 1fr 1fr auto;gap:6px;align-items:center;margin-bottom:4px"><span style="font-size:12px;color:var(--text3);min-width:20px">'+(si+1)+'</span>'+(isActive?'<input type="number" value="'+(s.weight||'')+'" placeholder="kg" style="padding:5px 8px;font-size:13px;background:var(--bg3);border:1px solid var(--border2);border-radius:6px;color:var(--text);outline:none" onchange="updateSet(\''+id+'\','+ei+','+si+',\'weight\',this.value)"><input type="number" value="'+(s.reps||'')+'" placeholder="reps" style="padding:5px 8px;font-size:13px;background:var(--bg3);border:1px solid var(--border2);border-radius:6px;color:var(--text);outline:none" onchange="updateSet(\''+id+'\','+ei+','+si+',\'reps\',this.value)">':'<span style="font-size:13px">'+(s.weight||'&#8212;')+'kg</span><span style="font-size:13px">'+(s.reps||'&#8212;')+'</span>')+'<div class="sub-goal-check '+(s.logged?'done':'')+'" onclick="'+(isActive?'toggleSetLogged(\''+id+'\','+ei+','+si+')':'')+'"></div></div>'}).join('')+(!(e.sets||[]).length?'<div style="font-size:12px;color:var(--text3);padding:5px 0">No sets logged'+(isActive?' &#8212; click + Set above':'')+'</div>':'')+'</div>'}).join('')+'</div>'+(isActive?'<button class="btn btn-sm" style="width:100%;justify-content:center;margin-bottom:12px" onclick="addExercise(\''+id+'\')">+ Add exercise</button><div class="modal-btns"><button class="btn" onclick="closeModal()">Keep open</button><button class="btn btn-accent" onclick="finishSession(\''+id+'\')">Finish &#10003;</button></div>':'<button class="btn btn-ghost btn-sm" onclick="closeModal()">Close</button>')},
  addPR:function(){return '<h2>Log personal record</h2><div class="field"><label>Exercise</label><input id="m-prname" placeholder="e.g. Squat, Bench Press"></div><div class="field-row"><div class="field"><label>Weight (kg)</label><input id="m-prweight" type="number" step="0.5"></div><div class="field"><label>Reps</label><input id="m-prreps" type="number"></div></div><div class="field"><label>Date</label><input id="m-prdate" type="date" value="'+localDateKey(new Date())+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveManualPR()">Save PR</button></div>'},
  manageTemplates:function(){var templates=STATE.gymTemplates||[];return '<h2>Workout templates</h2>'+templates.map(function(t){return '<div class="card-sm" style="margin-bottom:8px;border:1px solid var(--border)"><div style="display:flex;justify-content:space-between"><div><div style="font-size:13px;font-weight:500">'+t.name+'</div><div style="font-size:11px;color:var(--text2);margin-top:2px">'+t.exercises.map(function(e){return e.name+' '+e.sets+'&#215;'+e.targetReps}).join(' &#183; ')+'</div></div><button class="btn btn-sm btn-danger" onclick="deleteTemplate(\''+t.id+'\')">&#215;</button></div></div>'}).join('')+'<div class="divider"></div><div class="card-label" style="margin-bottom:8px">New template</div><div class="field"><label>Name</label><input id="m-tname" placeholder="e.g. Push A"></div><div class="field"><label>Muscle groups</label><input id="m-tmuscles" placeholder="Chest, Shoulders, Triceps"></div><div class="field"><label>Exercises (one per line: Name, Sets, Reps)</label><textarea id="m-texercises" placeholder="Bench Press, 4, 5&#10;OHP, 3, 8"></textarea></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Close</button><button class="btn btn-accent" onclick="saveTemplate()">Add template</button></div>'},
  logMood:function(dateArg){var d=dateArg||localDateKey(new Date());journalMoodVals={mood:0,energy:0};var m=(STATE.mood||{})[d]||{};if(m.mood)journalMoodVals.mood=m.mood;if(m.energy)journalMoodVals.energy=m.energy;var mE=['&#128542;','&#128528;','&#128578;','&#128522;','&#129321;'];var eE=['&#129803;','&#128564;','&#9889;','&#128293;','&#128640;'];function mkRow(emojis,rtype,cur){return emojis.map(function(e,i){var v=i+1;var sel=cur===v;return '<button type="button" data-rtype="'+rtype+'" data-val="'+v+'" onclick="pickMood(this)" style="flex:1;padding:8px 4px;border:2px solid '+(sel?'var(--accent)':'var(--border2)')+';background:'+(sel?'var(--accent-dim)':'var(--bg3)')+';border-radius:10px;cursor:pointer;text-align:center"><div style="font-size:22px">'+e+'</div></button>'}).join('')}return '<h2>Daily check-in</h2><div class="modal-sub">'+fmtDate(d)+'</div><div class="field"><label>Mood</label><div style="display:flex;gap:6px">'+mkRow(mE,'mood',m.mood)+'</div></div><div class="field"><label>Energy</label><div style="display:flex;gap:6px">'+mkRow(eE,'energy',m.energy)+'</div></div><div class="field-row"><div class="field"><label>Sleep (hrs)</label><input id="m-sleep" type="number" min="0" max="12" step="0.5" value="'+(m.sleep||'')+'" placeholder="7.5"></div><div class="field"><label>Water (ml)</label><input id="m-water" type="number" min="0" max="5000" step="100" value="'+(m.water||'')+'" placeholder="2000"></div></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveMoodFromModal(\''+d+'\')">Save</button></div>'},
  logDebtPayment:function(){var debts=(STATE.debts||[]).filter(function(d){return Number(d.balance)>0});var opts=debts.map(function(d){return '<option value="'+d.id+'">'+d.name+' ('+fmtMoney(d.balance)+')</option>'}).join('');return '<h2>💳 Log debt payment</h2><div class="field"><label>Which debt?</label><select id="m-dp-debt">'+opts+'</select></div><div class="field-row"><div class="field"><label>Amount (£)</label><input id="m-dp-amount" type="number" step="0.01" placeholder="100"></div><div class="field"><label>Date</label><input id="m-dp-date" type="date" value="'+localDateKey(new Date())+'"></div></div><div class="field"><label>Note (optional)</label><input id="m-dp-note" placeholder="e.g. Extra payment from bonus"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="saveDebtPayment()">Log payment ✓</button></div>'},
  addPlannedPayment:function(){var debts=(STATE.debts||[]).filter(function(d){return Number(d.balance)>0});var opts=debts.map(function(d){return '<option value="'+d.id+'">'+d.name+' ('+fmtMoney(d.balance)+')</option>'}).join('');return '<h2>📅 Plan a payment</h2><div class="modal-sub">Add a payment you intend to make this month</div><div class="field"><label>Which debt?</label><select id="m-ppdebt">'+opts+'</select></div><div class="field-row"><div class="field"><label>Amount (£)</label><input id="m-ppamount" type="number" step="0.01" placeholder="200"></div><div class="field"><label>Date</label><input id="m-ppdate" type="date" value="'+localDateKey(new Date())+'"></div></div><div class="field"><label>Note (optional)</label><input id="m-ppnote" placeholder="e.g. Payday payment"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="savePlannedPayment()">Add to plan ✓</button></div>'}
};var fn=modals[type];if(!fn)return;mc.innerHTML=fn.apply(null,args);document.getElementById('modal').style.display='flex'}

/* Debt payment logging */
function saveDebtPayment(){var debtId=(document.getElementById('m-dp-debt')||{}).value;var amount=Number((document.getElementById('m-dp-amount')||{}).value)||0;var date=(document.getElementById('m-dp-date')||{}).value||localDateKey(new Date());var note=(document.getElementById('m-dp-note')||{}).value||'';if(!debtId||!amount)return;if(!STATE.debtPayments)STATE.debtPayments=[];STATE.debtPayments.push({id:g(),debtId:debtId,amount:amount,date:date,note:note});
/* Also reduce the debt balance */
var debt=(STATE.debts||[]).find(function(d){return d.id===debtId});if(debt){debt.balance=Math.max(0,Number(debt.balance)-amount)}
saveState();closeModal();renderInsights();renderDebts()}
function deleteDebtPayment(pid){if(!confirm('Delete this payment?'))return;STATE.debtPayments=(STATE.debtPayments||[]).filter(function(p){return p.id!==pid});saveState();renderInsights();renderDebts()}

function pickMood(btn){var rtype=btn.getAttribute('data-rtype');var val=parseInt(btn.getAttribute('data-val'));journalMoodVals[rtype]=val;btn.parentNode.querySelectorAll('button').forEach(function(b){var selected=parseInt(b.getAttribute('data-val'))===val;b.style.background=selected?'var(--accent-dim)':'var(--bg3)';b.style.borderColor=selected?'var(--accent)':'var(--border2)'})}
function saveMoodFromModal(date){if(!STATE.mood)STATE.mood={};STATE.mood[date]={mood:journalMoodVals.mood||0,energy:journalMoodVals.energy||0,sleep:Number((document.getElementById('m-sleep')||{}).value)||0,water:Number((document.getElementById('m-water')||{}).value)||0};saveState();closeModal();if(document.getElementById('page-weekly').classList.contains('active'))renderWeeklyPlan();renderDashMoodCheckin()}

// Workout helpers
function startFromTemplate(tid){var t=(STATE.gymTemplates||[]).find(function(x){return x.id===tid});if(!t)return;var sess={id:g(),name:t.name,date:localDateKey(new Date()),muscleGroups:t.muscleGroups||[],exercises:t.exercises.map(function(e){return {name:e.name,sets:Array.from({length:Number(e.sets)||3},function(){return {weight:'',reps:'',logged:false}})}})};if(!STATE.workouts)STATE.workouts=[];STATE.workouts.push(sess);activeSessionId=sess.id;saveState();closeModal();openModal('viewSession',sess.id)}
function createCustomSession(){var name=((document.getElementById('m-sname')||{}).value||'').trim();if(!name)return;var muscles=((document.getElementById('m-muscles')||{}).value||'').split(',').map(function(m){return m.trim()}).filter(Boolean);var sess={id:g(),name:name,date:localDateKey(new Date()),muscleGroups:muscles,exercises:[]};if(!STATE.workouts)STATE.workouts=[];STATE.workouts.push(sess);activeSessionId=sess.id;saveState();closeModal();openModal('viewSession',sess.id)}
function addExercise(sessionId){var name=prompt('Exercise name:');if(!name)return;var sess=(STATE.workouts||[]).find(function(w){return w.id===sessionId});if(!sess)return;sess.exercises.push({name:name.trim(),sets:[{weight:'',reps:'',logged:false}]});saveState();openModal('viewSession',sessionId)}
function addSet(sessionId,exIdx){var sess=(STATE.workouts||[]).find(function(w){return w.id===sessionId});if(!sess)return;var ex=sess.exercises[exIdx];if(!ex)return;var prev=ex.sets[ex.sets.length-1];ex.sets.push({weight:(prev&&prev.weight)||'',reps:(prev&&prev.reps)||'',logged:false});saveState();openModal('viewSession',sessionId)}
function updateSet(sessionId,exIdx,setIdx,field,value){var sess=(STATE.workouts||[]).find(function(w){return w.id===sessionId});if(!sess)return;sess.exercises[exIdx].sets[setIdx][field]=value;saveState()}
function toggleSetLogged(sessionId,exIdx,setIdx){var sess=(STATE.workouts||[]).find(function(w){return w.id===sessionId});if(!sess)return;sess.exercises[exIdx].sets[setIdx].logged=!sess.exercises[exIdx].sets[setIdx].logged;saveState();openModal('viewSession',sessionId)}
function finishSession(id){if(activeSessionId===id)activeSessionId=null;saveState();closeModal();renderWorkout()}
function saveTemplate(){var name=((document.getElementById('m-tname')||{}).value||'').trim();if(!name)return;var muscles=((document.getElementById('m-tmuscles')||{}).value||'').split(',').map(function(m){return m.trim()}).filter(Boolean);var lines=((document.getElementById('m-texercises')||{}).value||'').split('\n').filter(Boolean);var exercises=lines.map(function(l){var p=l.split(',');return {name:(p[0]||'').trim(),sets:parseInt(p[1])||3,targetReps:(p[2]||'10').trim(),unit:'kg'}}).filter(function(e){return e.name});if(!STATE.gymTemplates)STATE.gymTemplates=[];STATE.gymTemplates.push({id:g(),name:name,muscleGroups:muscles,exercises:exercises});saveState();closeModal();openModal('manageTemplates')}
function deleteTemplate(id){STATE.gymTemplates=(STATE.gymTemplates||[]).filter(function(t){return t.id!==id});saveState();closeModal();openModal('manageTemplates')}
function saveManualPR(){var name=((document.getElementById('m-prname')||{}).value||'').trim();if(!name)return;if(!STATE.prs)STATE.prs={};STATE.prs[name]={weight:Number((document.getElementById('m-prweight')||{}).value)||0,reps:Number((document.getElementById('m-prreps')||{}).value)||0,date:(document.getElementById('m-prdate')||{}).value};saveState();closeModal();renderPRs()}

// Confirm delete
var _pendingDelete=null;
function confirmDelete(message,onConfirm){_pendingDelete=onConfirm;var mc=document.getElementById('modal-content');mc.innerHTML='<h2 style="font-size:18px">&#128465;&#65039; Are you sure?</h2><div class="modal-sub">'+message+'</div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn" style="background:#c0392b;color:#fff;border-color:#c0392b;font-weight:600" onclick="executePendingDelete()">Delete</button></div>';document.getElementById('modal').style.display='flex'}
function executePendingDelete(){if(_pendingDelete){_pendingDelete();_pendingDelete=null}closeModal()}
function closeModal(){document.getElementById('modal').style.display='none'}
function modalBgClick(e){if(e.target===document.getElementById('modal'))closeModal()}
document.addEventListener('keydown',function(e){if(e.key==='Escape')closeModal()});

// ── MY PLAN PROGRESS BAR ──
// handled by renderMyPlanStats()

// ── HYROX PROGRAMME ──
var hyroxPlans={
standard:[
{week:1,days:[{label:"Day 1",warmup:"4 Rounds\n150 m Run, 20 Sec Rest, then\n2 Rounds\n250 m Run, 30 Sec Rest",workout:"FOR TIME\n3000 m Run*\n*every 3 Min. perform 5 Burpees",core:"1 Round\n25 Sit Ups\n25 Superman\n25 Flutter Kicks"},{label:"Day 2",rest:"REST DAY"},{label:"Day 3",warmup:"1000 m Row",workout:"FOR TIME\na) 5 Rounds: 250 m Row, 30 Sec Rest\nb) 4 Rounds: 15 Wall Balls, 30 Sec Rest\nc) 4 Rounds: 30 Sec Farmers Carry, 30 Sec Rest"},{label:"Day 4",rest:"REST DAY"},{label:"Day 5",warmup:"5 Min. Easy Jog",workout:'"GEORGE" FOR TIME\n250 m Run, then\n1 Round: 20 Squats, 20 Burpees, 20 Sit Ups, 20 Push Ups, then\n250 m Run',core:"3 Rounds\n45 Sec. Plank hold\n30 Sec. Rest"}]},
{week:2,days:[{label:"Day 1",warmup:"1 Round\n5 Min. Run, 1 Min. Rest\n5 Min. Row or Run, 1 Min. Rest\n5 Min. Ski Erg or Run",workout:"a) 10 Rounds: 30 Sec. Sprint, 30 Sec. Rest\nb) FOR TIME – 3 Rounds: 10 Mountain Climber, 10 Lunges, 10 Sit Ups"},{label:"Day 2",rest:"REST DAY"},{label:"Day 3",warmup:"1 Round: 25 Jumping Jacks, 20 Sit Ups, 15 Squats, 10 Push Ups",workout:"a) 2 Rounds: 25 m Sled Push, 1 Min. Rest\n   2 Rounds: 25 m Sled Pull, 1 Min. Rest\nb) FOR TIME – 30-20-10: Row for cal, Burpees, Lunges"},{label:"Day 4",rest:"REST DAY"},{label:"Day 5",warmup:"3 Min. Run",workout:"a) 3 Rounds: 10 Bench Press, 10 Deadlift, 10 Back Squat, 2 Min. Rest\nb) 3 Rounds: 1 Min. Row for Cal, 1 Min. 25 m Shuttle Run, 1 Min. Burpees, 1 Min. Sit Ups, 1 Min. Rest",core:"3 Rounds\n15 V-Ups\n15 Superman"}]},
{week:3,days:[{label:"Day 1",warmup:"2 Rounds: 200 m Run, 10 Squats, 5 Burpees, 10 Sit Ups",workout:'"ZEPPELIN" (SCALED) FOR TIME\n500 m Run, then\n50 Wall Balls, 40 Lunges, 30 Burpees, 20 Sit Ups, 10 Push Ups, then\n500 m Run',core:"3 Rounds\n1 Min. Stability Ball Bridges\n30 Sec. Rest"},{label:"Day 2",rest:"REST DAY"},{label:"Day 3",warmup:"500 m Row / 10 Inch Worm\n2 Rounds: 5 Push Ups, 5 Squats, 10 Sit Ups",workout:"a) 2 Rounds: 50 m Sled Push, 1 Min. Rest\n   2 Rounds: 50 m Sled Pull, 1 Min. Rest\nb) FOR TIME: 1500 m Row\nc) 4 Rounds: 30 Sec Farmers Carry, 30 Sec Rest"},{label:"Day 4",rest:"REST DAY"},{label:"Day 5",warmup:"4 Rounds: 150 m Run, 20 Sec Rest\n2 Rounds: 250 m Run, 30 Sec Rest",workout:"a) 4 Rounds: 15 Push Ups\nb) 4 Rounds: 25 Back Squats\nc) 10 Rounds: 200 m Run, 2 Min. Rest",core:"3 Rounds\n30 Sec. Toe Touches\n30 Sec. Flutter Kicks\n30 Sec. Russian Twist\n30 Sec. Side Plank (each side)\n1 Min. Rest"}]},
{week:4,days:[{label:"Day 1",warmup:"4 Rounds: 150 m Run, 20 Sec Rest\n2 Rounds: 250 m Run, 30 Sec Rest",workout:"FOR TIME – 3 Rounds:\n20 Box Jumps, 20 Lunges, 20 Row for Cal, 20 Sit Ups, 20 Wall Balls",core:"1 Round\n25 Sit Ups\n25 Superman\n25 Flutter Kicks"},{label:"Day 2",rest:"REST DAY"},{label:"Day 3",warmup:"1 Round: 2 Min. Jump Rope, 25 m High Knees, 25 m Buttkicks, 25 m Lunges, 25 m Side Lunges",workout:'"BIGGIE" (SCALED)\n3 Rounds:\n1 Min. Wall Balls, 30 Sec. Rest\n1 Min. Burpee Broad Jump, 30 Sec. Rest\n1 Min. Row for Cal, 30 Sec. Rest\n1 Min. 10 m Shuttle Run, 30 Sec. Rest'},{label:"Day 4",rest:"REST DAY"},{label:"Day 5",warmup:"1 Round: 50 Jumping Jacks, 10 Tuck Jumps, 20 Lunges",workout:'a) 4 Rounds: 10 Bench Press, 10 Deadlift, 10 Back Squat, 2 Min. Rest\nb) "MITCHELL" FOR TIME:\n400 m Run, 50 Squats\n400 m Run, 50 Sit Ups\n400 m Run, 50 Lunges',core:"3 Rounds\n10 Bird Dogs r/l\n30 Sec. Plank"}]},
{week:5,days:[{label:"Day 1",warmup:"4 Rounds: 200 m Run, 30 Sec Rest",workout:"5000 m Run*\n*every 3 Min. perform 5 Burpees and 10 Squats",core:"1 Round\n50 Sit Ups\n50 Supermen\n1 Min. Plank hold"},{label:"Day 2",rest:"REST DAY"},{label:"Day 3",warmup:"1 Round: 25 m Lunges, 25 m Side Lunges, 25 m Broad Jumps, 25 m Inch Worm",workout:'"STARR" (SCALED) FOR TIME\n800 m Run\n30 Mountain Climber\n600 m Ski Erg\n30 Weighted Lunges @ 2x KB\n400 m Run\n30 Goblet Squats @ KB\n200 m Ski Erg\n30 Wall Balls'},{label:"Day 4",rest:"REST DAY"},{label:"Day 5",warmup:"1 Round: 50 Jumping Jacks, 200 m Run, 50 Jumping Jacks",workout:"a) 4 Rounds: 10 Weighted Step Ups on Box\nb) 4 Rounds: Max Rep Push Ups\nc) 20 Min. AMRAP: 10 Shuttle Run, 10 Wallballs, 10 Sit Ups",core:"3 Rounds\n10 Glute Bridges"}]},
{week:6,days:[{label:"Day 1",warmup:"4 Rounds: 150 m Run, 20 Sec Rest\n2 Rounds: 250 m Run, 30 Sec Rest",workout:"FOR TIME\n1000 m Run, then\n60-40-20: Sandbag Lunges, Single Leg Deadlift, Mountain Climbers, then\n1000 m Run",core:"3 Rounds\n30 Sec. Plank\n30 Sec. Side Plank (each side)"},{label:"Day 2",rest:"REST DAY"},{label:"Day 3",warmup:"1000 m Row",workout:"a) 5 Rounds: 100 m Farmers Carry, 90 Sec. Rest\nb) 4 Rounds: 50 m Sled Push, 2 Min. Rest\nc) 4 Rounds: 50 m Sled Pull, 2 Min. Rest",core:"3 Rounds\n15 Hanging Knee Raises\n20 Sit Ups\n15 Hyperextensions"},{label:"Day 4",rest:"REST DAY"},{label:"Day 5",warmup:"1 Round: 5 Min. Easy Jog, 10 Burpees, 10 Box Jumps, 10 V-Ups",workout:"a) 5 Rounds: 10 Bench Press, 10 Deadlift, 10 Back Squat, 2 Min. Rest\nb) FOR TIME – 3 Rounds: 600 m Run or Row, 50 Weighted Step over Box, 25 Push Ups"}]},
{week:7,days:[{label:"Day 1",warmup:"25 m Bear Crawl\n25 m Crab Walk\n25 m Inch Worm",workout:"FOR TIME – 3 Rounds:\n400 m Run\n5 Min. Ski Erg for Cal\n5 Min. Row for Cal\n3 Min. Rest",core:"1 Round\n50 V-Ups\n50 Supermen"},{label:"Day 2",rest:"REST DAY"},{label:"Day 3",warmup:"1 Round: 2 Min. Jump Rope, 25 m High Knees, 25 m Buttkicks, 25 m Lunges, 25 m Side Lunges",workout:"FOR TIME – 4 Rounds:\n400 m Row\n25 m Sled Push\n25 m Sled Pull"},{label:"Day 4",rest:"REST DAY"},{label:"Day 5",warmup:"1 Round: 50 Jumping Jacks, 10 Tuck Jumps, 20 Lunges",workout:'a) 4 Rounds: 10 Bench Press, 10 Deadlift, 10 Back Squat, 2 Min. Rest\nb) "SHAKUR"\n(1) 5 Min. AMRAP: 10 Burpees, 10 Push Ups – 3 Min. Rest\n(2) 5 Min. AMRAP: 10 Air Squats, 10 KB Swings – 3 Min. Rest\n(3) 5 Min. AMRAP: 10 Weighted Lunges, 10 Wall Balls',core:"3 Rounds\n10 Bird Dogs r/l\n45 Sec. Plank\n45 Sec. Side Plank (each side)\n15 Glute Bridges"}]},
{week:8,days:[{label:"Day 1",warmup:"5 Min. Jump Rope\n5 Min. Stretching",workout:'"FRANKLIN" FOR TIME\n10 Min. Run\n50 Jumping Squats\n10 Min. Run\n50 Wall Balls\n10 Min. Run',core:"3 Rounds\n20 Russian Twist"},{label:"Day 2",rest:"REST DAY"},{label:"Day 3",warmup:"1 Round: 25 m High Knees, 25 m Buttkicks, 25 m Lunges, 25 m Side Lunges",workout:'"KRAVITZ" FOR TIME\n8 Rounds:\n1000 m Run\n20 Wallballs\n20 Sit Ups\n20 Lunges'},{label:"Day 4",rest:"ACTIVE RECOVERY\n20 Min. Easy Row\n20 Min. Mobility / Stretching"},{label:"Day 5",rest:"TOTAL REST"}]}
],
pro:[
{week:1,days:[{label:"Tag 1",warmup:"4 Rounds: 200 m Run, 30 Sec Rest\n2 Rounds: 400 m Run, 30 Sec Rest",workout:"FOR TIME\n5000 m Run*\n*every 3 Min. perform 10 Burpees",core:"25 Situps\n25 Superman\n25 Flutter Kicks"},{label:"Tag 2",warmup:"3 Rounds: 10 Squats, 10 Buttlifts",workout:"a) 5 Rounds: 12-15 Back Squats, 2 Min. Rest\nb) 5 Rounds: 12-15 Bench Press, 2 Min. Rest\nc) 5 Rounds: Max Reps Pull Ups, 2 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 3",warmup:"1000 m Row\n10 Inch Worm",workout:"a) 5 Rounds: 500 m Row, 30 Sec Rest\nb) 4 Rounds: 25 Wallballs, 1 Min. Rest\nc) 4 Rounds: 1 Min. Farmers Carry, 1 Min. Rest"},{label:"Tag 4",warmup:"500 m Row\n3 Rounds: 10 Good Mornings",workout:"a) 5 Rounds: 12-15 Deadlifts, 2 Min. Rest\nb) 5 Rounds: 12-15 Shoulder Press, 2 Min. Rest\nc) 5 Rounds: 12-15 Plyo Push Ups, 2 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 5",warmup:"3 Min. Easy Jog",workout:'"GEORGE" FOR TIME\n1000 m Run, then\n5 Rounds: 20 Squats, 20 Burpees, 20 Sit Ups, 20 Push Ups, then\n1000 m Run',core:"3 Rounds\n45 Sec. Plank hold\n30 Sec. Rest"}]},
{week:2,days:[{label:"Tag 1",warmup:"5 Min. Run, 1 Min. Rest\n5 Min. Row or Run, 1 Min. Rest\n5 Min. Ski Erg or Run",workout:"a) 10 Rounds: 45 Sec. Sprint, 30 Sec. Rest\nb) FOR TIME – 5 Rounds: 10 Mountain Climber, 10 Lunges, 10 Sit Ups"},{label:"Tag 2",warmup:"400 m Run, 10 Squats, 10 Push Ups, 10 Inch Worm",workout:"a) 5 Rounds: 25 m Sled Push AHAP, 3-5 Min. Rest\nb) 5 Rounds: 25 m Sled Pull, 3-5 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 3",warmup:"25 Jumping Jacks, 20 Situps, 15 Squats, 10 Burpees",workout:'"STING" COUNTDOWN\n50-40-30-20-10\nRow for cal, Burpees, Lunges',core:"5 Rounds\n45-60 Sec. Plank\n30 Sec. Rest"},{label:"Tag 4",warmup:"10 Min. Easy Run\n3 Rounds: 10 Step Ups on box",workout:"a) 4 Rounds: 10 Front Rack Lunges with Barbell AHAP, 3-5 Min. Rest\nb) 4 Rounds: 10 Hamstring Curls, 90 Sec. Rest\nc) 4 Rounds: 10 Abductor Machine, 90 Sec. Rest\nd) 4 Rounds: 10 Adductor Machine, 90 Sec. Rest",core:"10 Min. Foam Roller"},{label:"Tag 5",warmup:"3 Min. Run",workout:"FOR TIME – 5 Rounds:\n1 Min. Row/Ski Erg for Cal\n1 Min. 25 m Shuttle Run\n1 Min. Burpees\n1 Min. Sit Ups\n1 Min. Rest",core:"5 Rounds\n15 V-Ups\n15 Superman"}]},
{week:3,days:[{label:"Tag 1",warmup:"2 Rounds: 200 m Run, 10 Squats, 5 Burpees, 10 Situps",workout:'"ZEPPELIN" FOR TIME\n1500 m Run, then\n100 Wall Balls, 80 Lunges, 60 Burpees, 40 Sit Ups, 20 Push Ups, then\n1500 m Run',core:"3 Rounds\n1 Min. Stability Ball Bridges\n30 Sec. Rest"},{label:"Tag 2",warmup:"3 Rounds: 10 Squats, 10 Buttlifts",workout:"a) 5 Rounds: 10-12 Back Squats (heavier than wk1), 2 Min. Rest\nb) 5 Rounds: 10-12 Bench Press, 2 Min. Rest\nc) 6 Rounds: Max Reps Pull Ups, 2 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 3",warmup:"500 m Row, 10 Inch Worm\n2 Rounds: 5 Push Ups, 5 Squats, 10 Sit Ups",workout:"a) 4 Rounds: 50 m Sled Push, 1 Min. Rest\n   4 Rounds: 50 m Sled Pull, 1 Min. Rest\nb) 2000 m Row/Ski Erg\nc) 4 Rounds: 1 Min. Farmers Carry, 1 Min. Rest"},{label:"Tag 4",warmup:"500 m Row\n3 Rounds: 10 Good Mornings",workout:"a) 5 Rounds: 10-12 Deadlifts (heavier than wk1), 2 Min. Rest\nb) 5 Rounds: 10-12 Shoulder Press, 2 Min. Rest\nc) 6 Rounds: 10-12 Plyo Push Ups, 2 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 5",warmup:"4 Rounds: 150 m Run, 20 Sec Rest\n2 Rounds: 250 m Run, 30 Sec Rest",workout:'"JAGGER"\na) 20 Min. AMRAP: 400 m Run, 15 Burpees, 20 Weighted Lunges @ 2xKB – 5 Min. Rest\nb) 20 Min. AMRAP: 400 m Row, 15 Wallballs, 200 m Farmers Carry',core:"5 Rounds\n30 Sec. Toe Touches / Flutter Kicks / Russian Twist / Side Plank each side\n1 Min. Rest"}]},
{week:4,days:[{label:"Tag 1",warmup:"4 Rounds: 250 m Run, 20 Sec Rest\n2 Rounds: 400 m Run, 30 Sec Rest",workout:"FOR TIME – 4 Rounds:\n20 Box Jumps, 20 Lunges, 20 Row for Cal, 20 Sit Ups, 20 Wall Balls",core:"50 Spider Plank Crunch"},{label:"Tag 2",warmup:"500 m Ski Erg / Row",workout:"a) 5 Rounds: 1 Min. Farmers Carry, 1 Min. Rest\nb) 5 Rounds: 1 Min. Max Goblet Squats, 30 Sec. Rest\nc) 5 Rounds: 1 Min. Max Bench Press, 1 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 3",warmup:"2 Min. Jump Rope\n25 m High Knees / Buttkicks / Lunges / Side Lunges",workout:"5 Rounds:\n1 Min. Wall Balls, 30 Sec. Rest\n1 Min. Burpee Broad Jump, 30 Sec. Rest\n1 Min. Row for Calories, 30 Sec. Rest\n1 Min. 10 m Shuttle Run, 30 Sec. Rest",core:"4 Rounds\n15 Hanging Knee Raises\n20 Situps\n15 Hyperextensions"},{label:"Tag 4",warmup:"400 m Easy Run\n10 m Inch Worm\n20 Russian Twist\n25 m Easy Sled Push/Pull",workout:"a) 5 Rounds: 50 m Sled Push AHAP, 3-5 Min. Rest\nb) 5 Rounds: 50 m Sled Pull AHAP, 3-5 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 5",warmup:"50 Jumping Jacks\n10 Tuck Jumps\n20 Lunges",workout:'"MITCHELL" FOR TIME\n800 m Run, 100 Squats\n800 m Run, 100 Sit Ups\n800 m Run, 100 Lunges',core:"3 Rounds\n10 Bird Dogs r/l\n30 Sec. Plank / Side Plank (each side)\n10 Glute Bridges"}]},
{week:5,days:[{label:"Tag 1",warmup:"4 Rounds: 200 m Run, 30 Sec Rest",workout:"FOR TIME\n8000 m Run*\n*every 3 Min. perform 5 Burpees and 10 Squats",core:"1 Round\n50 Situps\n50 Supermen\n1 Min. Plank hold"},{label:"Tag 2",warmup:"3 Rounds: 10 Squats, 10 Buttlifts",workout:"a) 5 Rounds: 8-10 Back Squats (heavier than wk3), 2 Min. Rest\nb) 5 Rounds: 8-10 Bench Press, 2 Min. Rest\nc) 7 Rounds: Max Reps Pull Ups, 2 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 3",warmup:"25 m Lunges / Side Lunges / Broad Jumps / Inch Worm",workout:'"STARR" FOR TIME\n1600 m Run\n30 Mountain Climber\n1200 m Ski Erg\n30 Weighted Lunges @ 2x KB\n800 m Run\n30 Goblet Squats @ KB\n600 m Ski Erg\n30 Wall Balls'},{label:"Tag 4",warmup:"500 m Row\n3 Rounds: 10 Good Mornings",workout:"a) 5 Rounds: 8-10 Deadlifts (heavier than wk3), 2 Min. Rest\nb) 5 Rounds: 8-10 Shoulder Press, 2 Min. Rest\nc) 7 Rounds: 8-10 Plyo Push Ups, 2 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 5",warmup:"50 Jumping Jacks\n10 Tuck Jumps\n20 Lunges",workout:"FOR TIME – 7 Rounds:\n500 m Ski Erg @ 75%\n3 Min. Rest",core:"3 Rounds\n10 Bird Dogs r/l\n30 Sec. Plank / Side Plank (each side)\n10 Glute Bridges"}]},
{week:6,days:[{label:"Tag 1",warmup:"4 Rounds: 150 m Run, 20 Sec Rest\n2 Rounds: 250 m Run, 30 Sec Rest",workout:"FOR TIME\n2000 m Run, then\n80-60-40: Sandbag Lunges, Single Leg Deadlift, Mountain Climbers, then\n2000 m Ski Erg",core:"3 Rounds\n30 Sec. Plank / Side Plank (each side)"},{label:"Tag 2",warmup:"10 Min. Easy Run\n3 Rounds: 10 Step Ups on box, 5 Burpees",workout:"a) 5 Rounds: 8 Front Rack Lunges AHAP, 3-5 Min. Rest\nb) 5 Rounds: 10 Hamstring Curls, 90 Sec. Rest\nc) 5 Rounds: 10 Abductor/Adductor Machine, 90 Sec. Rest",core:"10 Min. Foam Roller"},{label:"Tag 3",warmup:"1500 m Row @ 60%",workout:"FOR TIME\n150 Wall Balls\n4 Min. Rest, then\n100 Burpees",core:"5 Rounds\n15 Hanging Knee Raises\n20 Sit Ups\n15 Hyperextensions"},{label:"Tag 4",rest:"ACTIVE RECOVERY\n60 Min. Bike Ride"},{label:"Tag 5",warmup:"5 Min. Easy Jog\n10 Burpees\n10 Box Jumps\n10 V-Ups",workout:"a) 5 Rounds: 10 Bench Press, 10 Deadlift, 10 Back Squats, 2 Min. Rest\nb) FOR TIME – 3 Rounds: 500 m Ski Erg or Row, 50 Weighted Step over Box, 50 Push Ups"}]},
{week:7,days:[{label:"Tag 1",warmup:"25 m Bear Crawl / Crab Walk / Inch Worm",workout:"FOR TIME – 5 Rounds:\n1000 m Run\n5 Min. Ski Erg for Cal\n5 Min. Row for Cal\n3 Min. Rest",core:"50 V-Ups\n50 Supermen"},{label:"Tag 2",warmup:"3 Rounds: 10 Squats, 10 Buttlifts",workout:"a) 5 Rounds: 6-8 Back Squats (heavier than wk5), 2 Min. Rest\nb) 5 Rounds: 6-8 Bench Press, 2 Min. Rest\nc) 5 Rounds: Max Reps Weighted Pull Ups, 2 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 3",warmup:"2 Min. Jump Rope\n25 m High Knees / Buttkicks / Lunges / Side Lunges",workout:"FOR TIME – 4 Rounds:\n400 m Row\n25 m Sled Push\n25 m Sled Pull"},{label:"Tag 4",warmup:"500m Row\n3 Rounds: 10 Good Mornings, 10 Sit Ups",workout:"a) 5 Rounds: 8-10 Deadlifts (heavier than wk5), 2 Min. Rest\nb) 5 Rounds: 8-10 Shoulder Press, 2 Min. Rest\nc) 7 Rounds: 8-10 Plyo Push Ups, 2 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 5",rest:"ACTIVE RECOVERY\n30 Min. Swimming or 60 Min. Bike Ride"}]},
{week:8,days:[{label:"Tag 1",warmup:"5 Min. Jump Rope",workout:"a) 10 Min. AMRAP: 10 Burpees, 10 Goblet Squats – 5 Min. Rest\nb) 10 Min. AMRAP: 10 Box Jumps, 10 Push Ups – 5 Min. Rest\nc) 10 Min. AMRAP: 10 Lunges, 10 Wallballs",core:"3 Rounds\n20 Russian Twist\n30 Sec. Rest"},{label:"Tag 2",warmup:"400 m Easy Run\n10 m Inch Worm\n20 Russian Twist\n25 m Easy Sled Push/Pull",workout:"a) 5 Rounds: 50 m Sled Push AHAP, 3-5 Min. Rest\nb) 5 Rounds: 50 m Sled Pull AHAP, 3-5 Min. Rest",core:"10 Min. Foam Roller"},{label:"Tag 3",warmup:"25 m High Knees / Buttkicks / Lunges / Side Lunges",workout:"30 Min. AMRAP\n15 Deadlift\n1000 m Row\n15 Back Squats\n1000 m Run"},{label:"Tag 4",rest:"ACTIVE RECOVERY\n20 Min. Easy Row\n20 Min. Mobility / Stretching"},{label:"Tag 5",rest:"TOTAL REST"}]}
]
};

var hyroxState=JSON.parse(localStorage.getItem('hyrox_v2')||'{}');
var hyroxCurrentPlan='standard';

function hyroxKey(plan,w,d){return plan+'_w'+w+'_d'+d}

function hyroxUpdateProgress(){
  var plan=hyroxPlans[hyroxCurrentPlan];
  var total=0,done=0;
  plan.forEach(function(wk,wi){
    wk.days.forEach(function(d,di){if(!d.rest){total++;if(hyroxState[hyroxKey(hyroxCurrentPlan,wi,di)])done++}});
    var card=document.querySelector('[data-hxwk="'+hyroxCurrentPlan+'-'+wi+'"]');
    if(card){
      var dotEls=card.querySelectorAll('.hx2-dot');
      var dotIdx=0;
      wk.days.forEach(function(d,di){
        if(d.rest)return;
        var dot=dotEls[dotIdx];dotIdx++;
        if(dot)dot.style.background=hyroxState[hyroxKey(hyroxCurrentPlan,wi,di)]?'var(--gold)':'var(--bg4)';
      });
      var wDone=wk.days.filter(function(d,di){return !d.rest&&hyroxState[hyroxKey(hyroxCurrentPlan,wi,di)]}).length;
      var wTotal=wk.days.filter(function(d){return !d.rest}).length;
      card.classList.toggle('hx2-complete',wDone===wTotal);
    }
  });
  var pct=total?Math.round(done/total*100):0;
  var f=document.getElementById('hxProgFill2');if(f)f.style.width=pct+'%';
  var l=document.getElementById('hxProgLabel2');if(l)l.textContent=done+' / '+total;
}

function hyroxToggleDay(plan,w,d){
  var key=hyroxKey(plan,w,d);
  var wkData=hyroxPlans[plan][w];
  var day=wkData.days[d];
  if(day.rest)return;
  if(hyroxState[key]){
    hyroxState[key]=false;
    localStorage.setItem('hyrox_v2',JSON.stringify(hyroxState));
    hyroxUpdateProgress();
    var row=document.querySelector('[data-hxday2="'+key+'"]');
    if(row)row.classList.remove('hx2-ticked');
    return;
  }
  var mc=document.getElementById('modal-content');
  mc.innerHTML='<h2>⚡ Log Hyrox Session</h2><div class="modal-sub">Week '+wkData.week+' · '+day.label+'</div><div class="field"><label>Date completed</label><input id="m-hxdate" type="date" value="'+localDateKey(new Date())+'"></div><div class="modal-btns"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn btn-accent" onclick="hyroxConfirmLog(\''+plan+'\','+w+','+d+')">Log ✓</button></div>';
  document.getElementById('modal').style.display='flex';
}
function hyroxConfirmLog(plan,w,d){
  var key=hyroxKey(plan,w,d);
  var wkData=hyroxPlans[plan][w];
  var day=wkData.days[d];
  var date=(document.getElementById('m-hxdate')||{}).value||localDateKey(new Date());
  hyroxState[key]=true;
  localStorage.setItem('hyrox_v2',JSON.stringify(hyroxState));
  var sess={id:g(),name:'Hyrox W'+wkData.week+' '+day.label,date:date,muscleGroups:['Hyrox'],exercises:[]};
  if(!STATE.workouts)STATE.workouts=[];
  STATE.workouts.push(sess);
  saveState();
  closeModal();
  hyroxUpdateProgress();
  var row=document.querySelector('[data-hxday2="'+key+'"]');
  if(row)row.classList.add('hx2-ticked');
  renderWorkout();
}

function hyroxToggleExpand(plan,w,d){
  var row=document.querySelector('[data-hxday2="'+hyroxKey(plan,w,d)+'"]');
  if(row)row.classList.toggle('hx2-expanded');
}

function hyroxResetAll(){
  if(!confirm('Reset all Hyrox progress?'))return;
  hyroxState={};localStorage.setItem('hyrox_v2',JSON.stringify(hyroxState));
  document.querySelectorAll('.hx2-day-row').forEach(function(r){r.classList.remove('hx2-ticked','hx2-expanded')});
  hyroxUpdateProgress();
}

function hyroxSwitchPlan(plan,btn){
  hyroxCurrentPlan=plan;
  document.querySelectorAll('.filter-btn').forEach(function(b){if(b.id==='hxPlanBtn1'||b.id==='hxPlanBtn2')b.classList.remove('active')});
  btn.classList.add('active');
  var s=document.getElementById('hxWeeksStandard');
  var p=document.getElementById('hxWeeksPro');
  if(s)s.style.display=plan==='standard'?'flex':'none';
  if(p)p.style.display=plan==='pro'?'flex':'none';
  hyroxUpdateProgress();
}

function hyroxSection(label,text){
  if(!text)return'';
  return'<div style="font-size:9px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:var(--gold);margin:10px 0 4px">'+label+'</div><div style="font-size:12px;line-height:1.8;color:var(--text2);white-space:pre-line">'+text+'</div>';
}

function hyroxRenderPlan(planKey){
  var cid=planKey==='standard'?'hxWeeksStandard':'hxWeeksPro';
  var container=document.getElementById(cid);
  if(!container)return;
  container.innerHTML='';
  hyroxPlans[planKey].forEach(function(wkData,wi){
    var card=document.createElement('div');
    card.style.cssText='background:var(--bg2);border:1px solid var(--border);border-radius:var(--radius);overflow:hidden;transition:border-color .2s';
    card.dataset.hxwk=planKey+'-'+wi;
    /* Count completed days for this week */
    var totalDays=0;var doneDays=0;
    wkData.days.forEach(function(d,di){if(!d.rest){totalDays++;if(hyroxState[hyroxKey(planKey,wi,di)])doneDays++}});
    var weekPct=totalDays>0?Math.round(doneDays/totalDays*100):0;
    var dots=wkData.days.map(function(d,di){
      if(d.rest)return '';
      return '<div style="width:10px;height:10px;border-radius:50%;background:'+(hyroxState[hyroxKey(planKey,wi,di)]?'var(--gold)':'var(--bg4)')+';transition:background .2s"></div>';
    }).join('');
    /* Week header */
    card.innerHTML='<div style="padding:14px 20px;background:var(--bg3);display:flex;align-items:center;justify-content:space-between;cursor:pointer;user-select:none;gap:12px" onclick="this.parentElement.classList.toggle(\'hx2-open\');this.querySelector(\'.hx2-chev\').textContent=this.parentElement.classList.contains(\'hx2-open\')?\'▲\':\'▼\';this.parentElement.querySelector(\'.hx2-days\').style.display=this.parentElement.classList.contains(\'hx2-open\')?\'grid\':\'none\'">'
      +'<div style="display:flex;align-items:center;gap:12px"><div style="font-family:var(--serif);font-size:18px;font-weight:600;color:var(--warm-brown)">Week '+wkData.week+'</div><div style="display:flex;gap:4px">'+dots+'</div></div>'
      +'<div style="display:flex;align-items:center;gap:12px"><span style="font-size:11px;font-weight:600;color:'+(weekPct>=100?'var(--mint)':'var(--text3)')+'">'+doneDays+'/'+totalDays+'</span><div class="hx2-chev" style="font-size:10px;color:var(--text3)">▼</div></div>'
      +'</div>'
      +'<div class="hx2-days" style="display:none;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:0"></div>';
    var dc=card.querySelector('.hx2-days');
    wkData.days.forEach(function(day,di){
      var key=hyroxKey(planKey,wi,di);
      var row=document.createElement('div');
      row.className='hx2-day-row'+(hyroxState[key]?' hx2-ticked':'');
      row.dataset.hxday2=key;
      row.style.cssText='border-top:1px solid var(--border);border-right:1px solid var(--border);transition:background .15s';
      var isRest=!!day.rest;
      if(isRest){
        row.innerHTML='<div style="padding:12px 20px;display:flex;align-items:center;gap:8px"><span style="font-size:12px;font-weight:600;color:var(--text3)">'+day.label+'</span><span style="font-size:10px;color:var(--text3)">— Rest</span></div>';
      }else{
        var content='<div class="hx2-content" style="padding:0 20px 14px">'+hyroxSection('Warm Up',day.warmup)+hyroxSection('Workout',day.workout)+(day.core?hyroxSection('Core',day.core):'')+'</div>';
        var tickBtn='<button style="width:22px;height:22px;border-radius:50%;border:1.5px solid var(--border2);background:none;cursor:pointer;display:flex;align-items:center;justify-content:center;font-size:11px;color:transparent;flex-shrink:0;transition:all .2s;font-family:var(--sans)" onclick="event.stopPropagation();hyroxToggleDay(\''+planKey+'\','+wi+','+di+')">✓</button>';
        row.innerHTML='<div style="display:flex;align-items:center;justify-content:space-between;padding:12px 20px;cursor:pointer" onclick="hyroxToggleExpand(\''+planKey+'\','+wi+','+di+')">'
          +'<div class="hx2-label" style="font-size:13px;font-weight:600;color:var(--text)">'+day.label+'</div>'
          +tickBtn
          +'</div>'+content;
        /* Start with content visible so days are scannable */
        row.classList.add('hx2-expanded');
      }
      dc.appendChild(row);
    });
    container.appendChild(card);
  });

  /* Style ticked rows & tick buttons */
  document.querySelectorAll('.hx2-day-row').forEach(function(row){
    var key=row.dataset.hxday2;if(!key)return;
    var btn=row.querySelector('button');
    if(hyroxState[key]){
      row.style.background='rgba(201,151,58,0.06)';
      var label=row.querySelector('.hx2-label');if(label)label.style.color='var(--gold)';
      if(btn){btn.style.background='var(--gold)';btn.style.borderColor='var(--gold)';btn.style.color='var(--bg2)'}
    }
  });
}

// Watch for ticked state changes to update tick button styles
var _hxTickObserver=new MutationObserver(function(muts){
  muts.forEach(function(m){
    var row=m.target;
    var btn=row.querySelector('button');
    var label=row.querySelector('.hx2-label');
    if(row.classList.contains('hx2-ticked')){
      row.style.background='rgba(201,151,58,0.06)';
      if(label)label.style.color='var(--gold)';
      if(btn){btn.style.background='var(--gold)';btn.style.borderColor='var(--gold)';btn.style.color='var(--bg2)'}
    } else {
      row.style.background='';
      if(label)label.style.color='var(--text)';
      if(btn){btn.style.background='none';btn.style.borderColor='var(--border2)';btn.style.color='transparent'}
    }
    var content=row.querySelector('.hx2-content');
    if(content)content.style.display=row.classList.contains('hx2-expanded')?'block':'none';
  });
});

function hyroxExpandObserve(){
  document.querySelectorAll('.hx2-day-row').forEach(function(row){
    _hxTickObserver.observe(row,{attributes:true,attributeFilter:['class']});
    row.addEventListener('click',function(){
      var content=row.querySelector('.hx2-content');
      if(content)content.style.display=row.classList.contains('hx2-expanded')?'block':'none';
    });
  });
}

hyroxRenderPlan('standard');
hyroxRenderPlan('pro');
hyroxUpdateProgress();
setTimeout(hyroxExpandObserve,100);

