// PROJECTS
// ============================================================
var projFilter='all';
function renderProjects(){var all=STATE.projects||[];var filtered=projFilter==='all'?all:all.filter(function(p){return p.status===projFilter});var el=document.getElementById('projects-container');if(!el)return;if(!filtered.length){el.innerHTML='<div class="empty"><div class="empty-icon">&#128193;</div>No projects yet. Add one!</div>';return}var statusColors={active:'var(--accent)',paused:'var(--amber)',done:'var(--mint)'};el.innerHTML=filtered.map(function(proj){var taskDone=(proj.tasks||[]).filter(function(t){return t.done}).length;var taskTotal=(proj.tasks||[]).length;var p=taskTotal>0?Math.round(taskDone/taskTotal*100):0;var dl=proj.deadline?Math.ceil((new Date(proj.deadline)-new Date())/86400000):null;return '<div class="card" style="margin-bottom:12px;border-left:4px solid '+(proj.color||'var(--accent)')+'"><div style="display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:10px"><div style="flex:1"><div style="display:flex;gap:8px;align-items:center;margin-bottom:5px"><span style="padding:3px 10px;border-radius:20px;font-size:11px;font-weight:600;background:'+(statusColors[proj.status]||'var(--accent)')+';color:#fff">'+(proj.status||'active')+'</span>'+(dl!==null?'<span style="font-size:11px;color:var(--text3)">'+fmtDate(proj.deadline)+' &#183; '+(dl>0?dl+' days':'Overdue')+'</span>':'')+'</div><div style="font-size:14px;font-weight:600">'+proj.name+'</div>'+(proj.desc?'<div style="font-size:12px;color:var(--text2);margin-top:2px">'+proj.desc+'</div>':'')+'</div><div style="display:flex;gap:4px"><button class="btn btn-sm btn-ghost" onclick="openModal(\'editProject\',\''+proj.id+'\')">Edit</button><button class="btn btn-sm btn-danger" onclick="confirmDelete(\'Delete project?\',function(){deleteProject(\''+proj.id+'\')})">&#215;</button></div></div>'+(taskTotal>0?'<div style="display:flex;align-items:center;gap:10px;margin-bottom:10px"><div class="pbar-wrap" style="flex:1"><div class="pbar" style="width:'+p+'%;background:'+(proj.color||'var(--accent)')+'"></div></div><span style="font-size:12px;color:var(--text3)">'+taskDone+'/'+taskTotal+'</span></div>':'')+(proj.tasks||[]).map(function(t){return '<div style="display:flex;align-items:center;gap:8px;padding:6px 12px;background:var(--cream);border-radius:8px;margin-top:4px"><div class="sub-goal-check '+(t.done?'done':'')+'" onclick="toggleProjectTask(\''+proj.id+'\',\''+t.id+'\')"></div><span style="flex:1;font-size:13px;'+(t.done?'text-decoration:line-through;color:var(--text3)':'')+'">'+t.text+'</span><button style="background:none;border:none;cursor:pointer;color:var(--text3);font-size:14px;padding:0 2px" onclick="deleteProjectTask(\''+proj.id+'\',\''+t.id+'\')">&#215;</button></div>'}).join('')+'<button class="add-sub" onclick="openModal(\'addProjectTask\',\''+proj.id+'\')">+ Add task</button></div>'}).join('')}
function filterProjects(s,btn){projFilter=s;document.querySelectorAll('#project-filters .filter-btn').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');renderProjects()}
function deleteProject(id){STATE.projects=(STATE.projects||[]).filter(function(p){return p.id!==id});saveState();renderProjects()}
function toggleProjectTask(pid,tid){var p=(STATE.projects||[]).find(function(x){return x.id===pid});if(!p)return;var t=(p.tasks||[]).find(function(x){return x.id===tid});if(t)t.done=!t.done;saveState();renderProjects()}
function deleteProjectTask(pid,tid){var p=(STATE.projects||[]).find(function(x){return x.id===pid});if(!p)return;p.tasks=(p.tasks||[]).filter(function(t){return t.id!==tid});saveState();renderProjects()}
function saveProject(){var name=((document.getElementById('m-pname')||{}).value||'').trim();if(!name)return;var cat=(document.getElementById('m-pcat')||{}).value||'Personal';var colors={Career:'#d4845a',Personal:'#6b9e7a',Finance:'#c9973a',Fitness:'#9b7b8a'};if(!STATE.projects)STATE.projects=[];STATE.projects.push({id:g(),name:name,status:(document.getElementById('m-pstatus')||{}).value||'active',cat:cat,desc:(document.getElementById('m-pdesc')||{}).value||'',deadline:(document.getElementById('m-pdeadline')||{}).value||'',tasks:[],color:colors[cat]||'var(--accent)'});saveState();closeModal();renderProjects()}
function updateProject(id){var p=(STATE.projects||[]).find(function(x){return x.id===id});if(!p)return;p.name=(document.getElementById('m-pname')||{}).value||p.name;p.status=(document.getElementById('m-pstatus')||{}).value||p.status;p.desc=(document.getElementById('m-pdesc')||{}).value||'';p.deadline=(document.getElementById('m-pdeadline')||{}).value||'';saveState();closeModal();renderProjects()}
function saveProjectTask(pid){var text=((document.getElementById('m-ptask')||{}).value||'').trim();if(!text)return;var p=(STATE.projects||[]).find(function(x){return x.id===pid});if(!p)return;if(!p.tasks)p.tasks=[];p.tasks.push({id:g(),text:text,done:false});saveState();closeModal();renderProjects()}

