// RELATIONSHIPS
// ============================================================
var relFilter='all';
function renderRelationships(){var all=STATE.relationships||[];var filtered=relFilter==='all'?all:all.filter(function(r){return r.cat===relFilter});var el=document.getElementById('relationships-container');if(!el)return;if(!filtered.length){el.innerHTML='<div class="empty"><div class="empty-icon">&#129400;</div>No people added yet</div>';return}el.innerHTML=filtered.map(function(r){var daysSince=r.lastContact?Math.floor((new Date()-new Date(r.lastContact))/86400000):999;var overdue=daysSince>=r.freq;var urgency=overdue?'var(--red)':daysSince>=r.freq*0.75?'var(--amber)':'var(--mint)';return '<div class="card" style="margin-bottom:10px;border-left:4px solid '+(r.color||'var(--tan)')+'"><div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap"><span style="font-size:26px">'+(r.icon||'&#128100;')+'</span><div style="flex:1"><div style="font-size:14px;font-weight:600">'+r.name+'</div><div style="font-size:12px;color:var(--text2)">'+r.cat+' &#183; Check in every '+r.freq+' days'+(r.note?' &#183; '+r.note:'')+'</div><div style="font-size:12px;color:'+urgency+';margin-top:2px;font-weight:500">'+(overdue?'&#9888;&#65039; Overdue &#8212; ':'Last contact ')+(daysSince===999?'never':daysSince+' days ago')+'</div></div><div style="display:flex;gap:6px"><button class="btn btn-sm btn-accent" onclick="logContact(\''+r.id+'\')">Log &#10003;</button><button class="btn btn-sm btn-ghost" onclick="openModal(\'editRelationship\',\''+r.id+'\')">Edit</button><button class="btn btn-sm btn-danger" onclick="confirmDelete(\'Remove?\',function(){deleteRelationship(\''+r.id+'\')})">&#215;</button></div></div></div>'}).join('')}
function filterRel(cat,btn){relFilter=cat;document.querySelectorAll('#rel-filters .filter-btn').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');renderRelationships()}
function logContact(id){var r=(STATE.relationships||[]).find(function(x){return x.id===id});if(!r)return;r.lastContact=localDateKey(new Date());saveState();renderRelationships();renderDashboardRelationships()}
function deleteRelationship(id){STATE.relationships=(STATE.relationships||[]).filter(function(r){return r.id!==id});saveState();renderRelationships()}
function saveRelationship(){var name=((document.getElementById('m-rname')||{}).value||'').trim();if(!name)return;if(!STATE.relationships)STATE.relationships=[];STATE.relationships.push({id:g(),name:name,cat:(document.getElementById('m-rcat')||{}).value||'Friend',freq:Number((document.getElementById('m-rfreq')||{}).value)||14,icon:(document.getElementById('m-ricon')||{}).value||'&#128100;',note:(document.getElementById('m-rnote')||{}).value||'',lastContact:null,color:'#c9973a'});saveState();closeModal();renderRelationships()}
function updateRelationship(id){var r=(STATE.relationships||[]).find(function(x){return x.id===id});if(!r)return;r.name=(document.getElementById('m-rname')||{}).value||r.name;r.icon=(document.getElementById('m-ricon')||{}).value||r.icon;r.freq=Number((document.getElementById('m-rfreq')||{}).value)||r.freq;r.note=(document.getElementById('m-rnote')||{}).value||'';saveState();closeModal();renderRelationships()}
function renderDashboardRelationships(){var relEl=document.getElementById('dash-relationships-preview');if(!relEl)return;var overdue=(STATE.relationships||[]).filter(function(r){if(!r.lastContact)return true;return Math.floor((new Date()-new Date(r.lastContact))/86400000)>=r.freq});relEl.innerHTML=overdue.length?overdue.map(function(r){var daysSince=r.lastContact?Math.floor((new Date()-new Date(r.lastContact))/86400000):999;return '<div style="display:flex;align-items:center;gap:10px;padding:8px 0;border-bottom:1px solid var(--border)"><span style="font-size:18px">'+(r.icon||'&#128100;')+'</span><div style="flex:1"><div style="font-size:12px;font-weight:500">'+r.name+'</div><div style="font-size:11px;color:var(--red)">'+(daysSince===999?'Never contacted':daysSince+' days ago')+'</div></div><button class="btn btn-sm btn-accent" onclick="logContact(\''+r.id+'\')">Log &#10003;</button></div>'}).join('')+'<button class="btn btn-ghost btn-sm" onclick="nav(\'relationships\')" style="margin-top:8px;width:100%;justify-content:center">View all &#8594;</button>':'<div style="font-size:12px;color:var(--text3);text-align:center;padding:12px">All relationships on track!</div><button class="btn btn-ghost btn-sm" onclick="nav(\'relationships\')" style="margin-top:4px;width:100%;justify-content:center">View all &#8594;</button>'}

// WATCHLIST
var watchFilter='all';
function renderWatchlist(){var all=STATE.watchlist||[];var filtered=watchFilter==='all'?all:all.filter(function(i){return i.status===watchFilter||i.type===watchFilter});var el=document.getElementById('watchlist-container');if(!el)return;var statusIcons={want:'&#127871;',watching:'&#9654;&#65039;',done:'&#10003;&#65039;'};var statusLabels={want:'Want to watch',watching:'Watching',done:'Done'};el.innerHTML=filtered.length?'<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:12px">'+filtered.map(function(item){return '<div class="card" style="padding:14px"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:7px"><span style="font-size:18px">'+(statusIcons[item.status]||'&#127916;')+'</span><div style="display:flex;gap:4px"><select onchange="changeWatchStatus(\''+item.id+'\',this.value)" style="font-size:11px;padding:3px 6px;background:var(--bg3);border:1px solid var(--border2);border-radius:6px;color:var(--text);font-family:var(--sans);outline:none">'+Object.keys(statusLabels).map(function(s){return '<option value="'+s+'"'+(item.status===s?' selected':'')+'>'+statusLabels[s]+'</option>'}).join('')+'</select><button class="btn btn-sm btn-danger" onclick="confirmDelete(\'Remove?\',function(){deleteWatchItem(\''+item.id+'\')})">&#215;</button></div></div><div style="font-size:13px;font-weight:600;margin-bottom:3px">'+item.name+'</div><div style="font-size:11px;color:var(--text3)">'+item.type+'</div>'+(item.note?'<div style="font-size:11px;color:var(--text2)">'+item.note+'</div>':'')+'</div>'}).join('')+'</div>':'<div class="empty"><div class="empty-icon">&#127916;</div>Nothing here yet</div>'}
function filterWatch(s,btn){watchFilter=s;document.querySelectorAll('#watch-filters .filter-btn').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');renderWatchlist()}
function changeWatchStatus(id,status){var item=(STATE.watchlist||[]).find(function(x){return x.id===id});if(item)item.status=status;saveState()}
function deleteWatchItem(id){STATE.watchlist=(STATE.watchlist||[]).filter(function(i){return i.id!==id});saveState();renderWatchlist()}
function saveWatchItem(){var name=((document.getElementById('m-wname')||{}).value||'').trim();if(!name)return;if(!STATE.watchlist)STATE.watchlist=[];STATE.watchlist.push({id:g(),name:name,type:(document.getElementById('m-wtype')||{}).value||'Movie',status:(document.getElementById('m-wstatus')||{}).value||'want',note:(document.getElementById('m-wnote')||{}).value||'',rating:0,added:localDateKey(new Date())});saveState();closeModal();renderWatchlist()}

// WISHLIST
var wishFilter='all';
function renderWishlist(){var all=STATE.wishlist||[];var now=new Date();all.forEach(function(item){if(item.status==='waiting'&&item.addedDate){var days=Math.floor((now-new Date(item.addedDate))/86400000);if(days>=30)item.status='approved'}});var filtered=wishFilter==='all'?all:all.filter(function(i){return i.status===wishFilter});var waiting=all.filter(function(i){return i.status==='waiting'}).length;var approved=all.filter(function(i){return i.status==='approved'}).length;var wsEl=document.getElementById('wish-stats');if(wsEl)wsEl.innerHTML='<div class="card-sm"><div style="font-size:11px;color:var(--text3)">Waiting</div><div style="font-size:20px;font-family:var(--serif);color:var(--accent)">'+waiting+'</div></div><div class="card-sm"><div style="font-size:11px;color:var(--text3)">Approved</div><div style="font-size:20px;font-family:var(--serif);color:var(--mint)">'+approved+'</div></div>';var el=document.getElementById('wishlist-container');if(!el)return;var statusMap={waiting:{bg:'#fdf6e8',col:'#8a6000',label:'Waiting'},approved:{bg:'#f0f7f1',col:'#2d6a35',label:'Approved'},purchased:{bg:'#f5f0fb',col:'#5a3a8a',label:'Purchased'}};el.innerHTML=filtered.length?filtered.map(function(item){var daysLeft30=item.addedDate?Math.max(0,30-Math.floor((now-new Date(item.addedDate))/86400000)):30;var s=statusMap[item.status]||statusMap.waiting;return '<div class="card" style="margin-bottom:10px"><div style="display:flex;align-items:flex-start;gap:12px;flex-wrap:wrap"><div style="flex:1"><div style="display:flex;gap:8px;align-items:center;margin-bottom:5px"><span style="padding:3px 10px;border-radius:20px;font-size:11px;font-weight:600;background:'+s.bg+';color:'+s.col+'">'+s.label+'</span>'+(item.cat?'<span style="font-size:11px;color:var(--text3)">'+item.cat+'</span>':'')+'</div><div style="font-size:14px;font-weight:600">'+item.name+'</div>'+(item.price?'<div style="font-size:16px;font-family:var(--serif);color:var(--accent);margin-top:3px">'+fmtMoney(item.price)+'</div>':'')+(item.note?'<div style="font-size:12px;color:var(--text2);margin-top:3px">'+item.note+'</div>':'')+(item.status==='waiting'?'<div style="font-size:12px;color:var(--amber);margin-top:5px;font-weight:500">'+daysLeft30+' days left on waitlist</div>':'')+'</div><div style="display:flex;flex-direction:column;gap:4px">'+(item.status==='approved'?'<button class="btn btn-sm btn-accent" onclick="markWishItem(\''+item.id+'\',\'purchased\')">Buy it</button>':'')+'<button class="btn btn-sm btn-danger" onclick="confirmDelete(\'Remove?\',function(){deleteWishItem(\''+item.id+'\')})">&#215;</button></div></div></div>'}).join(''):'<div class="empty"><div class="empty-icon">&#128717;&#65039;</div>Nothing on your wishlist yet!</div>'}
function filterWish(s,btn){wishFilter=s;document.querySelectorAll('#wish-filters .filter-btn').forEach(function(b){b.classList.remove('active')});btn.classList.add('active');renderWishlist()}
function markWishItem(id,status){var item=(STATE.wishlist||[]).find(function(x){return x.id===id});if(item)item.status=status;saveState();renderWishlist()}
function deleteWishItem(id){STATE.wishlist=(STATE.wishlist||[]).filter(function(i){return i.id!==id});saveState();renderWishlist()}
function saveWishItem(){var name=((document.getElementById('m-wname')||{}).value||'').trim();if(!name)return;if(!STATE.wishlist)STATE.wishlist=[];STATE.wishlist.push({id:g(),name:name,price:Number((document.getElementById('m-wprice')||{}).value)||0,cat:(document.getElementById('m-wcat')||{}).value||'',note:(document.getElementById('m-wnote')||{}).value||'',status:'waiting',addedDate:localDateKey(new Date())});saveState();closeModal();renderWishlist()}


