// WEEKLY PLAN
// ============================================================
var weeklyViewKey=null;
function renderWeeklyPlan(){if(!weeklyViewKey)weeklyViewKey=weekKey(new Date());var wkStart=new Date(weeklyViewKey);var wkEnd=new Date(weeklyViewKey);wkEnd.setDate(wkEnd.getDate()+6);var lEl=document.getElementById('weekly-week-label');if(lEl)lEl.textContent=fmtDate(wkStart.toISOString())+' \u2013 '+fmtDate(wkEnd.toISOString());var plan=(STATE.weeklyPlans||{})[weeklyViewKey]||{};var days=weekDays(weeklyViewKey);var dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];var todayKey=new Date().toISOString().slice(0,10);var moodEm=['','😞','😐','🙂','😊','🤩'];var energyEm=['','🧟','😴','⚡','🔥','🚀'];

/* Week stats */
var wkWorkouts=(STATE.workouts||[]).filter(function(w){return days.indexOf(w.date)!==-1});
var gymCount=wkWorkouts.filter(function(w){return !(w.muscleGroups&&w.muscleGroups.indexOf('Hyrox')!==-1)}).length;
var hyroxCount=wkWorkouts.filter(function(w){return w.muscleGroups&&w.muscleGroups.indexOf('Hyrox')!==-1}).length;
var wkRuns=((STATE.metrics||{}).run||[]).filter(function(r){return days.indexOf(r.date)!==-1});
var wkRunKm=wkRuns.reduce(function(s,r){return s+Number(r.distance||0)},0);
var moodDays=days.filter(function(d){return (STATE.mood||{})[d]&&(STATE.mood||{})[d].mood});
var avgMood=moodDays.length?(moodDays.reduce(function(s,d){return s+Number((STATE.mood||{})[d].mood)},0)/moodDays.length):0;
var habitsDone=0;var habitsTotal=0;(STATE.habits||[]).forEach(function(h){days.forEach(function(d){habitsTotal++;if(h.log&&h.log[d])habitsDone++})});
var statsEl=document.getElementById('weekly-stats-row');
if(statsEl)statsEl.innerHTML='<div class="card-sm" style="text-align:center;border-top:3px solid var(--accent)"><div style="font-size:22px;font-family:var(--serif);font-weight:600;color:var(--accent)">'+gymCount+'</div><div style="font-size:11px;color:var(--text2)">gym sessions</div></div>'+'<div class="card-sm" style="text-align:center;border-top:3px solid var(--gold)"><div style="font-size:22px;font-family:var(--serif);font-weight:600;color:var(--gold)">'+hyroxCount+'</div><div style="font-size:11px;color:var(--text2)">hyrox sessions</div></div>'+'<div class="card-sm" style="text-align:center;border-top:3px solid var(--teal)"><div style="font-size:22px;font-family:var(--serif);font-weight:600;color:var(--teal)">'+wkRunKm.toFixed(1)+'</div><div style="font-size:11px;color:var(--text2)">km run ('+wkRuns.length+')</div></div>'+'<div class="card-sm" style="text-align:center;border-top:3px solid #8b5cf6"><div style="font-size:22px;font-family:var(--serif);font-weight:600;color:#8b5cf6">'+(avgMood?avgMood.toFixed(1):'—')+'</div><div style="font-size:11px;color:var(--text2)">avg mood ('+moodDays.length+'/7)</div></div>'+'<div class="card-sm" style="text-align:center;border-top:3px solid #ec4899"><div style="font-size:22px;font-family:var(--serif);font-weight:600;color:#ec4899">'+habitsDone+'/'+habitsTotal+'</div><div style="font-size:11px;color:var(--text2)">habits done</div></div>';

/* Priorities */
var pEl=document.getElementById('weekly-priorities');if(pEl)pEl.innerHTML=[0,1,2].map(function(i){var val=((plan.priorities||[])[i])||'';return '<div style="display:flex;align-items:center;gap:8px;margin-bottom:8px"><span style="width:20px;height:20px;border-radius:50%;background:var(--accent);color:#fff;font-size:11px;font-weight:700;display:flex;align-items:center;justify-content:center;flex-shrink:0">'+(i+1)+'</span><input type="text" value="'+val.replace(/"/g,'&quot;')+'" placeholder="Priority '+(i+1)+'..." id="wp-p'+i+'" style="flex:1;padding:8px 10px;background:var(--bg3);border:1.5px solid var(--border2);border-radius:var(--radius-sm);color:var(--text);font-family:var(--sans);font-size:13px;outline:none"></div>'}).join('');
var iEl=document.getElementById('weekly-intention');if(iEl)iEl.value=plan.intention||'';
var rEl=document.getElementById('weekly-reflection');if(rEl)rEl.value=plan.reflection||'';

/* Week activity timeline — shows what actually happened each day */
var atEl=document.getElementById('weekly-activity-timeline');
if(atEl){var atHtml='<div class="weekly-7grid">';
days.forEach(function(d,i){var isToday=d===todayKey;var isPast=d<todayKey;var dayWorkouts=(STATE.workouts||[]).filter(function(w){return w.date===d});var dayRuns=((STATE.metrics||{}).run||[]).filter(function(r){return r.date===d});var m=(STATE.mood||{})[d]||{};var hasActivity=dayWorkouts.length||dayRuns.length;
atHtml+='<div style="background:'+(isToday?'var(--accent-dim)':'var(--bg3)')+';border:1.5px solid '+(isToday?'var(--accent)':'var(--border)')+';border-radius:var(--radius-sm);padding:10px 8px;text-align:center;min-height:100px">';
atHtml+='<div style="font-size:11px;font-weight:600;color:'+(isToday?'var(--accent)':'var(--text2)')+'">'+dayNames[i]+'</div>';
atHtml+='<div style="font-size:10px;color:var(--text3);margin-bottom:6px">'+new Date(d+'T12:00:00').getDate()+'</div>';
if(dayWorkouts.length){dayWorkouts.forEach(function(w){var isH=w.muscleGroups&&w.muscleGroups.indexOf('Hyrox')!==-1;atHtml+='<div style="padding:3px 6px;border-radius:6px;font-size:10px;font-weight:600;margin-bottom:3px;background:'+(isH?'var(--gold-dim);color:var(--gold)':'var(--accent-dim);color:var(--accent)')+'">'+(isH?'⚡ Hyrox':'🏋️ Gym')+'</div>'})}
if(dayRuns.length){dayRuns.forEach(function(r){atHtml+='<div style="padding:3px 6px;border-radius:6px;font-size:10px;font-weight:600;margin-bottom:3px;background:rgba(95,158,160,0.15);color:var(--teal)">🏃 '+r.distance+'km</div>'})}
if(!hasActivity&&isPast){atHtml+='<div style="font-size:10px;color:var(--text3);margin-top:8px">Rest day</div>'}
if(!hasActivity&&!isPast&&!isToday){atHtml+='<div style="font-size:10px;color:var(--text3);margin-top:8px">—</div>'}
if(!hasActivity&&isToday){atHtml+='<div style="font-size:10px;color:var(--accent);margin-top:8px">Today</div>'}
atHtml+='</div>'});
atHtml+='</div>';atEl.innerHTML=atHtml}

/* Mood check-in */
var cgEl=document.getElementById('daily-checkin-grid');if(cgEl)cgEl.innerHTML='<div class="weekly-7grid">'+days.map(function(d,i){var m=(STATE.mood||{})[d]||{};var isToday=d===todayKey;return '<div style="background:'+(isToday?'var(--accent-dim)':'var(--bg3)')+';border:1.5px solid '+(isToday?'var(--accent)':'var(--border)')+';border-radius:var(--radius-sm);padding:10px 6px;text-align:center;cursor:pointer;transition:transform .15s" onclick="openModal(\'logMood\',\''+d+'\')" onmouseenter="this.style.transform=\'scale(1.03)\'" onmouseleave="this.style.transform=\'scale(1)\'"><div style="font-size:11px;font-weight:600;color:'+(isToday?'var(--accent)':'var(--text2)')+'">'+dayNames[i]+'</div><div style="font-size:10px;color:var(--text3)">'+new Date(d+'T12:00:00').getDate()+'</div><div style="font-size:22px;margin-top:4px">'+(m.mood?moodEm[m.mood]:'·')+'</div><div style="font-size:16px;margin-top:2px">'+(m.energy?energyEm[m.energy]:'')+'</div>'+(m.sleep?'<div style="font-size:10px;color:var(--text3);margin-top:2px">💤 '+m.sleep+'h</div>':'')+(m.water?'<div style="font-size:10px;color:var(--teal);margin-top:1px">� '+m.water+'L</div>':'')+'</div>'}).join('')+'</div>';t

/* Habit snapshot */
var hsEl=document.getElementById('weekly-habit-snapshot');
if(hsEl){var habits=STATE.habits||[];if(habits.length){var hsHtml='<div style="overflow-x:auto;-webkit-overflow-scrolling:touch"><div style="display:grid;grid-template-columns:minmax(100px,1fr) repeat(7,32px);gap:4px;align-items:center;font-size:12px;min-width:360px">';hsHtml+='<div style="font-weight:600;color:var(--text2)"></div>'+dayNames.map(function(dn){return '<div style="text-align:center;font-weight:600;color:var(--text3);font-size:10px">'+dn+'</div>'}).join('');habits.forEach(function(h){hsHtml+='<div style="font-size:12px;color:var(--text);white-space:nowrap;overflow:hidden;text-overflow:ellipsis">'+(h.icon||'')+' '+h.name+'</div>';days.forEach(function(d){var done=h.logs&&h.logs[d];hsHtml+='<div style="text-align:center"><span style="display:inline-block;width:22px;height:22px;border-radius:50%;line-height:22px;font-size:12px;'+(done?'background:var(--accent);color:#fff':'background:var(--bg3);color:var(--text3);border:1.5px solid var(--border2)')+'">'+( done?'✓':'')+'</span></div>'})});hsHtml+='</div></div>';hsEl.innerHTML=hsHtml}else{hsEl.innerHTML='<div style="font-size:13px;color:var(--text3);padding:12px 0;text-align:center">No habits set up yet</div>'}}

/* Goals needing attention */
/* Roadmap items due this week */
var rdEl=document.getElementById('weekly-roadmap-due');
if(rdEl){var dueItems=[];var dueDates=STATE.roadmapDueDates||{};
/* Check built-in items with due dates */
RM_MONTHS.forEach(function(m){m.sections.forEach(function(sec,si){sec.items.forEach(function(item,ii){var k=rmKey(m.id,si,ii);if((STATE.roadmapHidden||{})[k])return;var done=rmIsDone(m.id,si,ii);if(done)return;var dd=dueDates[k];if(!dd)return;if(dd>=days[0]&&dd<=days[6]){var it=rmGetItemText(m.id,si,ii);dueItems.push({text:it.text,dueDate:dd,section:sec.label,month:m.name,key:k,type:'builtin',mid:m.id,si:si,ii:ii})}})})});
/* Check added items with due dates */
(STATE.roadmapAdded||[]).forEach(function(a){if((STATE.roadmapChecklist||{})[a.id])return;if(!a.dueDate)return;if(a.dueDate>=days[0]&&a.dueDate<=days[6]){dueItems.push({text:a.text,dueDate:a.dueDate,section:'',month:'',key:a.id,type:'added'})}});
dueItems.sort(function(a,b){return a.dueDate.localeCompare(b.dueDate)});
if(dueItems.length){rdEl.innerHTML=dueItems.map(function(di){var dl2=Math.ceil((new Date(di.dueDate)-new Date())/86400000);var urgency=dl2<0?'var(--red)':dl2<=2?'var(--amber)':'var(--teal)';return '<div style="display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid var(--border)"><div style="width:6px;height:6px;border-radius:50%;background:'+urgency+';flex-shrink:0"></div><div style="flex:1"><div style="font-size:13px;font-weight:500">'+di.text+'</div>'+(di.section?'<div style="font-size:10px;color:var(--text3)">'+di.section+' · '+di.month+'</div>':'')+'</div><span style="font-size:11px;font-weight:600;color:'+urgency+';white-space:nowrap">'+fmtDate(di.dueDate)+(dl2<0?' (overdue)':dl2===0?' (today)':dl2===1?' (tomorrow)':'')+'</span></div>'}).join('')}else{rdEl.innerHTML='<div style="font-size:13px;color:var(--text3);padding:12px 0;text-align:center">No roadmap items due this week</div>'}}
var gaEl=document.getElementById('weekly-goals-attention');if(gaEl){var needsWork=(STATE.goals||[]).filter(function(g){var p=goalPct(g);var dl=Math.ceil((new Date(g.deadline)-new Date())/86400000);return p<50&&dl<180&&dl>0});gaEl.innerHTML=needsWork.length?needsWork.map(function(g){var p=goalPct(g);var dl=Math.ceil((new Date(g.deadline)-new Date())/86400000);return '<div style="display:flex;align-items:center;gap:10px;padding:9px 0;border-bottom:1px solid var(--border)"><span class="badge badge-'+g.badge+'">'+g.cat+'</span><div style="flex:1"><div style="font-size:13px;font-weight:500">'+g.name+'</div><div style="font-size:11px;color:var(--text3)">'+p+'% · '+dl+' days left</div></div><button class="btn btn-sm" onclick="openModal(\'updateGoal\',\''+g.id+'\')">Update</button></div>'}).join(''):'<div style="font-size:13px;color:var(--text3);padding:12px 0;text-align:center">All goals on track!</div>'}}
function changeWeeklyWeek(dir){if(!weeklyViewKey)weeklyViewKey=weekKey(new Date());var d=new Date(weeklyViewKey);d.setDate(d.getDate()+dir*7);weeklyViewKey=d.toISOString().slice(0,10);renderWeeklyPlan()}
function saveWeeklyPlan(){if(!weeklyViewKey)weeklyViewKey=weekKey(new Date());if(!STATE.weeklyPlans)STATE.weeklyPlans={};var priorities=[0,1,2].map(function(i){return (document.getElementById('wp-p'+i)||{}).value||''});STATE.weeklyPlans[weeklyViewKey]={priorities:priorities,intention:(document.getElementById('weekly-intention')||{}).value||'',reflection:(document.getElementById('weekly-reflection')||{}).value||'',savedAt:new Date().toISOString()};saveState();var btn=event.target;var orig=btn.textContent;btn.textContent='Saved!';setTimeout(function(){btn.textContent=orig},2000)}

