// Winter Arc selectors, evidence rules, safety policy, logging and progression.
// Raw user evidence is stored once; all challenge completion is derived here.
(function(global){
  'use strict';
  var PLAN_ID='winter-arc-75-me-2026';
  var CHALLENGE_ID='winter-arc-75-me-v1';

  function plan(){return global.WINTER_ARC_TRAINING_V1||null}
  function clone(value){return JSON.parse(JSON.stringify(value))}
  function dateKey(value){return typeof value==='string'?value:localDateKey(value||new Date())}
  function addDays(key,amount){var d=new Date(key+'T12:00:00');d.setDate(d.getDate()+amount);return localDateKey(d)}
  function dayDiff(a,b){var x=a.split('-').map(Number),y=b.split('-').map(Number);return Math.round((Date.UTC(y[0],y[1]-1,y[2])-Date.UTC(x[0],x[1]-1,x[2]))/86400000)}
  function clampNumber(value,min,max){var n=Number(value);return Number.isFinite(n)?Math.min(max,Math.max(min,n)):null}
  function evidenceElapsed(timer,now){if(!timer)return 0;var base=Number(timer.elapsedBeforeSec||timer.elapsedSec||0),anchor=Number(timer.anchorMs),heartbeat=Number(timer.heartbeatMs);if(!anchor)return Math.max(0,Math.floor(base));var end=Math.min(Number(now||Date.now()),heartbeat?heartbeat+35000:anchor);return Math.max(0,Math.floor(base+Math.max(0,end-anchor)/1000))}
  function resumeEvidenceTimer(timer){if(!timer)return;timer.elapsedBeforeSec=evidenceElapsed(timer);timer.anchorMs=Date.now();timer.heartbeatMs=timer.anchorMs}
  function pauseEvidenceTimer(timer){if(!timer||!timer.anchorMs)return;timer.elapsedBeforeSec=evidenceElapsed(timer);timer.anchorMs=null;timer.heartbeatMs=null}
  function occurrenceId(key,code){return PLAN_ID+'__'+key+'__'+code}
  function sessionRecord(id){return (STATE.trainingSessions||{})[id]||null}

  function winterArcPhaseForWeek(week){var p=plan();return p&&p.phases[week-1]||null}
  function winterArcOccurrence(value){
    var p=plan(),key=dateKey(value);if(!p||key<p.startDate||key>p.endDate)return null;
    var offset=dayDiff(p.startDate,key),week=Math.floor(offset/7)+1,dow=new Date(key+'T12:00:00').getDay();
    var base=p.weekPattern.find(function(item){return item.dow===dow});if(!base)return null;
    var phase=winterArcPhaseForWeek(week),out=clone(base),patternCode=out.code;
    if(key===p.endDate){out.code='TEST';out.label='Final test, review + core';out.kind='test';out.durationMin=45;out.test=true;out.qualifies=true}
    out.id=occurrenceId(key,out.code);out.planId=p.id;out.planVersion=p.version;out.planContentRevision=p.contentRevision;out.date=key;out.day=offset+1;out.week=week;out.phase=clone(phase);
    if(patternCode==='INT')out.interval=clone(p.intervals[phase.key]||p.intervals[phase.rangeKey]);
    if(out.includePhysio)out.physio=clone(p.physio);
    var mainExercises=p.exercises[out.code]||[],coreCoverage=p.dailyCore&&p.dailyCore.coverage[patternCode],coreExercises=p.dailyCore&&p.dailyCore.supplemental[patternCode]||[];
    if(coreCoverage)out.core=clone(coreCoverage);
    out.exercises=clone(mainExercises.concat(coreExercises));
    return out;
  }
  function winterArcWeek(value){var key=dateKey(value),p=plan();if(!p)return [];var d=new Date(key+'T12:00:00'),shift=(d.getDay()+6)%7,monday=addDays(key,-shift);var rows=[];for(var i=0;i<7;i++){var occurrence=winterArcOccurrence(addDays(monday,i));if(occurrence)rows.push(occurrence)}return rows}

  function winterArcSafety(value){
    var key=dateKey(value),choice=((STATE.dailyCheckIns||{})[key]||{}).sessionChoice;
    if(choice==='rest')return {level:'rest',action:'rest',title:'Full rest selected',message:'No workout is required today. Clinical guidance always wins.',clinician:true};
    if(choice==='recovery')return {level:'recovery',action:'recovery',title:'Recovery selected',message:'Use the 45-minute Recovery session instead of the scheduled workout.'};
    return {level:'planned',action:'planned',title:'Train as planned',message:'Follow the scheduled session and use Niggle or Stop if an exercise does not feel right.'};
  }
  function effectiveWinterArcOccurrence(value){
    var occurrence=winterArcOccurrence(value);if(!occurrence)return null;var safety=winterArcSafety(value);occurrence.safety=safety;
    if(safety.action==='recovery'&&occurrence.code!=='REC'){
      var recovery=plan().weekPattern.find(function(x){return x.code==='REC'});occurrence.originalCode=occurrence.code;occurrence.code='REC-SAFETY';occurrence.label='Recovery · chosen swap';occurrence.kind='recovery';occurrence.exercises=[];occurrence.blocks=clone(recovery.blocks);occurrence.core=clone(plan().dailyCore.coverage.REC);
    }
    if(safety.action==='rest'){occurrence.originalCode=occurrence.code;occurrence.code='REST-SAFETY';occurrence.label='Full rest · selected';occurrence.kind='rest';occurrence.qualifies=false;occurrence.exercises=[];occurrence.core=null}
    return occurrence;
  }

  function checkInForDate(value){return (STATE.dailyCheckIns||{})[dateKey(value)]||{}}
  function saveDailyCheckIn(value,patch){
    var key=dateKey(value),snapshot=clone(STATE);if(!STATE.dailyCheckIns)STATE.dailyCheckIns={};var current=STATE.dailyCheckIns[key]||{};
    var next=Object.assign({},current,patch,{date:key,updatedAt:new Date().toISOString()});
    Object.keys(patch||{}).forEach(function(field){if(patch[field]===null)delete next[field]});
    if(next.hipPain!==undefined){next.hipPain=clampNumber(next.hipPain,0,10);if(next.hipPain===null)delete next.hipPain}
    ['sleepHours','steps','proteinG','calories'].forEach(function(field){if(next[field]!==undefined&&next[field]!==''){var n=Number(next[field]);if(Number.isFinite(n)&&n>=0)next[field]=n;else delete next[field]}});
    if(next.alcoholState&&['none','special-occasion','outside-plan'].indexOf(next.alcoholState)===-1)delete next.alcoholState;
    STATE.dailyCheckIns[key]=next;if(!saveStateOrRollback(snapshot))return false;
    emitLifeHubChange({action:'winter-arc-checkin',dateKeys:[key],domains:['dailyCheckIns'],source:'winter-arc'});return true;
  }

  function habitByChallengeKey(key){var c=(STATE.challenges||{})[CHALLENGE_ID]||{};var id=c.habitIds&&c.habitIds[key];return id?(STATE.habits||[]).find(function(h){return h&&h.id===id}):null}
  function waterEvidence(key,target){var c=(STATE.challenges||{})[CHALLENGE_ID]||{},glassMl=Number(c.waterGlassMl||STATE.waterSettings&&STATE.waterSettings.glassMl||250),glasses=Number((STATE.water||{})[key]||0),ml=glasses*glassMl;return {done:ml>=target,ml:ml,targetMl:target,glasses:glasses}}
  function readingSeconds(key){return Object.keys((STATE.reading&&STATE.reading.sessions)||{}).reduce(function(sum,id){var s=STATE.reading.sessions[id];return sum+(s&&s.date===key&&s.completedAt?Number(s.elapsedSec||0):0)},0)}
  function canonicalSessionEvidence(session,key){if(!session||session.status!=='completed'||session.date!==key||Number(session.durationSec)<2700)return false;var occurrence=winterArcOccurrence(key);if(!occurrence||session.id!==occurrence.id||session.occurrenceId!==occurrence.id||session.planId!==occurrence.planId||session.planVersion!==occurrence.planVersion)return false;if(session.code==='REST-SAFETY'||session.kind==='rest'||session.qualifies!==true)return false;if(session.code==='REC-SAFETY')return session.kind==='recovery'&&Array.isArray(session.exercises)&&session.exercises.length===0;if(session.code!==occurrence.code||session.kind!==occurrence.kind)return false;if(session.planContentRevision==='1.2'&&occurrence.exercises&&occurrence.exercises.length){var expected=(occurrence.exercises||[]).filter(function(def){var count=def.fixedSets!==undefined?def.fixedSets:(def.phaseSets&&def.phaseSets[occurrence.phase.key]!==undefined?def.phaseSets[occurrence.phase.key]:occurrence.phase.mainSets);return count>0});if(!Array.isArray(session.exercises)||session.exercises.length!==expected.length||!expected.every(function(def){return session.exercises.some(function(ex){return ex.exerciseId===def.id&&Array.isArray(ex.sets)})}))return false}return true}
  function qualifyingWorkoutSeconds(key){return Object.keys(STATE.trainingSessions||{}).reduce(function(sum,id){var s=STATE.trainingSessions[id];return sum+(canonicalSessionEvidence(s,key)?Number(s.durationSec||0):0)},0)}
  function winterArcRuleStatus(rule,value){
    var key=dateKey(value),check=checkInForDate(key);
    if(rule.evidence==='daily-steps')return {done:Number(check.steps||0)>=rule.target,value:Number(check.steps||0),target:rule.target,meta:Number(check.steps||0).toLocaleString()+' / '+rule.target.toLocaleString()};
    if(rule.evidence==='qualifying-session'){var sec=qualifyingWorkoutSeconds(key);return {done:sec>=rule.targetSeconds,value:sec,target:rule.targetSeconds,meta:Math.floor(sec/60)+' / '+Math.floor(rule.targetSeconds/60)+' min'}}
    if(rule.evidence==='water')return waterEvidence(key,rule.targetMl);
    if(rule.evidence==='reading'){var read=readingSeconds(key);return {done:read>=rule.targetSeconds,value:read,target:rule.targetSeconds,meta:Math.floor(read/60)+' / 15 min'}}
    if(rule.evidence==='habit'){var habit=habitByChallengeKey(rule.habitKey);return {done:!!(habit&&habit.logs&&habit.logs[key]),habitId:habit&&habit.id||null}}
    if(rule.evidence==='alcohol')return {done:check.alcoholState==='none'||check.alcoholState==='special-occasion',state:check.alcoholState||null,meta:check.alcoholState==='special-occasion'?'Special occasion':check.alcoholState==='none'?'No alcohol':'Choose result'};
    if(rule.evidence==='nutrition'){var threshold=Number(check.proteinG||0)>=rule.proteinMinG&&Number(check.calories||0)>=rule.caloriesMin&&Number(check.calories||0)<=rule.caloriesMax,manual=check.balancedPortionsConfirmed===true;return {done:threshold||manual,threshold:threshold,manual:manual,meta:manual?'Portion guide confirmed':Number(check.proteinG||0)+'g · '+Number(check.calories||0)+' kcal'}}
    return {done:false};
  }
  function winterArcDailyStatus(value){var p=plan(),key=dateKey(value),rows=(p?p.challenge.rules:[]).map(function(rule){return Object.assign({},clone(rule),winterArcRuleStatus(rule,key))});return {date:key,rows:rows,done:rows.filter(function(r){return r.done}).length,total:rows.length,complete:rows.length===8&&rows.every(function(r){return r.done})}}

  function startReadingTimer(value){var key=dateKey(value),snapshot=clone(STATE),now=new Date().toISOString();if(!STATE.reading)STATE.reading={sessions:{},activeSessionId:null};if(STATE.reading.activeSessionId){var active=STATE.reading.sessions[STATE.reading.activeSessionId];if(active){resumeEvidenceTimer(active);active.status='active';saveStateOrRollback(snapshot)}return STATE.reading.activeSessionId}var id='read__'+key+'__'+Date.now().toString(36),stamp=Date.now();STATE.reading.sessions[id]={id:id,date:key,startedAt:now,anchorMs:stamp,heartbeatMs:stamp,elapsedBeforeSec:0,status:'active'};STATE.reading.activeSessionId=id;if(!saveStateOrRollback(snapshot))return null;emitLifeHubChange({action:'reading-start',entityId:id,dateKeys:[key],domains:['reading'],source:'winter-arc'});return id}
  function finishReadingTimer(){var id=STATE.reading&&STATE.reading.activeSessionId,s=STATE.reading&&STATE.reading.sessions&&STATE.reading.sessions[id];if(!s)return false;var snapshot=clone(STATE),elapsed=evidenceElapsed(s);s.elapsedSec=elapsed;s.completedAt=new Date().toISOString();s.status='completed';delete s.anchorMs;delete s.heartbeatMs;delete s.elapsedBeforeSec;STATE.reading.activeSessionId=null;if(!saveStateOrRollback(snapshot))return false;emitLifeHubChange({action:'reading-finish',entityId:id,dateKeys:[s.date],domains:['reading'],source:'winter-arc'});return true}
  function activeReadingElapsed(){var id=STATE.reading&&STATE.reading.activeSessionId,s=STATE.reading&&STATE.reading.sessions&&STATE.reading.sessions[id];return s?evidenceElapsed(s):0}

  function previousExerciseContext(exerciseId,beforeDate){var rows=Object.keys(STATE.trainingSessions||{}).map(function(id){return STATE.trainingSessions[id]}).filter(function(s){return s&&s.status==='completed'&&s.date<beforeDate}).sort(function(a,b){return b.date.localeCompare(a.date)});for(var i=0;i<rows.length;i++){var found=(rows[i].exercises||[]).find(function(x){return x.exerciseId===exerciseId});if(found)return {exercise:found,session:rows[i],phase:rows[i].phase||(winterArcOccurrence(rows[i].date)||{}).phase||null}}return null}
  function previousExerciseResult(exerciseId,beforeDate){var context=previousExerciseContext(exerciseId,beforeDate);return context&&context.exercise||null}
  function roundDown(value,step){return Math.floor((Number(value)+1e-9)/step)*step}
  function epleyLoad(weight,reps,targetReps,targetRir,step){var e1rm=Number(weight)*(1+Number(reps)/30);return roundDown(e1rm/(1+(Number(targetReps)+Number(targetRir))/30),step||1)}
  function exerciseRange(exercise,phase){var key=phase.rangeKey||phase.key,range=exercise.reps&&exercise.reps[key];return range||null}
  function suggestedExercise(exercise,occurrence){
    var phase=occurrence.phase,range=exerciseRange(exercise,phase),context=previousExerciseContext(exercise.id,occurrence.date),previous=context&&context.exercise,linkedPrevious=exercise.linkedExerciseId&&previousExerciseResult(exercise.linkedExerciseId,occurrence.date),sets=exercise.fixedSets!==undefined?exercise.fixedSets:(exercise.phaseSets&&exercise.phaseSets[phase.key]!==undefined?exercise.phaseSets[phase.key]:phase.mainSets);
    if(exercise.mode==='skill')sets=1;if(sets<=0)return null;
    var load=previous&&Number.isFinite(Number(previous.nextLoadKg))?Number(previous.nextLoadKg):Number(exercise.startLoadKg||0);
    var phaseChanged=!!(context&&context.phase&&context.phase.key!==phase.key);
    if(phaseChanged&&!exercise.coreMicrodose&&range&&['db','db-pair','barbell','machine','cable'].indexOf(exercise.loadType)!==-1){
      var completed=(previous.sets||[]).filter(function(set){return set.done&&Number(set.loadKg)>0&&Number(set.reps)>0}).sort(function(a,b){return Number(b.loadKg)*(1+Number(b.reps)/30)-Number(a.loadKg)*(1+Number(a.reps)/30)});
      if(completed[0])load=epleyLoad(completed[0].loadKg,completed[0].reps,range[0],phase.rir,exercise.incrementKg||1);
    }
    if(phase.loadFactor&&!exercise.coreMicrodose)load=roundDown(load*phase.loadFactor,exercise.incrementKg||1);
    var timeRange=exercise.timeRangeSec&&exercise.timeRangeSec[phase.rangeKey],duration=previous&&previous.next&&Number.isFinite(Number(previous.next.durationSec))?Number(previous.next.durationSec):((exercise.timeSec&&exercise.timeSec[phase.rangeKey])||(timeRange&&timeRange[0])||null),maxDuration=timeRange&&timeRange[1]||duration;
    var reps=previous&&previous.next&&Number.isFinite(Number(previous.next.reps))?Number(previous.next.reps):(range?range[0]:(exercise.mode==='skill'?1:null)),rawRung=linkedPrevious&&linkedPrevious.nextRung||linkedPrevious&&linkedPrevious.rung||previous&&previous.nextRung||previous&&previous.rung||1,rung=Math.min(Math.max(1,Number(rawRung)||1),Math.max(1,Number(exercise.rungs||7))),misses=Number(previous&&previous.minimumMisses||previous&&previous.next&&previous.next.minimumMisses||0);
    return {id:occurrence.id+'__'+exercise.id,exerciseId:exercise.id,originalName:exercise.name,name:exercise.name,mode:exercise.mode,unit:exercise.unit||'reps',sides:exercise.sides||null,loadType:exercise.loadType,restSec:exercise.restSec||60,lowerBody:!!exercise.lowerBody,coreMicrodose:!!exercise.coreMicrodose,noProgression:!!exercise.noProgression,swap:exercise.swap||null,range:range,targetRir:phase.rir,phaseKey:phase.key,phaseWeek:phase.week,minimumMisses:misses,rung:rung,sets:Array.from({length:sets},function(_,index){return {id:occurrence.id+'__'+exercise.id+'__s'+(index+1),loadKg:load||0,reps:reps,durationSec:duration,targetDurationSec:duration,maxDurationSec:maxDuration,distanceM:exercise.distanceM||null,targetDistanceM:exercise.distanceM||null,done:false,effort:'Right',pain:'None'}})};
  }
  function buildTrainingSession(value){var occurrence=effectiveWinterArcOccurrence(value);if(!occurrence)return null;var existing=sessionRecord(occurrence.id);if(existing)return existing;var exercises=(occurrence.exercises||[]).map(function(ex){return suggestedExercise(ex,occurrence)}).filter(Boolean);return {id:occurrence.id,occurrenceId:occurrence.id,planId:occurrence.planId,planVersion:occurrence.planVersion,planContentRevision:occurrence.planContentRevision,date:occurrence.date,code:occurrence.code,label:occurrence.label,kind:occurrence.kind,phase:clone(occurrence.phase),status:'planned',qualifies:occurrence.qualifies!==false,durationSec:0,exercises:exercises,safety:occurrence.safety}}
  function upgradeSessionContent(session){
    if(!session||session.status==='completed'||session.planContentRevision===plan().contentRevision)return false;var canonical=winterArcOccurrence(session.date);if(!canonical||session.code!==canonical.code)return false;
    if(!Array.isArray(session.exercises))session.exercises=[];var existing={};session.exercises.forEach(function(ex){existing[ex.exerciseId]=true});(canonical.exercises||[]).forEach(function(def){if(existing[def.id])return;var added=suggestedExercise(def,canonical);if(added)session.exercises.push(added)});
    session.planContentRevision=canonical.planContentRevision;session.label=canonical.label;return true;
  }
  function applyCurrentSafety(session){
    if(!session||session.status==='completed')return false;var effective=effectiveWinterArcOccurrence(session.date);if(!effective)return false;var changed=false;
    if(JSON.stringify(session.safety||{})!==JSON.stringify(effective.safety||{})){session.safety=clone(effective.safety);changed=true}
    if(effective.kind==='rest'){
      if(session.exercises&&session.exercises.length&&!session.supersededExercises)session.supersededExercises=clone(session.exercises);
      if(session.exercises&&session.exercises.length){session.exercises=[];changed=true}if(session.kind!=='rest'||session.code!=='REST-SAFETY'){session.kind='rest';session.code='REST-SAFETY';session.label='Full rest · selected';changed=true}session.planContentRevision=effective.planContentRevision;
      if(session.qualifies!==false){session.qualifies=false;changed=true}if(session.lockedBySafety!=='rest'){session.lockedBySafety='rest';changed=true}
    }else if(effective.kind==='recovery'&&session.kind!=='recovery'){
      if(session.exercises&&session.exercises.length&&!session.supersededExercises)session.supersededExercises=clone(session.exercises);
      session.exercises=[];session.kind='recovery';session.code=effective.code;session.label=effective.label;session.lockedBySafety=null;session.qualifies=true;changed=true;
    }else if(effective.safety.action==='planned'&&session.code==='REC-SAFETY'){
      var restored=winterArcOccurrence(session.date);session.kind=restored.kind;session.code=restored.code;session.label=restored.label;session.phase=clone(restored.phase);session.exercises=session.supersededExercises?clone(session.supersededExercises):(restored.exercises||[]).map(function(ex){return suggestedExercise(ex,restored)}).filter(Boolean);delete session.supersededExercises;session.planContentRevision=restored.planContentRevision;session.lockedBySafety=null;session.qualifies=restored.qualifies!==false;changed=true;
    }else if(session.kind==='rest'||session.code==='REST-SAFETY'){
      var canonical=winterArcOccurrence(session.date),restoredExercises=session.supersededExercises?clone(session.supersededExercises):(canonical.exercises||[]).map(function(ex){return suggestedExercise(ex,canonical)}).filter(Boolean);session.kind=canonical.kind;session.code=canonical.code;session.label=canonical.label;session.phase=clone(canonical.phase);session.exercises=restoredExercises;delete session.supersededExercises;var restoredIds={};session.exercises.forEach(function(ex){restoredIds[ex.exerciseId]=true});(canonical.exercises||[]).forEach(function(def){if(restoredIds[def.id])return;var added=suggestedExercise(def,canonical);if(added)session.exercises.push(added)});session.planContentRevision=canonical.planContentRevision;session.lockedBySafety=null;session.qualifies=canonical.qualifies!==false;changed=true;
    }else if(session.lockedBySafety==='rest'){
      session.lockedBySafety=null;session.qualifies=effective.qualifies!==false;changed=true;
    }
    return changed;
  }
  function reconcileWinterArcSessionSafety(value){var key=dateKey(value),occurrence=winterArcOccurrence(key),session=occurrence&&sessionRecord(occurrence.id);if(!session||session.status==='completed')return false;var snapshot=clone(STATE),changed=applyCurrentSafety(session);if(session.lockedBySafety==='rest'&&session.sessionTimer&&session.sessionTimer.anchorMs){pauseEvidenceTimer(session.sessionTimer);changed=true}if(!changed)return true;session.updatedAt=new Date().toISOString();if(!saveStateOrRollback(snapshot,{suppressUndo:true}))return false;emitLifeHubChange({action:'training-choice',entityId:session.id,dateKeys:[key],domains:['trainingSessions'],source:'winter-arc'});return true}

  function startWinterArcSession(value){
    var requested=dateKey(value);if(requested!==localDateKey(new Date()))return null;var draft=buildTrainingSession(requested);if(!draft)return null;if(draft.status==='completed')return draft.id;
    var existing=!!sessionRecord(draft.id),snapshot=clone(STATE);upgradeSessionContent(draft);applyCurrentSafety(draft);
    if(draft.lockedBySafety==='rest'){if(existing)saveStateOrRollback(snapshot,{suppressUndo:true});return null}
    if(draft.status==='planned'){
      var now=Date.now();draft.status='in-progress';draft.startedAt=new Date(now).toISOString();draft.sessionTimer={anchorMs:now,heartbeatMs:now,elapsedBeforeSec:Number(draft.durationSec||0)};draft.updatedAt=draft.startedAt;if(!STATE.trainingSessions)STATE.trainingSessions={};STATE.trainingSessions[draft.id]=draft;if(!saveStateOrRollback(snapshot))return null;emitLifeHubChange({action:'training-start',entityId:draft.id,dateKeys:[draft.date],domains:['trainingSessions'],source:'winter-arc'});
    }else if(draft.status==='in-progress'){
      if(draft.sessionTimer)resumeEvidenceTimer(draft.sessionTimer);(draft.exercises||[]).forEach(function(ex){(ex.sets||[]).forEach(function(set){if(set.timerAnchorMs){var elapsed=evidenceElapsed({anchorMs:set.timerAnchorMs,heartbeatMs:set.heartbeatMs,elapsedBeforeSec:set.durationSec||0});set.durationSec=elapsed;set.timerAnchorMs=Date.now();set.heartbeatMs=set.timerAnchorMs}})});draft.updatedAt=new Date().toISOString();if(!saveStateOrRollback(snapshot))return null;
    }
    return draft.id;
  }
  function updateTrainingSet(sessionId,exerciseId,setId,patch){var session=sessionRecord(sessionId);if(!session)return false;var snapshot=clone(STATE);if(applyCurrentSafety(session)){session.updatedAt=new Date().toISOString();if(session.lockedBySafety==='rest'||session.kind==='recovery'){saveStateOrRollback(snapshot);return false}}var exercise=(session.exercises||[]).find(function(x){return x.id===exerciseId}),set=exercise&&(exercise.sets||[]).find(function(x){return x.id===setId});if(!set)return false;if(exercise.stopLatched&&patch.done===true)return false;Object.keys(patch).forEach(function(key){set[key]=patch[key]});session.updatedAt=new Date().toISOString();if(set.pain==='Stop'){set.done=false;exercise.swapFlag=true;exercise.stopLatched=true;if(!Array.isArray(exercise.stopEvents))exercise.stopEvents=[];if(!exercise.stopEvents.some(function(event){return event.setId===set.id}))exercise.stopEvents.push({setId:set.id,at:new Date().toISOString()})}if(!saveStateOrRollback(snapshot))return false;emitLifeHubChange({action:'training-set',entityId:setId,dateKeys:[session.date],domains:['trainingSessions'],source:'winter-arc',rendered:true});return true}
  function sameAsLastTime(sessionId,exerciseId){var session=sessionRecord(sessionId),exercise=session&&(session.exercises||[]).find(function(x){return x.id===exerciseId});if(!exercise)return false;var previous=previousExerciseResult(exercise.exerciseId,session.date);if(!previous)return false;var snapshot=clone(STATE);exercise.sets.forEach(function(set,index){var prior=previous.sets&&previous.sets[Math.min(index,previous.sets.length-1)];if(prior){['loadKg','reps','durationSec','distanceM'].forEach(function(k){if(prior[k]!=null)set[k]=prior[k]})}});session.updatedAt=new Date().toISOString();if(!saveStateOrRollback(snapshot))return false;emitLifeHubChange({action:'training-copy-last',entityId:exerciseId,dateKeys:[session.date],domains:['trainingSessions'],source:'winter-arc',rendered:true});return true}
  function nextExerciseSuggestion(exercise,phase,morningPain){
    var sets=exercise.sets||[],completed=sets.filter(function(s){return s.done}),painStop=sets.some(function(s){return s.pain==='Stop'}),niggle=sets.some(function(s){return s.pain==='Niggle'}),range=exercise.range,load=Number(sets[0]&&sets[0].loadKg||0),effort=sets.some(function(s){return s.effort==='Hard'})?'Hard':sets.length&&sets.every(function(s){return s.effort==='Easy'})?'Easy':'Right',definition=findExercise(exercise.exerciseId);
    if(exercise.swapAccepted||exercise.skippedAfterStop)return {action:'hold',loadKg:load,minimumMisses:Number(exercise.minimumMisses||0),reason:'Pain response recorded — hold progression.'};
    if(painStop||exercise.stopLatched||exercise.stopEvents&&exercise.stopEvents.length)return {action:'swap',loadKg:load,minimumMisses:Number(exercise.minimumMisses||0),reason:'Pain marked Stop — hold progression and use the swap or skip.'};
    if((niggle||Number(morningPain)>=2)&&exercise.lowerBody)return {action:'hold',loadKg:load,minimumMisses:Number(exercise.minimumMisses||0),reason:'Lower-body load held for pain safety.'};
    if(exercise.noProgression)return {action:'hold',loadKg:load,minimumMisses:0,reason:'Keep this breathing reset easy and consistent.'};
    if(phase.noProgression)return {action:'hold',loadKg:load,minimumMisses:Number(exercise.minimumMisses||0),reason:'No progression during deload or taper.'};
    if(exercise.mode==='time'&&completed.length===sets.length&&sets.length&&completed.every(function(set){return Number(set.durationSec||0)>=Number(set.targetDurationSec||0)})){var currentTarget=Number(sets[0].targetDurationSec||sets[0].durationSec||0),maxTarget=Number(sets[0].maxDurationSec||currentTarget+5);if(currentTarget>=maxTarget)return {action:'hold',durationSec:maxTarget,minimumMisses:0,reason:'Daily core time target reached — keep it crisp.'};return {action:'increase-time',durationSec:Math.min(maxTarget,currentTarget+5),minimumMisses:0,reason:'All timed sets reached target — add 5 seconds.'}}
    if(exercise.mode==='time')return {action:'hold',durationSec:Number(sets[0]&&sets[0].targetDurationSec||0),minimumMisses:Number(exercise.minimumMisses||0),reason:'Hold the timed target until every set reaches it.'};
    if(exercise.mode==='distance'&&completed.length===sets.length&&sets.length&&completed.every(function(set){return Number(set.distanceM||0)>=Number(set.targetDistanceM||0)})){var distanceIncrement=Number(definition&&definition.incrementKg||0);return {action:'increase',loadKg:load+distanceIncrement,minimumMisses:0,reason:'All carries reached target — add the prescribed load.'}}
    if(exercise.mode==='distance')return {action:'hold',loadKg:load,minimumMisses:Number(exercise.minimumMisses||0),reason:'Hold load until every carry reaches the target distance.'};
    if(exercise.mode==='ladder'&&completed.length>=3&&completed.length===sets.length&&completed.every(function(s){return Number(s.reps)>=10})){var maxRung=Number(definition&&definition.rungs||Infinity);if(Number(exercise.rung||1)>=maxRung)return {action:'hold',rung:maxRung,minimumMisses:0,reason:'Top ladder rung reached — hold and own it.'};return {action:'next-rung',rung:Number(exercise.rung||1)+1,reps:6,minimumMisses:0,reason:'Three sets at 10 — move one rung and reset to 6.'}}
    if(exercise.mode==='ladder')return {action:'hold',rung:Math.min(Number(definition&&definition.rungs||7),Math.max(1,Number(exercise.rung||1))),minimumMisses:Number(exercise.minimumMisses||0),reason:'Stay on this rung until three sets reach 10.'};
    if(!range||!completed.length)return {action:'hold',loadKg:load,minimumMisses:Number(exercise.minimumMisses||0),reason:'Repeat this target next time.'};
    var allMax=completed.length===sets.length&&completed.every(function(s){return Number(s.reps)>=range[1]});
    if(allMax&&effort!=='Hard'){
      if(exercise.coreMicrodose)return {action:'hold',loadKg:load,reps:range[1],minimumMisses:0,reason:'Daily core rep target reached — keep the movement controlled.'};
      if(definition&&definition.loadType==='bodyweight')return {action:'add-bodyweight-load',loadKg:load+Number(definition.bodyweightAddKg||8),reps:4,minimumMisses:0,reason:'Top reps reached — add two 4kg dumbbells and reset to 4 reps.'};
      var increment=Number(definition&&definition.incrementKg||0);if(effort==='Easy'&&phase.week<=2)increment*=2;var next=definition&&definition.loadType==='assistance'?load-increment:load+increment;return {action:'increase',loadKg:Math.max(0,next),minimumMisses:0,reason:effort==='Easy'&&phase.week<=2?'Easy calibration: double increment.':'All sets reached the top of the range.'};
    }
    if(allMax&&effort==='Hard')return {action:'hold',loadKg:load,minimumMisses:0,reason:'Top reps felt hard — hold the load.'};
    var allMin=completed.length===sets.length&&completed.every(function(s){return Number(s.reps)>=range[0]});if(allMin)return {action:'reps',loadKg:load,reps:Math.min(range[1],Math.min.apply(null,completed.map(function(s){return Number(s.reps)}))+1),minimumMisses:0,reason:'Hold load and add one rep from the lowest set.'};
    var previousMisses=Number(exercise.minimumMisses||0)+1;if(previousMisses>=2){var factor=definition&&definition.loadType==='assistance'?1.1:0.9;return {action:'reduce',loadKg:roundDown(load*factor,definition&&definition.incrementKg||1),minimumMisses:0,reason:'Minimum missed twice — adjust by 10%.'}}
    return {action:'hold',loadKg:load,minimumMisses:previousMisses,reason:'Repeat after one minimum miss.'};
  }
  function findExercise(id){var p=plan(),found=null;Object.keys(p.exercises).some(function(code){found=p.exercises[code].find(function(ex){return ex.id===id});return !!found});if(found)return found;Object.keys(p.dailyCore&&p.dailyCore.supplemental||{}).some(function(code){found=p.dailyCore.supplemental[code].find(function(ex){return ex.id===id});return !!found});return found}
  function finishWinterArcSession(sessionId,durationSec){var session=sessionRecord(sessionId);if(!session)return false;var snapshot=clone(STATE),safetyChanged=applyCurrentSafety(session);if(session.lockedBySafety==='rest'){if(safetyChanged)saveStateOrRollback(snapshot);return false}if((session.exercises||[]).some(function(ex){return ex.stopLatched&&!ex.swapAccepted&&!ex.skippedAfterStop})){return false}var occurrence=winterArcOccurrence(session.date),pain=null;session.durationSec=Math.max(0,Math.round(Number(durationSec)||0));session.sessionTimer=null;session.restTimer=null;session.completedAt=new Date().toISOString();session.updatedAt=session.completedAt;session.status='completed';(session.exercises||[]).forEach(function(ex){var suggestion=nextExerciseSuggestion(ex,occurrence.phase,pain);ex.next=suggestion;ex.minimumMisses=Number(suggestion.minimumMisses||0);if(suggestion.loadKg!=null)ex.nextLoadKg=suggestion.loadKg;if(suggestion.rung!=null)ex.nextRung=suggestion.rung});if(!saveStateOrRollback(snapshot))return false;emitLifeHubChange({action:'training-finish',entityId:sessionId,dateKeys:[session.date],domains:['trainingSessions'],source:'winter-arc'});return true}

  function pauseWinterArcEvidenceTimers(){var snapshot=clone(STATE),changed=false,reading=STATE.reading&&STATE.reading.sessions&&STATE.reading.sessions[STATE.reading.activeSessionId];if(reading&&reading.anchorMs){pauseEvidenceTimer(reading);changed=true}Object.keys(STATE.trainingSessions||{}).forEach(function(id){var session=STATE.trainingSessions[id];if(!session||session.status!=='in-progress')return;if(session.sessionTimer&&session.sessionTimer.anchorMs){pauseEvidenceTimer(session.sessionTimer);changed=true}(session.exercises||[]).forEach(function(ex){(ex.sets||[]).forEach(function(set){if(set.timerAnchorMs){set.durationSec=evidenceElapsed({anchorMs:set.timerAnchorMs,heartbeatMs:set.heartbeatMs,elapsedBeforeSec:set.durationSec||0});set.timerAnchorMs=null;set.heartbeatMs=null;changed=true}})})});if(changed)saveStateOrRollback(snapshot,{suppressUndo:true});return changed}
  function resumeWinterArcEvidenceTimers(){var snapshot=clone(STATE),changed=false,today=dateKey(new Date()),reading=STATE.reading&&STATE.reading.sessions&&STATE.reading.sessions[STATE.reading.activeSessionId];if(reading&&!reading.anchorMs&&reading.status==='active'){resumeEvidenceTimer(reading);changed=true}Object.keys(STATE.trainingSessions||{}).forEach(function(id){var session=STATE.trainingSessions[id];if(!session||session.status!=='in-progress')return;if(session.date!==today){if(session.sessionTimer&&session.sessionTimer.anchorMs){pauseEvidenceTimer(session.sessionTimer);changed=true}return}if(session.sessionTimer&&!session.sessionTimer.anchorMs){resumeEvidenceTimer(session.sessionTimer);changed=true}});if(changed)saveStateOrRollback(snapshot,{suppressUndo:true});return changed}
  function heartbeatWinterArcEvidence(){if(typeof document!=='undefined'&&document.hidden)return false;var snapshot=clone(STATE),now=Date.now(),today=dateKey(new Date()),changed=false,reading=STATE.reading&&STATE.reading.sessions&&STATE.reading.sessions[STATE.reading.activeSessionId];if(reading&&reading.anchorMs){reading.heartbeatMs=now;changed=true}Object.keys(STATE.trainingSessions||{}).forEach(function(id){var session=STATE.trainingSessions[id];if(!session||session.status!=='in-progress'||session.date!==today)return;if(session.sessionTimer&&session.sessionTimer.anchorMs){session.sessionTimer.heartbeatMs=now;changed=true}(session.exercises||[]).forEach(function(ex){(ex.sets||[]).forEach(function(set){if(set.timerAnchorMs){set.heartbeatMs=now;changed=true}})})});if(changed)saveStateOrRollback(snapshot,{suppressUndo:true});return changed}

  global.WINTER_ARC_PLAN_ID=PLAN_ID;global.WINTER_ARC_CHALLENGE_ID=CHALLENGE_ID;
  global.winterArcPlan=plan;global.winterArcOccurrence=winterArcOccurrence;global.effectiveWinterArcOccurrence=effectiveWinterArcOccurrence;global.winterArcWeek=winterArcWeek;global.winterArcSafety=winterArcSafety;
  global.winterArcDailyStatus=winterArcDailyStatus;global.winterArcRuleStatus=winterArcRuleStatus;global.checkInForDate=checkInForDate;global.saveDailyCheckIn=saveDailyCheckIn;global.reconcileWinterArcSessionSafety=reconcileWinterArcSessionSafety;
  global.startReadingTimer=startReadingTimer;global.finishReadingTimer=finishReadingTimer;global.activeReadingElapsed=activeReadingElapsed;global.readingSeconds=readingSeconds;
  global.buildTrainingSession=buildTrainingSession;global.startWinterArcSession=startWinterArcSession;global.updateTrainingSet=updateTrainingSet;global.sameAsLastTime=sameAsLastTime;global.finishWinterArcSession=finishWinterArcSession;
  global.nextExerciseSuggestion=nextExerciseSuggestion;global.epleyLoad=epleyLoad;global.winterArcOccurrenceId=occurrenceId;global.winterArcEvidenceElapsed=evidenceElapsed;global.pauseWinterArcEvidenceTimers=pauseWinterArcEvidenceTimers;global.resumeWinterArcEvidenceTimers=resumeWinterArcEvidenceTimers;global.heartbeatWinterArcEvidence=heartbeatWinterArcEvidence;
})(typeof window!=='undefined'?window:globalThis);


// Browser presentation adapters. These replace the visible v6 weekly template
// while leaving its stored object and all generic workout history untouched.
(function(global){
  'use strict';
  var loggerTicker=null,pendingSetFocus=null;
  function esc(value){return typeof escapeHtml==='function'?escapeHtml(String(value==null?'':value)):String(value==null?'':value)}
  function currentPlan(){return global.WINTER_ARC_TRAINING_V1}
  function definitionFor(exerciseId){var p=currentPlan(),found=null;Object.keys(p.exercises||{}).some(function(code){found=(p.exercises[code]||[]).find(function(def){return def.id===exerciseId});return !!found});if(found)return found;Object.keys(p.dailyCore&&p.dailyCore.supplemental||{}).some(function(code){found=(p.dailyCore.supplemental[code]||[]).find(function(def){return def.id===exerciseId});return !!found});return found}
  function displayDate(value){var key=typeof value==='string'?value:localDateKey(value||new Date()),p=currentPlan();return key<p.startDate?p.startDate:key>p.endDate?p.endDate:key}
  function sessionForOccurrence(occurrence){return occurrence&&STATE.trainingSessions&&STATE.trainingSessions[occurrence.id]||null}
  function fmtSeconds(seconds){var total=Math.max(0,Math.floor(Number(seconds)||0)),m=Math.floor(total/60),s=total%60;return m+':'+String(s).padStart(2,'0')}
  function phaseCopy(occurrence){return 'Week '+occurrence.week+' · '+occurrence.phase.label+' · '+occurrence.phase.mainSets+' sets · RIR '+occurrence.phase.rir}

  var winterArcRoute=null;
  function winterArcContent(){return document.getElementById('winter-arc-content')}
  function activeWorkoutTab(){var active=document.querySelector('#page-workout .sub-page.active');return active?active.id.replace('workout-',''):'overview'}
  function updateWinterArcPageHeading(occurrence,preview){var title=document.getElementById('winter-arc-page-title'),kicker=document.getElementById('winter-arc-page-kicker');if(title)title.textContent=occurrence?occurrence.label:'Winter Arc session';if(kicker)kicker.textContent=preview?'SESSION PREVIEW':'WINTER ARC · '+(occurrence?occurrence.code:'SESSION')}
  function openWinterArcPageRoute(route){winterArcRoute=route;var page=document.getElementById('page-winter-arc');if(page&&page.classList.contains('active'))renderWinterArcPage();else nav('winter-arc')}
  global.renderWinterArcPage=function(){if(!winterArcRoute)return;var occurrence=winterArcOccurrence(winterArcRoute.date),session=winterArcRoute.sessionId&&(STATE.trainingSessions||{})[winterArcRoute.sessionId];if(session&&winterArcRoute.mode!=='preview'){occurrence=Object.assign({},occurrence,{label:session.label,code:session.code})}updateWinterArcPageHeading(occurrence,winterArcRoute.mode==='preview');if(winterArcRoute.mode==='preview')renderWinterArcPreview(winterArcRoute.date,session);else renderWinterArcLogger(winterArcRoute.sessionId)};
  global.closeWinterArcPage=function(){
    if(loggerTicker){clearInterval(loggerTicker);loggerTicker=null}hideWinterArcRestPopup();var route=winterArcRoute;winterArcRoute=null;var returnPage=route&&route.returnPage||'workout',returnTab=route&&route.returnTab||'overview',date=route&&route.date;
    nav(returnPage,function(){var button=null;if(returnPage==='workout'){button=document.querySelector('#page-workout .page-tab[data-tab="'+returnTab+'"]');subNav('workout',returnTab,button)}var focusRoot=returnPage==='workout'?document.getElementById('workout-'+returnTab):document.getElementById('page-'+returnPage),focus=date&&focusRoot&&focusRoot.querySelector('[data-training-date="'+date+'"]'),target=returnPage==='workout'?(button||focus):(focus||route&&route.opener);if(target&&typeof target.focus==='function')target.focus();if(button)setTimeout(function(){if(document.getElementById('page-workout').classList.contains('active'))button.focus()},600)});
  };

  global.todaysTrainingSession=function(key){
    var occurrence=effectiveWinterArcOccurrence(key||localDateKey(new Date()));if(!occurrence)return null;
    occurrence.session=occurrence.code;occurrence.trainingType=occurrence.kind;occurrence.icon=occurrence.kind==='strength'?'🏋🏽‍♀️':occurrence.kind==='cardio'?'💓':occurrence.kind==='rest'?'🛌':'🌸';occurrence.sub=occurrence.durationMin+' min · '+occurrence.phase.label;occurrence.detail=occurrence.safety.message;occurrence.logType=null;occurrence.acceptedLogTypes=[];return occurrence;
  };

  var activeEvidenceRule=null;
  function openEvidenceDialog(html,ruleId){
    var modal=document.getElementById('modal'),content=document.getElementById('modal-content');if(!modal||!content)return false;activeEvidenceRule=ruleId||null;if(typeof _modalReturnFocus!=='undefined'&&modal.style.display!=='flex')_modalReturnFocus=document.activeElement;content.innerHTML=html;modal.style.display='flex';var first=content.querySelector('[autofocus],input,button');if(first)setTimeout(function(){first.focus()},0);return true;
  }
  function evidenceError(message){var el=document.getElementById('wa-evidence-error');if(el){el.textContent=message;el.style.display='block'}}
  function finishEvidenceSave(key,patch,message){var returnRule=activeEvidenceRule;if(!saveDailyCheckIn(key,patch))return false;if(typeof closeModal==='function')closeModal();if(returnRule)setTimeout(function(){var replacement=document.querySelector('[data-challenge-rule="'+returnRule+'"]');if(replacement)replacement.focus()},0);if(typeof showCelebrationToast==='function')showCelebrationToast(message,'✓');return true}

  global.openWinterArcSteps=function(value){
    var key=value||localDateKey(new Date()),row=checkInForDate(key),current=row.steps==null?'':row.steps;
    openEvidenceDialog('<div class="wa-modal-kicker">10,000 STEPS</div><h2>Log today’s steps</h2><div class="modal-sub">'+esc(fmtDate(key))+' · enter the total shown by your phone or watch.</div><div id="wa-evidence-error" class="wa-evidence-error" role="alert" style="display:none"></div><div class="field"><label for="wa-quick-steps">Steps</label><input id="wa-quick-steps" type="number" inputmode="numeric" min="0" max="200000" step="1" value="'+esc(current)+'" placeholder="e.g. 10420" autofocus onkeydown="if(event.key===\'Enter\')saveWinterArcSteps(\''+key+'\')"></div><div class="modal-btns">'+(current!==''?'<button type="button" class="btn btn-ghost" onclick="clearWinterArcSteps(\''+key+'\')">Clear</button>':'')+'<button type="button" class="btn" onclick="closeModal()">Cancel</button><button type="button" class="btn btn-accent" onclick="saveWinterArcSteps(\''+key+'\')">Save steps</button></div>','steps');
  };
  global.saveWinterArcSteps=function(key){var input=document.getElementById('wa-quick-steps'),steps=Number(input&&input.value);if(!input||input.value===''||!Number.isInteger(steps)||steps<0||steps>200000){evidenceError('Enter a whole-number step total between 0 and 200,000.');return false}return finishEvidenceSave(key,{steps:steps},'Steps saved')};
  global.clearWinterArcSteps=function(key){return finishEvidenceSave(key,{steps:null},'Steps cleared')};

  global.openWinterArcEating=function(value){
    var key=value||localDateKey(new Date()),row=checkInForDate(key),protein=row.proteinG==null?'':row.proteinG,calories=row.calories==null?'':row.calories,hasEvidence=row.balancedPortionsConfirmed||protein!==''||calories!=='';
    openEvidenceDialog('<div class="wa-modal-kicker">EAT WELL</div><h2>How did eating go?</h2><div class="modal-sub">Use the quick portion guide, or log protein and calories if you tracked them.</div><div id="wa-evidence-error" class="wa-evidence-error" role="alert" style="display:none"></div><button type="button" class="wa-evidence-choice'+(row.balancedPortionsConfirmed?' selected':'')+'" aria-pressed="'+(row.balancedPortionsConfirmed?'true':'false')+'" onclick="saveWinterArcBalancedEating(\''+key+'\')"><strong>Balanced portions ✓</strong><span>One-tap option when meals followed your portion guide.</span></button><div class="wa-evidence-divider"><span>or track macros</span></div><div class="wa-form-grid"><div class="field"><label for="wa-quick-protein">Protein · grams</label><input id="wa-quick-protein" type="number" inputmode="decimal" min="0" max="1000" step="1" value="'+esc(protein)+'" placeholder="120"></div><div class="field"><label for="wa-quick-calories">Calories</label><input id="wa-quick-calories" type="number" inputmode="numeric" min="0" max="20000" step="1" value="'+esc(calories)+'" placeholder="1900"></div></div><p class="wa-evidence-hint">The tracked rule completes at 120g+ protein and 1,700–2,100 kcal.</p><div class="modal-btns">'+(hasEvidence?'<button type="button" class="btn btn-ghost" onclick="clearWinterArcEating(\''+key+'\')">Clear</button>':'')+'<button type="button" class="btn" onclick="closeModal()">Cancel</button><button type="button" class="btn btn-accent" onclick="saveWinterArcMacros(\''+key+'\')">Save macros</button></div>','eating');
  };
  global.saveWinterArcBalancedEating=function(key){return finishEvidenceSave(key,{balancedPortionsConfirmed:true,proteinG:null,calories:null},'Balanced portions saved')};
  global.saveWinterArcMacros=function(key){var p=document.getElementById('wa-quick-protein'),c=document.getElementById('wa-quick-calories'),protein=Number(p&&p.value),calories=Number(c&&c.value);if(!p||!c||p.value===''||c.value===''||!Number.isFinite(protein)||!Number.isFinite(calories)||protein<0||protein>1000||calories<0||calories>20000){evidenceError('Enter valid protein and calorie totals.');return false}return finishEvidenceSave(key,{balancedPortionsConfirmed:false,proteinG:protein,calories:calories},'Nutrition saved')};
  global.clearWinterArcEating=function(key){return finishEvidenceSave(key,{balancedPortionsConfirmed:false,proteinG:null,calories:null},'Eating result cleared')};

  global.openWinterArcAlcohol=function(value){
    var key=value||localDateKey(new Date()),row=checkInForDate(key),state=row.alcoholState||'',choice=function(value,label,copy){return '<button type="button" class="wa-evidence-choice'+(state===value?' selected':'')+'" aria-pressed="'+(state===value?'true':'false')+'" onclick="saveWinterArcAlcohol(\''+key+'\',\''+value+'\')"><strong>'+label+'</strong><span>'+copy+'</span></button>'};
    openEvidenceDialog('<div class="wa-modal-kicker">ALCOHOL</div><h2>Choose today’s result</h2><div class="modal-sub">Alcohol is limited to special occasions decided in advance.</div>'+choice('none','No alcohol','The daily rule is complete.')+choice('special-occasion','Planned special occasion','The daily rule is complete.')+choice('outside-plan','Outside the plan','Recorded honestly; the daily rule remains incomplete.')+'<div class="modal-btns">'+(state?'<button type="button" class="btn btn-ghost" onclick="clearWinterArcAlcohol(\''+key+'\')">Clear</button>':'')+'<button type="button" class="btn" onclick="closeModal()">Cancel</button></div>','alcohol');
  };
  global.saveWinterArcAlcohol=function(key,state){if(['none','special-occasion','outside-plan'].indexOf(state)===-1)return false;return finishEvidenceSave(key,{alcoholState:state,alcoholNote:null},'Alcohol result saved')};
  global.clearWinterArcAlcohol=function(key){return finishEvidenceSave(key,{alcoholState:null,alcoholNote:null},'Alcohol result cleared')};

  global.chooseWinterArcRecovery=function(key){if(saveDailyCheckIn(key,{sessionChoice:'recovery'})){reconcileWinterArcSessionSafety(key);if(typeof refreshPlannerCards==='function')refreshPlannerCards(['training']);if(typeof renderTrainingOverview==='function')renderTrainingOverview()}};
  global.chooseWinterArcFullRest=function(key){if(saveDailyCheckIn(key,{sessionChoice:'rest'})){reconcileWinterArcSessionSafety(key);if(typeof refreshPlannerCards==='function')refreshPlannerCards(['training']);if(typeof renderTrainingOverview==='function')renderTrainingOverview()}};
  global.restoreWinterArcPlan=function(key){if(saveDailyCheckIn(key,{sessionChoice:null})){reconcileWinterArcSessionSafety(key);if(typeof refreshPlannerCards==='function')refreshPlannerCards(['training']);if(typeof renderTrainingOverview==='function')renderTrainingOverview()}};

  function occurrenceDetail(occurrence){
    var rows=[];
    if(occurrence.interval)rows.push('<li><strong>Intervals</strong><span>'+esc(occurrence.interval.label)+'</span></li>');
    (occurrence.blocks||[]).forEach(function(block){rows.push('<li><strong>'+esc(block[0])+'</strong><span>'+block[1]+' min</span></li>')});
    (occurrence.options||[]).forEach(function(option){rows.push('<li><strong>Cardio option</strong><span>'+esc(option)+'</span></li>')});
    (occurrence.exercises||[]).forEach(function(ex){var range=ex.reps&&ex.reps[occurrence.phase.rangeKey],timeRange=ex.timeRangeSec&&ex.timeRangeSec[occurrence.phase.rangeKey],target=range?range[0]+'–'+range[1]+' '+(ex.unit||'reps'):timeRange?timeRange[0]+'–'+timeRange[1]+' sec':ex.timeSec?ex.timeSec[occurrence.phase.rangeKey]+' sec':ex.distanceM?ex.distanceM+'m':ex.skill&&ex.skill[occurrence.phase.rangeKey]||'';rows.push('<li><strong>'+(ex.coreMicrodose?'Daily core · ':'')+esc(ex.id)+' · '+esc(ex.name)+'</strong><span>'+esc(target)+(ex.sides?' · '+esc(ex.sides):'')+(ex.optional?' · optional':'')+'</span></li>')});
    if(occurrence.core&&occurrence.core.type==='embedded')rows.push('<li><strong>Daily core covered</strong><span>'+esc(occurrence.core.label)+'</span></li>');
    return rows.join('');
  }

  global.renderTrainingOverview=function(){
    var nowKey=localDateKey(new Date()),anchor=displayDate(nowKey),week=winterArcWeek(anchor),completed=week.filter(function(o){var s=sessionForOccurrence(o);return s&&s.status==='completed'}).length,target=week.length;
    var c=document.getElementById('training-week-count');if(c)c.innerHTML=completed+'<span style="font-size:18px;color:var(--text2);font-weight:400"> / '+target+'</span>';
    var t=document.getElementById('training-week-target');if(t)t.textContent=nowKey<currentPlan().startDate?'Your first Winter Arc week':completed===target?'Week complete ✓':(target-completed)+' planned session'+(target-completed===1?'':'s')+' left';
    var grid=document.getElementById('training-week-grid');if(grid)grid.innerHTML='<div class="training-week-grid">'+week.map(function(o){var s=sessionForOccurrence(o),today=o.date===nowKey;return '<button type="button" class="training-day '+(s&&s.status==='completed'?'done':today?'today':'')+'" data-training-date="'+o.date+'" onclick="openWinterArcWorkout(\''+o.date+'\')"><span class="training-day-name">'+esc(new Date(o.date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'short'}))+'</span><span class="training-day-plan">'+esc(o.code)+'</span><span class="training-day-logged">'+(s&&s.status==='completed'?'✓ Done':s&&s.status==='in-progress'?'Resume':esc(o.label))+'</span></button>'}).join('')+'</div>';
    var all=Object.keys(STATE.trainingSessions||{}).map(function(id){return STATE.trainingSessions[id]}).filter(function(s){return s&&s.status==='completed'}).sort(function(a,b){return String(b.completedAt||b.date).localeCompare(String(a.completedAt||a.date))});
    var month=nowKey.slice(0,7),monthCount=all.filter(function(s){return s.date&&s.date.slice(0,7)===month}).length;var mc=document.getElementById('training-month-count');if(mc)mc.textContent=monthCount;var mb=document.getElementById('training-month-breakdown');if(mb)mb.textContent='Winter Arc sessions';var last=all[0],ls=document.getElementById('training-last-session'),lw=document.getElementById('training-last-when');if(ls)ls.textContent=last?last.label:'—';if(lw)lw.textContent=last?fmtDate(last.date):'log your first';var streak=document.getElementById('training-streak'),streakSub=document.getElementById('training-streak-sub');if(streak)streak.textContent='—';if(streakSub)streakSub.textContent='never-miss-twice, not a reset streak';
    if(typeof renderTrainingEvents==='function')renderTrainingEvents();if(typeof renderTrainingBody==='function')renderTrainingBody();
  };

  global.renderTrainingFuel=function(){
    var el=document.getElementById('training-fuel');if(!el)return;var n=currentPlan().nutrition,today=localDateKey(new Date()),check=checkInForDate(today),eating=global.winterArcDailyStatus(today).rows.find(function(r){return r.id==='eating'});el.innerHTML='<div class="wa-fuel-hero card"><div><span>DAILY TARGET</span><strong>'+n.caloriesTarget.toLocaleString()+' kcal</strong><p>Floor '+n.caloriesFloor.toLocaleString()+' · eating rule range '+n.caloriesFloor.toLocaleString()+'–'+n.caloriesRuleMax.toLocaleString()+'</p></div><div class="wa-fuel-macros"><div><strong>'+n.proteinTargetG+'g</strong><span>protein</span></div><div><strong>'+n.fatTargetG+'g</strong><span>fat</span></div><div><strong>'+n.carbsTargetG+'g</strong><span>carbs</span></div><div><strong>2L</strong><span>water</span></div></div></div><div class="card wa-fuel-rule"><div class="planner-card-head"><span class="planner-card-title">Today’s eating rule</span><span class="wa-session-state">'+(eating&&eating.done?'Complete ✓':'Open')+'</span></div><p>Complete at 120g+ protein and 1,700–2,100 kcal, or confirm the balanced portion guide. Gym days: aim for 2.5–3L water.</p><div class="wa-evidence-line">Logged: '+Number(check.proteinG||0)+'g protein · '+Number(check.calories||0)+' kcal</div><button type="button" class="btn btn-accent" onclick="openWinterArcEating(\''+today+'\')">Update eating</button></div>';
  };

  function persistSession(session,action){var snapshot=JSON.parse(JSON.stringify(STATE));session.updatedAt=new Date().toISOString();if(!saveStateOrRollback(snapshot))return false;emitLifeHubChange({action:action,entityId:session.id,dateKeys:[session.date],domains:['trainingSessions'],source:'winter-arc',rendered:true});return true}
  function activeDuration(session){if(session.status==='completed')return Number(session.durationSec||0);var timer=session.sessionTimer;if(timer&&typeof winterArcEvidenceElapsed==='function')return winterArcEvidenceElapsed(timer);return Math.max(0,Number(session.durationSec||0))}
  function findParts(sessionId,exerciseId,setId){var session=(STATE.trainingSessions||{})[sessionId],exercise=session&&(session.exercises||[]).find(function(ex){return ex.id===exerciseId}),set=exercise&&(exercise.sets||[]).find(function(item){return item.id===setId});return {session:session,exercise:exercise,set:set}}
  function startRest(session,seconds){session.restTimer={anchorMs:Date.now(),durationSec:Number(seconds)||60}}
  function hideWinterArcRestPopup(){var overlay=document.getElementById('winter-arc-rest-overlay');if(overlay){overlay.hidden=true;delete overlay.dataset.sessionId}}
  function renderWinterArcRestPopup(session){var overlay=document.getElementById('winter-arc-rest-overlay'),clock=document.getElementById('winter-arc-rest-clock'),skip=document.getElementById('winter-arc-rest-skip');if(!overlay||!clock||!session||!session.restTimer){hideWinterArcRestPopup();return}var left=Math.max(0,Number(session.restTimer.durationSec)-Math.floor((Date.now()-Number(session.restTimer.anchorMs))/1000));if(left<=0){hideWinterArcRestPopup();return}var opening=overlay.hidden;overlay.dataset.sessionId=session.id;clock.textContent=fmtSeconds(left);overlay.hidden=false;if(opening&&skip)setTimeout(function(){skip.focus()},0)}
  global.winterArcSkipRestFromPopup=function(){var overlay=document.getElementById('winter-arc-rest-overlay'),id=overlay&&overlay.dataset.sessionId;if(id)winterArcSkipRest(id)};

  global.winterArcToggleSet=function(sessionId,exerciseId,setId){var parts=findParts(sessionId,exerciseId,setId);if(!parts.set)return;var done=!parts.set.done;if(updateTrainingSet(sessionId,exerciseId,setId,{done:done})&&done){var snapshot=JSON.parse(JSON.stringify(STATE)),session=STATE.trainingSessions[sessionId];startRest(session,parts.exercise.restSec);saveStateOrRollback(snapshot);renderWinterArcLogger(sessionId)}};
  global.winterArcAdjustSet=function(sessionId,exerciseId,setId,field,amount){var parts=findParts(sessionId,exerciseId,setId);if(!parts.set)return;var next=Math.max(0,Number(parts.set[field]||0)+Number(amount));if(updateTrainingSet(sessionId,exerciseId,setId,{[field]:Math.round(next*100)/100}))renderWinterArcLogger(sessionId)};
  global.winterArcSetValue=function(sessionId,exerciseId,setId,field,value){var next=Math.max(0,Number(value)||0);if(updateTrainingSet(sessionId,exerciseId,setId,{[field]:next}))renderWinterArcLogger(sessionId)};
  global.winterArcSetRating=function(sessionId,exerciseId,setId,field,value){if(updateTrainingSet(sessionId,exerciseId,setId,{[field]:value}))renderWinterArcLogger(sessionId)};
  global.winterArcUseSwap=function(sessionId,exerciseId){var parts=findParts(sessionId,exerciseId);if(!parts.exercise||!parts.exercise.swap)return;var snapshot=JSON.parse(JSON.stringify(STATE));parts.exercise.substitutedName=parts.exercise.swap;parts.exercise.name=parts.exercise.swap;parts.exercise.swapAccepted=true;parts.exercise.stopLatched=false;parts.exercise.swapFlag=false;(parts.exercise.sets||[]).forEach(function(set){set.done=false;set.pain='None'});parts.session.updatedAt=new Date().toISOString();if(saveStateOrRollback(snapshot))renderWinterArcLogger(sessionId)};
  global.winterArcSkipExercise=function(sessionId,exerciseId){var parts=findParts(sessionId,exerciseId);if(!parts.exercise)return;var snapshot=JSON.parse(JSON.stringify(STATE));parts.exercise.skippedAfterStop=true;parts.exercise.stopLatched=false;parts.exercise.swapFlag=false;(parts.exercise.sets||[]).forEach(function(set){set.done=false});parts.session.updatedAt=new Date().toISOString();if(saveStateOrRollback(snapshot))renderWinterArcLogger(sessionId)};
  global.winterArcChangeRung=function(sessionId,exerciseId,amount){var parts=findParts(sessionId,exerciseId);if(!parts.exercise)return;var snapshot=JSON.parse(JSON.stringify(STATE)),definition=definitionFor(parts.exercise.exerciseId),max=Math.max(1,Number(definition&&definition.rungs||7));parts.exercise.rung=Math.min(max,Math.max(1,Number(parts.exercise.rung||1)+Number(amount)));if(saveStateOrRollback(snapshot))renderWinterArcLogger(sessionId)};
  global.winterArcTimedSet=function(sessionId,exerciseId,setId){var parts=findParts(sessionId,exerciseId,setId);if(!parts.set)return;if(parts.set.timerAnchorMs){var elapsed=typeof winterArcEvidenceElapsed==='function'?winterArcEvidenceElapsed({anchorMs:parts.set.timerAnchorMs,heartbeatMs:parts.set.heartbeatMs,elapsedBeforeSec:parts.set.durationSec||0}):Number(parts.set.durationSec||0);updateTrainingSet(sessionId,exerciseId,setId,{durationSec:elapsed,timerAnchorMs:null,heartbeatMs:null,done:true});var snapshot=JSON.parse(JSON.stringify(STATE));startRest(STATE.trainingSessions[sessionId],parts.exercise.restSec);saveStateOrRollback(snapshot)}else{var now=Date.now();updateTrainingSet(sessionId,exerciseId,setId,{timerAnchorMs:now,heartbeatMs:now})}renderWinterArcLogger(sessionId)};
  global.winterArcSkipRest=function(sessionId){var s=(STATE.trainingSessions||{})[sessionId];if(!s)return;var snapshot=JSON.parse(JSON.stringify(STATE));s.restTimer=null;if(saveStateOrRollback(snapshot)){hideWinterArcRestPopup();renderWinterArcLogger(sessionId)}};
  global.winterArcSameLast=function(sessionId,exerciseId){if(sameAsLastTime(sessionId,exerciseId))renderWinterArcLogger(sessionId)};
  global.winterArcAddSet=function(sessionId,exerciseId){
    var parts=findParts(sessionId,exerciseId);if(!parts.session||!parts.exercise||parts.session.status!=='in-progress'||parts.exercise.sets.length>=12)return false;var snapshot=JSON.parse(JSON.stringify(STATE)),previous=parts.exercise.sets[parts.exercise.sets.length-1]||{},set=JSON.parse(JSON.stringify(previous)),suffix;
    delete set.timerAnchorMs;delete set.heartbeatMs;set.done=false;set.effort='Right';set.pain='None';set.extra=true;
    do{suffix='x'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);set.id=parts.exercise.id+'__'+suffix}while(parts.exercise.sets.some(function(item){return item.id===set.id}));
    parts.exercise.sets.push(set);parts.session.updatedAt=new Date().toISOString();pendingSetFocus=set.id;if(!saveStateOrRollback(snapshot)){pendingSetFocus=null;return false}emitLifeHubChange({action:'training-set-add',entityId:set.id,dateKeys:[parts.session.date],domains:['trainingSessions'],source:'winter-arc',rendered:true});renderWinterArcLogger(sessionId);return true;
  };

  function setControl(session,exercise,set,index){var isTime=exercise.mode==='time',isDistance=exercise.mode==='distance',valueField=isTime?'durationSec':isDistance?'distanceM':'reps',value=Number(set[valueField]||0),unit=exercise.unit||'reps',workLabel=isDistance?'distance':unit,workUnit=isDistance?'m':unit,loadControl=exercise.loadType&&['bodyweight','time','notch'].indexOf(exercise.loadType)===-1?'<div class="wa-stepper"><button type="button" onclick="winterArcAdjustSet(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\',\'loadKg\',-0.5)" data-wa-key="load-minus:'+set.id+'" aria-label="Decrease weight">−</button><input type="number" min="0" step="0.5" data-wa-key="load:'+set.id+'" value="'+Number(set.loadKg||0)+'" onchange="winterArcSetValue(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\',\'loadKg\',this.value)" aria-label="Weight in kilograms"><span>kg</span><button type="button" onclick="winterArcAdjustSet(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\',\'loadKg\',0.5)" data-wa-key="load-plus:'+set.id+'" aria-label="Increase weight">+</button></div>':'';
    var workControl=isTime?'<button type="button" class="wa-timer-btn'+(set.timerAnchorMs?' running':'')+'" data-wa-key="timer:'+set.id+'" onclick="winterArcTimedSet(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\')" data-timed-set="'+set.id+'">'+(set.timerAnchorMs?'Stop timer':'Start · '+fmtSeconds(value))+'</button>':'<div class="wa-stepper"><button type="button" onclick="winterArcAdjustSet(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\',\''+valueField+'\','+(isDistance?-5:-1)+')" data-wa-key="work-minus:'+set.id+'" aria-label="Decrease '+workLabel+'">−</button><input type="number" min="0" step="'+(isDistance?5:1)+'" data-wa-key="work:'+set.id+'" value="'+value+'" onchange="winterArcSetValue(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\',\''+valueField+'\',this.value)" aria-label="'+(isDistance?'Distance in metres':unit.charAt(0).toUpperCase()+unit.slice(1))+'"><span>'+workUnit+'</span><button type="button" onclick="winterArcAdjustSet(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\',\''+valueField+'\','+(isDistance?5:1)+')" data-wa-key="work-plus:'+set.id+'" aria-label="Increase '+workLabel+'">+</button></div>';
    return '<div class="wa-set-row'+(set.done?' done':'')+'"><button type="button" class="wa-one-tap" data-wa-key="done:'+set.id+'" onclick="winterArcToggleSet(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\')"'+(exercise.stopLatched?' disabled':'')+' aria-pressed="'+(set.done?'true':'false')+'" aria-label="Mark set '+(index+1)+' complete">'+(set.done?'✓':'S'+(index+1))+'</button>'+loadControl+workControl+'<div class="wa-rating" role="group" aria-label="Effort">'+['Easy','Right','Hard'].map(function(v){return '<button type="button" data-wa-key="effort:'+set.id+':'+v+'" aria-pressed="'+(set.effort===v?'true':'false')+'" class="'+(set.effort===v?'selected':'')+'" onclick="winterArcSetRating(\''+session.id+'\',\''+exercise.id+'\',\''+set.id+'\',\'effort\',\''+v+'\')">'+v+'</button>'}).join('')+'</div></div>'}
  function exerciseCard(session,exercise){var next=exercise.next,swap=exercise.swapFlag?'<div class="wa-stop-callout" role="alert"><strong>Stop this exercise.</strong> '+esc(exercise.swap?'Swap to '+exercise.swap+'.':'Skip it today and follow clinical guidance.')+(exercise.swap?'<button type="button" data-wa-key="swap:'+exercise.id+'" class="btn btn-sm" onclick="winterArcUseSwap(\''+session.id+'\',\''+exercise.id+'\')">Use '+esc(exercise.swap)+'</button>':'')+'<button type="button" data-wa-key="skip:'+exercise.id+'" class="btn btn-sm btn-ghost" onclick="winterArcSkipExercise(\''+session.id+'\',\''+exercise.id+'\')">Skip exercise</button>'+'</div>':'';return '<section class="wa-exercise'+(exercise.coreMicrodose?' wa-core-exercise':'')+'" data-wa-exercise="'+esc(exercise.id)+'" tabindex="-1"><div class="wa-exercise-head"><div><span>'+(exercise.coreMicrodose?'DAILY CORE · ':'')+esc(exercise.exerciseId)+'</span><h3>'+esc(exercise.name)+'</h3><p>'+(exercise.range?exercise.range[0]+'–'+exercise.range[1]+' '+esc(exercise.unit||'reps')+' · ':'')+'RIR '+exercise.targetRir+(exercise.sides?' · '+esc(exercise.sides):'')+' · rest '+exercise.restSec+'s</p></div><div class="wa-exercise-actions">'+(exercise.mode==='ladder'?'<div class="wa-rung"><button type="button" data-wa-key="rung-minus:'+exercise.id+'" onclick="winterArcChangeRung(\''+session.id+'\',\''+exercise.id+'\',-1)">−</button><span>Rung '+Number(exercise.rung||1)+'</span><button type="button" data-wa-key="rung-plus:'+exercise.id+'" onclick="winterArcChangeRung(\''+session.id+'\',\''+exercise.id+'\',1)">+</button></div>':'')+'<button type="button" data-wa-key="same:'+exercise.id+'" class="btn btn-sm btn-ghost" onclick="winterArcSameLast(\''+session.id+'\',\''+exercise.id+'\')">Same as last time</button><button type="button" data-wa-key="add-set:'+exercise.id+'" class="btn btn-sm btn-ghost" onclick="winterArcAddSet(\''+session.id+'\',\''+exercise.id+'\')"'+(exercise.sets.length>=12?' disabled':'')+'>+ Add set</button></div></div>'+swap+'<div class="wa-sets">'+exercise.sets.map(function(set,index){return setControl(session,exercise,set,index)}).join('')+'</div>'+(next?'<div class="wa-next"><strong>Next:</strong> '+esc(next.reason)+(next.loadKg!=null?' · '+next.loadKg+'kg':'')+'</div>':'')+'</section>'}

  function sessionMainCard(occurrence){
    if(!occurrence||occurrence.kind==='strength'||occurrence.kind==='rest')return '';
    var prescription=occurrence.interval&&occurrence.interval.label||(occurrence.blocks||[]).map(function(block){return block[0]+' '+block[1]+' min'}).join(' · ')||(occurrence.options||[]).join(' · ')||occurrence.label;
    return '<div class="wa-cardio-session"><strong>'+esc(occurrence.label)+'</strong><p>'+esc(prescription)+'</p>'+(occurrence.core?'<span class="wa-core-chip">Daily core · '+esc(occurrence.core.label)+'</span>':'')+'</div>';
  }

  function previousBestE1rm(exerciseId,beforeDate){var best=0;Object.keys(STATE.trainingSessions||{}).forEach(function(id){var session=STATE.trainingSessions[id];if(!session||session.status!=='completed'||session.date>=beforeDate)return;var ex=(session.exercises||[]).find(function(item){return item.exerciseId===exerciseId});(ex&&ex.sets||[]).forEach(function(set){if(set.done&&Number(set.loadKg)>0&&Number(set.reps)>0)best=Math.max(best,Number(set.loadKg)*(1+Number(set.reps)/30))})});return best}

  global.renderWinterArcPreview=function(value,existing){hideWinterArcRestPopup();var key=value||localDateKey(new Date()),occurrence=winterArcOccurrence(key),content=winterArcContent();if(!occurrence||!content)return;var future=key>localDateKey(new Date());content.innerHTML='<div class="wa-modal-kicker">SESSION PREVIEW</div><h2>'+esc(occurrence.code+' · '+occurrence.label)+'</h2><div class="modal-sub">'+esc(fmtDate(key))+' · '+esc(phaseCopy(occurrence))+'</div><div class="wa-safety-banner planned"><strong>Preview only</strong><span>'+(future?'This session unlocks on '+esc(fmtDate(key))+'.':'This session was scheduled for '+esc(fmtDate(key))+'.')+' Opening a preview does not start a timer or create a workout.</span></div><ul class="wa-plan-details">'+occurrenceDetail(occurrence)+'</ul>'+(existing&&existing.status==='in-progress'?'<div class="wa-stop-callout"><strong>An older preview draft is still marked in progress.</strong><span>Discard it to remove the test session and its timer.</span></div>':'')+'<div class="modal-btns">'+(existing&&existing.status==='in-progress'?'<button type="button" class="btn btn-danger" onclick="deleteWinterArcSession(\''+existing.id+'\')">Discard draft</button>':'')+'<button type="button" class="btn btn-accent" onclick="closeWinterArcPage()">Close preview</button></div>'}

  global.renderWinterArcLogger=function(sessionId){
    var session=(STATE.trainingSessions||{})[sessionId],content=winterArcContent();if(!session||!content)return;var focused=document.activeElement,focusKey=focused&&focused.getAttribute&&focused.getAttribute('data-wa-key'),scrollTop=content.scrollTop;var occurrence=effectiveWinterArcOccurrence(session.date)||winterArcOccurrence(session.date),duration=activeDuration(session),rest=session.restTimer,restLeft=rest?Math.max(0,Number(rest.durationSec)-Math.floor((Date.now()-Number(rest.anchorMs))/1000)):0;
    if(session.status==='completed'){hideWinterArcRestPopup();content.innerHTML='<div class="wa-modal-kicker">SESSION COMPLETE</div><h2>'+esc(session.label)+'</h2><div class="wa-session-summary"><strong>'+Math.floor(Number(session.durationSec||0)/60)+' min</strong><span>'+esc(fmtDate(session.date))+'</span></div>'+(session.exercises||[]).map(function(ex){var best=(ex.sets||[]).filter(function(s){return s.done}).sort(function(a,b){return Number(b.loadKg||0)*(1+Number(b.reps||0)/30)-Number(a.loadKg||0)*(1+Number(a.reps||0)/30)})[0],e1=!ex.coreMicrodose&&best&&best.loadKg&&best.reps?Math.round(Number(best.loadKg)*(1+Number(best.reps)/30)*10)/10:null,previousBest=previousBestE1rm(ex.exerciseId,session.date),isPr=e1&&e1>previousBest+0.01;return '<div class="wa-summary-row"><span>'+esc(ex.name)+(isPr?' <b class="wa-pr">PR</b>':'')+'</span><strong>'+(e1?'e1RM '+e1+'kg':'Complete')+'</strong><small>'+esc(ex.next&&ex.next.reason||'')+(ex.next&&ex.next.loadKg!=null?' · next '+ex.next.loadKg+'kg':'')+'</small></div>'}).join('')+'<div class="modal-btns"><button type="button" data-wa-key="finish" class="btn btn-accent" onclick="closeWinterArcPage()">Done</button></div>';content.scrollTop=scrollTop;if(focusKey==='finish'){var completedFocus=content.querySelector('[data-wa-key="finish"]');if(completedFocus)setTimeout(function(){completedFocus.focus({preventScroll:true})},0)}return}
    content.innerHTML='<div class="wa-logger-head"><div><div class="wa-modal-kicker">'+esc(phaseCopy(occurrence))+'</div><h2>'+esc(session.label)+'</h2><p>'+esc(fmtDate(session.date))+' · <span data-session-clock>'+fmtSeconds(duration)+'</span></p></div></div>'+(session.safety&&session.safety.action!=='planned'?'<div class="wa-safety-banner '+esc(session.safety.level)+'"><strong>'+esc(session.safety.title)+'</strong><span>'+esc(session.safety.message)+'</span></div>':'')+sessionMainCard(occurrence)+(session.exercises&&session.exercises.length?session.exercises.map(function(ex){return exerciseCard(session,ex)}).join(''):'')+'<div class="wa-logger-footer"><span>Workout rule completes at 45 logged minutes.</span><div class="wa-logger-footer-actions"><button type="button" class="btn btn-ghost" onclick="deleteWinterArcSession(\''+session.id+'\')">Discard session</button><button type="button" data-wa-key="finish" class="btn btn-accent" onclick="finishWinterArcWorkout(\''+session.id+'\')">Finish session</button></div></div>';
    content.scrollTop=scrollTop;if(focusKey){var safeKey=typeof CSS!=='undefined'&&CSS.escape?CSS.escape(focusKey):focusKey.replace(/"/g,'\\"'),focusTarget=content.querySelector('[data-wa-key="'+safeKey+'"]');if(!focusTarget&&/^(swap|skip):/.test(focusKey)){var exerciseKey=focusKey.slice(focusKey.indexOf(':')+1),safeExercise=typeof CSS!=='undefined'&&CSS.escape?CSS.escape(exerciseKey):exerciseKey;focusTarget=content.querySelector('[data-wa-exercise="'+safeExercise+'"]')}if(!focusTarget&&focusKey==='rest-skip')focusTarget=content.querySelector('[data-wa-key="finish"]');if(focusTarget)setTimeout(function(){focusTarget.focus({preventScroll:true})},0)}if(pendingSetFocus){var newSetFocus=content.querySelector('[data-wa-key="done:'+pendingSetFocus+'"]');pendingSetFocus=null;if(newSetFocus)setTimeout(function(){newSetFocus.focus({preventScroll:true})},0)}
    renderWinterArcRestPopup(session);if(loggerTicker)clearInterval(loggerTicker);loggerTicker=setInterval(function(){var current=(STATE.trainingSessions||{})[sessionId],clock=content.querySelector('[data-session-clock]');if(!current||!clock){clearInterval(loggerTicker);loggerTicker=null;return}clock.textContent=fmtSeconds(activeDuration(current));if(current.restTimer){var left=Math.max(0,Number(current.restTimer.durationSec)-Math.floor((Date.now()-Number(current.restTimer.anchorMs))/1000)),restClock=document.getElementById('winter-arc-rest-clock');if(left<=0){current.restTimer=null;saveState({suppressUndo:true});hideWinterArcRestPopup()}else if(restClock)restClock.textContent=fmtSeconds(left)}content.querySelectorAll('[data-timed-set]').forEach(function(node){var parts=null;(current.exercises||[]).some(function(ex){var set=(ex.sets||[]).find(function(s){return s.id===node.getAttribute('data-timed-set')});if(set){parts=set;return true}return false});if(parts&&parts.timerAnchorMs)node.textContent='Stop · '+fmtSeconds(typeof winterArcEvidenceElapsed==='function'?winterArcEvidenceElapsed({anchorMs:parts.timerAnchorMs,heartbeatMs:parts.heartbeatMs,elapsedBeforeSec:parts.durationSec||0}):Number(parts.durationSec||0))})},1000);
  };

  global.openWinterArcWorkout=function(value){
    var key=value||localDateKey(new Date()),occurrence=effectiveWinterArcOccurrence(key);if(!occurrence)return;var id=occurrence.id,existing=(STATE.trainingSessions||{})[id],active=document.querySelector('.page.active'),returnPage=active&&!active.id.includes('winter-arc')?active.id.replace(/^page-/,''):'workout',returnTab=returnPage==='workout'?activeWorkoutTab():'overview',base={date:key,returnPage:returnPage,returnTab:returnTab,opener:document.activeElement};
    if(existing&&existing.status==='completed'){openWinterArcPageRoute(Object.assign(base,{mode:'logger',sessionId:id}));return}
    if(key!==localDateKey(new Date())){openWinterArcPageRoute(Object.assign(base,{mode:'preview',sessionId:existing&&existing.id||null}));return}
    id=startWinterArcSession(key);if(!id){if(typeof showCelebrationToast==='function')showCelebrationToast('Full rest is selected for today','♡');return}openWinterArcPageRoute(Object.assign(base,{mode:'logger',sessionId:id}));
  };
  global.finishWinterArcWorkout=function(sessionId){var s=(STATE.trainingSessions||{})[sessionId];if(!s)return;var duration=activeDuration(s);if(finishWinterArcSession(sessionId,duration)){if(typeof showCelebrationToast==='function')showCelebrationToast(duration>=2700?'45-minute plan workout complete':'Session saved · keep going to 45 minutes for the daily rule','✨');renderWinterArcLogger(sessionId)}else{if(typeof showCelebrationToast==='function')showCelebrationToast('Resolve the safety stop or full-rest override first','♡');renderWinterArcLogger(sessionId)}};
  global.deleteWinterArcSession=function(sessionId){var session=(STATE.trainingSessions||{})[sessionId];if(!session)return;var showing=!!(winterArcRoute&&winterArcRoute.sessionId===sessionId);confirmDelete('Delete this Winter Arc session? The dated plan remains available.',function(){var snapshot=JSON.parse(JSON.stringify(STATE));delete STATE.trainingSessions[sessionId];if(!saveStateOrRollback(snapshot))return false;emitLifeHubChange({action:'training-delete',entityId:sessionId,dateKeys:[session.date],domains:['trainingSessions'],source:'winter-arc'});if(showing)setTimeout(closeWinterArcPage,0);return true})};
})(typeof window!=='undefined'?window:globalThis);


(function(){
  if(typeof document==='undefined')return;
  var heartbeatId=null;
  function startHeartbeat(){if(heartbeatId)return;heartbeatId=setInterval(function(){if(typeof heartbeatWinterArcEvidence==='function')heartbeatWinterArcEvidence()},30000)}
  document.addEventListener('visibilitychange',function(){if(document.hidden){if(typeof pauseWinterArcEvidenceTimers==='function')pauseWinterArcEvidenceTimers()}else{if(typeof resumeWinterArcEvidenceTimers==='function')resumeWinterArcEvidenceTimers();startHeartbeat()}});
  window.addEventListener('pagehide',function(){if(typeof pauseWinterArcEvidenceTimers==='function')pauseWinterArcEvidenceTimers()});
  document.addEventListener('lifehub:ready',function(){if(typeof resumeWinterArcEvidenceTimers==='function')resumeWinterArcEvidenceTimers();startHeartbeat()});
})();
